// The Squad — Lead: A2 Psych | Support: A7 Artisan
// Intimacy per-resident + archetype voice — mined from legacyIntimacy.snapshot.js.
// Regenerate: node scripts/generateIntimacyPersonas.mjs
import { registerModuleVariants } from '../../engine.js';
import './depth.js';
import './selectors.js';

registerModuleVariants('intimacy.approach', [
  { when: {"archetype":["athlete"]}, weight: 2, text: ["\"You have no idea how strong I actually am.\"","She watches your hands with the focused attention she used to give to game tape.","Her breath catches — then she resets, the way she always resets. Controlled. Deliberate."] },
  { when: {"archetype":["influencer"]}, weight: 2, text: ["\"Tell me how I look right now.\"","She tilts her head the way she does for photos — except she's not smiling. She's watching.","A small, knowing sound. \"I knew you'd like that.\""] },
  { when: {"archetype":["cheerleader"]}, weight: 2, text: ["\"Oh my god — okay — that's — okay.\"","She laughs, delighted, slightly breathless, like a crowd just roared.","\"You're supposed to be you,\" she says, which is not a complaint."] },
  { when: {"archetype":["bookworm"]}, weight: 2, text: ["\"Interesting. That's — I'm noticing several things at once.\"","She processes. Actually processes. You can almost see it.","\"I've read about this,\" she says. \"It's not the same as — it's very different actually.\""] },
  { when: {"archetype":["swimmer"]}, weight: 2, text: ["\"Interesting. That's — I'm noticing several things at once.\"","She processes. Actually processes. You can almost see it.","\"I've logged this,\" she says. \"It's not the same as — it's very different actually.\""] },
  { when: {"archetype":["gamer"]}, weight: 2, text: ["\"Okay. Okay. No — wait. Yeah. Okay.\"","She makes a sound like she's just solved something difficult.","A pause. Then: \"Respawning in three, two — \" She shuts herself up."] },
  { when: {"archetype":["sorority"]}, weight: 2, text: ["\"Hi,\" she says softly, which is not a greeting but an arrival.","She settles into it like she settles into everything — with practiced warmth, with genuine ease.","\"I've been thinking about this,\" she says. This is not a surprise to you."] },
  { when: {"archetype":["overachiever"]}, weight: 2, text: ["\"This is — I'm noting the physiological responses. For reference.\"","She's still taking internal inventory. Old habit.","Her analytical distance collapses suddenly, all at once. \"Oh,\" she says. Just that."] },
  { when: {"archetype":["artsy"]}, weight: 2, text: ["\"You're touching something I haven't named yet.\"","She observes the experience the way she observes material — with a kind of hunger.","\"The weight of me,\" she says softly. \"You can feel the whole weight of me.\""] },
  { when: {"archetype":["quiet"]}, weight: 2, text: ["She makes a small, soft sound that you understand entirely.","Her eyes are very steady on yours. She doesn't look away.","A slight, certain nod. Yes."] },
  { when: {"archetype":["transfer"]}, weight: 2, text: ["\"I'm going to be honest with you — I've been thinking about this.\"","She looks at you with the directness she always has, nothing performed about it.","\"Yes,\" she says simply. \"This.\""] },
  { when: {"studentId":[0]}, weight: 4, text: ["\"Okay but you have to admit I'm your biggest one now,\" she says, and means it as a compliment.","She bounces — actually bounces — and then laughs at herself for bouncing. \"I did not mean to do that.\"","\"Feel that? That's like twenty pounds just in my thighs. Isn't that insane?\""] },
  { when: {"studentId":[2]}, weight: 4, text: ["\"Wait — what's my angle right now? Is this good? I feel like this is a good angle.\"","She adjusts her hair on instinct, then catches herself. \"Sorry. Habit.\"","\"Tell me I look good like this. I mean it. Tell me.\"","\"I hope you like what you find,\" she says. She means all of it — the weight, the warmth, all of it.","She watches you with genuine warmth, nothing performed about it.","\"I've been wanting you to look at me like that,\" she says. \"Specifically like that.\""] },
  { when: {"studentId":[6]}, weight: 4, text: ["\"Sweetheart,\" she says warmly, which is how she begins everything that matters.","She curls into you with practiced, genuine ease. \"Finally,\" she says.","\"You've been patient,\" she says. \"I noticed that. I wanted you to know I noticed.\""] },
  { when: {"studentId":[1]}, weight: 4, text: ["\"So the — the thing that's happening is — I have thoughts. Multiple thoughts. Conflicting.\"","She adjusts her glasses and then takes them off entirely, which is significant.","\"I've been thinking about the physics of this,\" she says. \"Specifically the pressure distributions.\""] },
  { when: {"studentId":[3]}, weight: 4, text: ["\"I've been working out but honestly I've also been eating a lot so I don't know what you're — okay. You feel that? That's not fat. That's — well. Some of it.\"","She rolls her shoulders like she's warming up for something. Old reflex.","\"You're going to tell everyone you beat me,\" she says. \"I can tell.\"","\"Feel that?\" She flexes her thigh against you deliberately. \"Two hundred of that is pure me.\"","She watches your expression with an athlete's attention to feedback.","\"I've been working on my capacity,\" she says. \"You should test it.\""] },
  { when: {"studentId":[8]}, weight: 4, text: ["She leans in by three degrees. An enormous declaration, from her.","Her hand finds yours without looking. She holds it. Doesn't let go.","A sound: small, soft, completely certain.","A breath. Just a breath. Then she moves fractionally closer.","Her eyes close. Her whole body makes a decision without a word.","She presses her palm flat against yours. The gesture is complete."] },
  { when: {"studentId":[4]}, weight: 4, text: ["\"I've been thinking of myself as a medium,\" she says. \"You're working with me now.\"","She closes her eyes and tilts her head back. \"I want to know what you're perceiving.\"","\"My body has become a landscape,\" she says softly. \"You're mapping it.\""] },
  { when: {"studentId":[5]}, weight: 4, text: ["\"Loading screen,\" she says. \"I'm having a loading screen. Give me a second.\"","She covers her face with both hands. Then uncovers it. \"Hi. Okay. Hi.\"","\"I've thought about this in an extremely fictional context,\" she says. \"This is not that.\""] },
  { when: {"studentId":[7]}, weight: 4, text: ["\"Noting elevated heart rate. Mine, not yours. Just for the record.\"","She straightens her back and then immediately un-straightens it. First time you've seen that.","\"I've been projecting for this scenario,\" she says. \"My projections were inaccurate.\"","\"I have approximately seven concurrent thoughts about this and I'm working to reduce them.\"","She inhales through her nose in the precise way she does before a presentation.","\"The data here is subjective,\" she says. \"I'm finding that acceptable.\""] },
  { when: {"studentId":[9]}, weight: 4, text: ["\"I didn't know what this school was going to be,\" she says. \"I'm glad it was this.\"","She meets your eyes with the directness that's been there since day one.","\"I'm not going to pretend I haven't thought about this,\" she says."] },
  { when: {"studentId":[10]}, weight: 4, text: ["\"Touch is data,\" she says. \"You're reading something that took a year to write.\"","She holds up her arm, examining it alongside you. \"The volume changed in November. Can you tell?\"","\"My body is the work now,\" she says. \"The medium became the message.\""] },
  { when: {"studentId":[11]}, weight: 4, text: ["\"Vitals are elevated,\" she murmurs, already clinical about herself. \"That's expected.\"","She checks your hands the way she'd check a chart — careful, warm, unhurried."] },
  { when: {"studentId":[12]}, weight: 4, text: ["\"You're watching me watch you,\" she says. \"That's the whole dynamic, isn't it?\"","She holds your gaze with unsettling calm. \"I've been curious about this.\""] },
  { when: {"studentId":[13]}, weight: 4, text: ["\"Well bless your heart,\" she says warmly, settling in like she's always belonged here.","She curls close with practiced southern ease. \"There you are, sugar.\""] },
  { when: {"studentId":[14]}, weight: 4, text: ["\"Feels like harvest season,\" she says, amused. \"All this abundance.\"","She leans in with country certainty. \"Been thinking about this, honest.\""] },
  { when: {"studentId":[15]}, weight: 4, text: ["She watches you without blinking. \"Soon,\" she says. It isn't a threat.","A small, amused sound. She already knows how this ends."] },
  { when: {"studentId":[16]}, weight: 4, text: ["\"Heart rate's up,\" she whispers. \"Mine, I mean. I double-checked.\"","She adjusts her glasses, then leaves them off. Significant."] },
  { when: {"studentId":[17]}, weight: 4, text: ["\"Uncharted territory,\" he says, grinning. \"My favorite kind.\"","He maps your reaction like a new dig site — delighted, thorough."] },
]);
registerModuleVariants('intimacy.resistance', [
  { when: {"archetype":["athlete"]}, weight: 2, text: ["\"I'm not — I'm just seeing what you're — stop looking at me like that.\""] },
  { when: {"archetype":["influencer"]}, weight: 2, text: ["\"I'm aware of exactly what I look like right now, thank you.\""] },
  { when: {"archetype":["cheerleader"]}, weight: 2, text: ["\"I'm not — I mean we shouldn't — \" She's already leaning in."] },
  { when: {"archetype":["bookworm"]}, weight: 2, text: ["\"I just think we should — there are a number of considerations — \""] },
  { when: {"archetype":["swimmer"]}, weight: 2, text: ["\"I just think we should — there are a number of considerations — \""] },
  { when: {"archetype":["gamer"]}, weight: 2, text: ["\"I'm not nervous, I'm just — input lag. I'm experiencing input lag.\""] },
  { when: {"archetype":["sorority"]}, weight: 2, text: ["\"Baby, I'm just saying we should — \" She stops. \"Never mind what I was saying.\""] },
  { when: {"archetype":["overachiever"]}, weight: 2, text: ["\"I should probably catalogue — I mean I should — \" The catalogue is abandoned."] },
  { when: {"archetype":["artsy"]}, weight: 2, text: ["\"I'm just trying to stay present. I keep wanting to describe it instead of — \""] },
  { when: {"archetype":["quiet"]}, weight: 2, text: ["A small shake of her head — not no, exactly. More: not yet. Slightly. Soon."] },
  { when: {"archetype":["transfer"]}, weight: 2, text: ["\"I'm not holding back, I just want you to — just — slower. Yes. Slower.\""] },
  { when: {"studentId":[0]}, weight: 4, text: ["\"I'm just saying you should appreciate all of this properly. Starting from the top.\""] },
  { when: {"studentId":[2]}, weight: 4, text: ["\"I'm just very aware of — I mean you can see everything from where you — tell me it's good.\"","\"Tell me what you want first. I want to know what you want. Then we'll — yes. That.\""] },
  { when: {"studentId":[6]}, weight: 4, text: ["\"Baby, just — let me just rearrange — there. That's better. That's so much better.\""] },
  { when: {"studentId":[1]}, weight: 4, text: ["\"I'm not — it's just — I want to process this properly — oh.\""] },
  { when: {"studentId":[3]}, weight: 4, text: ["\"I'm not — I train for endurance, okay, this is — fine. Fine. Come here.\"","\"I'm not nervous — athletes don't get nervous — I'm just — come here. Stop asking.\""] },
  { when: {"studentId":[8]}, weight: 4, text: ["She turns her face away once, briefly. Then back. You wait. She nods.","She turns her head. Not away — just to the side, briefly. She turns back."] },
  { when: {"studentId":[4]}, weight: 4, text: ["\"I'm processing the aesthetic experience simultaneously — I can do both — oh. Maybe not both.\""] },
  { when: {"studentId":[5]}, weight: 4, text: ["\"I'm not panicking, I'm just operating at an elevated — okay I'm a little panicked.\""] },
  { when: {"studentId":[7]}, weight: 4, text: ["\"I should clarify my parameters before — nope. Parameters abandoned. Moving forward.\"","\"I want to catalogue the sensation first — I realize that sounds — I'm aware that sounds — \""] },
  { when: {"studentId":[9]}, weight: 4, text: ["\"Slower. Just — tell me what you're — yes. Like that. Yes.\""] },
  { when: {"studentId":[10]}, weight: 4, text: ["\"I want you to understand what you're touching before you — yes. That. Now you understand.\""] },
  { when: {"studentId":[11]}, weight: 4, text: ["\"I should document the baseline first — oh. Never mind the baseline.\""] },
  { when: {"studentId":[12]}, weight: 4, text: ["\"I want to name what's happening before we — no. After. We'll name it after.\""] },
  { when: {"studentId":[13]}, weight: 4, text: ["\"Baby, let me just — there. That's better. Don't you dare stop now.\""] },
  { when: {"studentId":[14]}, weight: 4, text: ["\"Hold on — let me catch my breath — okay. Okay, come here.\""] },
  { when: {"studentId":[15]}, weight: 4, text: ["She turns her face once — not away. Measuring. Then she doesn't resist."] },
  { when: {"studentId":[16]}, weight: 4, text: ["\"I should verify the dosage — I mean the pacing — oh.\""] },
  { when: {"studentId":[17]}, weight: 4, text: ["\"Give me a second to — alright. Lead on, RA.\""] },
]);
registerModuleVariants('intimacy.encourages', [
  { when: {"archetype":["athlete"]}, weight: 2, text: ["\"Yeah. That. Keep doing that.\""] },
  { when: {"archetype":["influencer"]}, weight: 2, text: ["\"More. Come on. Don't stop.\""] },
  { when: {"archetype":["cheerleader"]}, weight: 2, text: ["\"Don't stop. Seriously. I will literally die if you stop.\""] },
  { when: {"archetype":["bookworm"]}, weight: 2, text: ["\"Please. Please don't stop. I'll be quiet. I'll stop analyzing. Please.\""] },
  { when: {"archetype":["swimmer"]}, weight: 2, text: ["\"Please. Please don't stop. I'll be quiet. I'll stop logging splits. Please.\""] },
  { when: {"archetype":["gamer"]}, weight: 2, text: ["\"Keep going. I'm not telling you to stop. I'm the opposite of telling you to stop.\""] },
  { when: {"archetype":["sorority"]}, weight: 2, text: ["\"Mm. Yes. Exactly that.\""] },
  { when: {"archetype":["overachiever"]}, weight: 2, text: ["\"I need you to understand that I am fully committed to this outcome.\""] },
  { when: {"archetype":["artsy"]}, weight: 2, text: ["\"I want you to know what this feels like. I want you to know exactly.\""] },
  { when: {"archetype":["quiet"]}, weight: 2, text: ["She takes your hand and moves it herself, without words, with complete precision."] },
  { when: {"archetype":["transfer"]}, weight: 2, text: ["\"Tell me what you think. Tell me what you're feeling. I want to know.\""] },
  { when: {"studentId":[0]}, weight: 4, text: ["\"Yes, that part, that's my favorite part, don't skip it.\""] },
  { when: {"studentId":[2]}, weight: 4, text: ["\"I want you to want this. I need you to want this. Do you? Say it.\"","\"I want you to enjoy this. I want that so much. Are you? Tell me you are.\""] },
  { when: {"studentId":[6]}, weight: 4, text: ["\"I love your hands. I love them. Keep going, honey.\""] },
  { when: {"studentId":[1]}, weight: 4, text: ["\"Please don't stop. I'll stop talking about physics, I promise. Please.\""] },
  { when: {"studentId":[3]}, weight: 4, text: ["\"Harder. I mean — yes. More. I'm not made of glass.\"","\"More. I can take more. Don't go easy.\""] },
  { when: {"studentId":[8]}, weight: 4, text: ["She moves your hand to where she wants it and leaves hers on top.","She puts her hand over yours and presses. Down. More. Yes."] },
  { when: {"studentId":[4]}, weight: 4, text: ["\"The density here is new. Two months ago this wasn't here. Do you feel the difference?\""] },
  { when: {"studentId":[5]}, weight: 4, text: ["\"Yes. That. Don't patch it out.\""] },
  { when: {"studentId":[7]}, weight: 4, text: ["\"Please continue. I've stopped evaluating. That's new. Please continue.\"","\"Continue. I've set aside the catalogue. Please continue.\""] },
  { when: {"studentId":[9]}, weight: 4, text: ["\"You can say what you're thinking. I want to know what you're thinking.\""] },
  { when: {"studentId":[10]}, weight: 4, text: ["\"The color of this — I've been calling it amber but it's more like — do you feel the warmth? That specific warmth?\""] },
  { when: {"studentId":[11]}, weight: 4, text: ["\"Continue. I'm noting everything. Please don't stop.\""] },
  { when: {"studentId":[12]}, weight: 4, text: ["\"Tell me what you're perceiving. I want the full subjective report.\""] },
  { when: {"studentId":[13]}, weight: 4, text: ["\"More, honey. I want all of it. You're doing so good.\""] },
  { when: {"studentId":[14]}, weight: 4, text: ["\"Like that. Yes. Don't go easy on me.\""] },
  { when: {"studentId":[15]}, weight: 4, text: ["She guides your hand with absolute precision. No words required."] },
  { when: {"studentId":[16]}, weight: 4, text: ["\"Please continue. The wellness outcomes are favorable.\""] },
  { when: {"studentId":[17]}, weight: 4, text: ["\"Keep going. I want the full expedition.\""] },
]);
registerModuleVariants('intimacy.psychVoice', [
  { when: {"archetype":["athlete"]}, weight: 2, text: ["She makes small competitive sounds, like she's winning something."] },
  { when: {"archetype":["influencer"]}, weight: 2, text: ["She narrates softly — \"there\" and \"yes\" and \"exactly there\" — a running edit of herself."] },
  { when: {"archetype":["cheerleader"]}, weight: 2, text: ["She's enthusiastic, emphatic, the way she's enthusiastic about everything she commits to."] },
  { when: {"archetype":["bookworm"]}, weight: 2, text: ["Small, lost sounds. All the words have left her."] },
  { when: {"archetype":["swimmer"]}, weight: 2, text: ["Small, lost sounds. All the words have left her."] },
  { when: {"archetype":["gamer"]}, weight: 2, text: ["She's gone. The humor, the deflection, all of it gone. Just her, present, breathing."] },
  { when: {"archetype":["sorority"]}, weight: 2, text: ["She is warm and present and entirely certain. No second thoughts. No hesitation."] },
  { when: {"archetype":["overachiever"]}, weight: 2, text: ["She stops performing competence. It's remarkable — you've never seen her stop."] },
  { when: {"archetype":["artsy"]}, weight: 2, text: ["She narrates in metaphors, half-whispered, then the metaphors stop and only the feeling remains."] },
  { when: {"archetype":["quiet"]}, weight: 2, text: ["She breathes. That's all. Perfectly, completely present in every breath."] },
  { when: {"archetype":["transfer"]}, weight: 2, text: ["She's open, present, entirely unhidden. This is how she does everything."] },
  { when: {"studentId":[0]}, weight: 4, text: ["She provides running commentary on her own body with the enthusiasm of a sportscast."] },
  { when: {"studentId":[2]}, weight: 4, text: ["She watches you watching her. The performance and the reality have merged completely.","She is warm and wanting and generously, genuinely present for all of it."] },
  { when: {"studentId":[6]}, weight: 4, text: ["A long, warm hum. Comfortable, certain, deeply pleased with the arrangement."] },
  { when: {"studentId":[1]}, weight: 4, text: ["She has forgotten every word she knows. Her mind, which never stops, has stopped."] },
  { when: {"studentId":[3]}, weight: 4, text: ["She's gone competitive about this too. Competing to be felt, to be present, to win.","She takes everything offered with competitive intensity, making sounds like winning feels."] },
  { when: {"studentId":[8]}, weight: 4, text: ["Her breathing. That's everything. The room becomes just that.","The quietest sound you've ever heard from a person. It contains everything."] },
  { when: {"studentId":[4]}, weight: 4, text: ["She murmurs: texture, weight, depth. Names what she feels with an artist's precision until the precision dissolves."] },
  { when: {"studentId":[5]}, weight: 4, text: ["She stops being funny. She stops being anything except here."] },
  { when: {"studentId":[7]}, weight: 4, text: ["She makes a single soft sound and then she's gone, every metric abandoned, just present.","The precision falls away in layers. By the end there is nothing left of the catalogue."] },
  { when: {"studentId":[9]}, weight: 4, text: ["She's fully present, fully open. Transferred here with nothing to prove and nothing to hide."] },
  { when: {"studentId":[10]}, weight: 4, text: ["She talks in colors and materials until the colors become irrelevant and only the material remains."] },
  { when: {"studentId":[11]}, weight: 4, text: ["Soft, measured sounds — she treats pleasure like good charting."] },
  { when: {"studentId":[12]}, weight: 4, text: ["She narrates the experience aloud until the analysis dissolves into feeling."] },
  { when: {"studentId":[13]}, weight: 4, text: ["A long, warm hum — comfort offered and received in equal measure."] },
  { when: {"studentId":[14]}, weight: 4, text: ["Breathless, generous sounds — appetite for closeness without apology."] },
  { when: {"studentId":[15]}, weight: 4, text: ["Silence. Then the faintest sound — enough to undo you."] },
  { when: {"studentId":[16]}, weight: 4, text: ["Precision falls away in layers until only warmth remains."] },
  { when: {"studentId":[17]}, weight: 4, text: ["Breathless laughter gives way to something quieter and more honest."] },
]);
registerModuleVariants('intimacy.climax', [
  { when: {"archetype":["athlete"]}, weight: 2, text: ["Afterward she lies very still, breathing hard, not quite meeting your eyes. \"Don't make a thing of it,\" she says. Which is what she says when something matters."] },
  { when: {"archetype":["influencer"]}, weight: 2, text: ["She kisses you once, precisely. \"Was I what you wanted?\" She already knows the answer but she wants to hear it."] },
  { when: {"archetype":["cheerleader"]}, weight: 2, text: ["\"That was so good,\" she says, in the same voice she'd use for a perfect routine. Pure, uncomplicated satisfaction."] },
  { when: {"archetype":["bookworm"]}, weight: 2, text: ["A long silence. Then: \"I'm going to need a minute.\" A beat. \"Or possibly several minutes.\" She's flushed to the roots of her hair."] },
  { when: {"archetype":["swimmer"]}, weight: 2, text: ["A long silence. Then: \"I'm going to need a minute.\" A beat. \"Or possibly several minutes.\" She's flushed to the roots of her hair."] },
  { when: {"archetype":["gamer"]}, weight: 2, text: ["\"Okay,\" she says eventually. \"Okay. That happened.\" A beat. \"I'm going to think about that for a very long time.\""] },
  { when: {"archetype":["sorority"]}, weight: 2, text: ["She tucks herself against you with the comfortable authority of someone who has decided where she belongs. \"Stay,\" she says. It's not a question."] },
  { when: {"archetype":["overachiever"]}, weight: 2, text: ["\"I have no notes,\" she says. \"I have literally no notes on this.\" She sounds amazed at herself."] },
  { when: {"archetype":["artsy"]}, weight: 2, text: ["\"I'm going to make something about this,\" she says. \"I don't know what yet. Something true.\""] },
  { when: {"archetype":["quiet"]}, weight: 2, text: ["She puts her head down and stays there a long time. When she finally looks up her expression is open in a way you haven't seen before."] },
  { when: {"archetype":["transfer"]}, weight: 2, text: ["\"I'm glad I'm here,\" she says. Meaning this room, this university, this moment, all at once."] },
  { when: {"studentId":[0]}, weight: 4, text: ["\"Okay I'm officially your best one,\" she says. \"This is not up for debate.\""] },
  { when: {"studentId":[2]}, weight: 4, text: ["\"I'm going to post something very vague later and everyone will wonder,\" she says, and kisses you once.","\"Good?\" she asks, and she's asking about both of you. \"Because that was very good for me.\""] },
  { when: {"studentId":[6]}, weight: 4, text: ["\"You should stay,\" she says. \"We don't have anywhere to be.\""] },
  { when: {"studentId":[1]}, weight: 4, text: ["She breathes. Counts something silently. \"I need to write this down,\" she says, but she doesn't move."] },
  { when: {"studentId":[3]}, weight: 4, text: ["\"Rematch,\" she says immediately. Then catches herself. Then laughs. \"I mean — yeah. Soon.\"","\"New personal best,\" she says, and for once she's not talking about weight."] },
  { when: {"studentId":[8]}, weight: 4, text: ["She keeps her head on your shoulder for a long time. You both understand not to speak.","She stays very still for a long time. Then she puts her hand on yours again. Just to keep it there."] },
  { when: {"studentId":[4]}, weight: 4, text: ["\"I'm going to need new materials,\" she says after a long silence. She means it as a compliment."] },
  { when: {"studentId":[5]}, weight: 4, text: ["\"Saving state,\" she says quietly. Then: \"Sorry, I — that was a thing I said.\" She's smiling."] },
  { when: {"studentId":[7]}, weight: 4, text: ["\"Revised,\" she says eventually. One word. You understand it means: everything I thought I knew about this.","\"I have no conclusions,\" she says. \"I never have no conclusions.\" She sounds like she's discovered something rare."] },
  { when: {"studentId":[9]}, weight: 4, text: ["\"Good,\" she says. Simple, complete, satisfied. \"Really good.\""] },
  { when: {"studentId":[10]}, weight: 4, text: ["\"Burnt sienna,\" she says softly. \"Everything right now is burnt sienna and heavy cream.\" She sounds pleased."] },
  { when: {"studentId":[11]}, weight: 4, text: ["\"Aggressive self-care,\" she says eventually, pleased with the data."] },
  { when: {"studentId":[12]}, weight: 4, text: ["\"Fascinating,\" she breathes. \"I have follow-up questions. Later.\""] },
  { when: {"studentId":[13]}, weight: 4, text: ["\"You stay,\" she says softly. \"We don't have anywhere better to be.\""] },
  { when: {"studentId":[14]}, weight: 4, text: ["\"Worth the wait,\" she says, satisfied. \"Every bit of it.\""] },
  { when: {"studentId":[15]}, weight: 4, text: ["\"Good,\" she says. One word. She sounds like she means you."] },
  { when: {"studentId":[16]}, weight: 4, text: ["\"No adverse effects,\" she says, flushed. \"I'd like to repeat the trial.\""] },
  { when: {"studentId":[17]}, weight: 4, text: ["\"Worth documenting,\" he says. \"Definitely worth documenting.\""] },
]);

