// Evolved stage reactions + outfit blurbs — MIGRATION.md extract.
import { CG_FILLED_REACTIONS, CG_FILLED_OUTFITS } from './competitiveGainerText.js';

export const EVOLVED_REACTIONS = {
  // ── ATHLETE paths ──────────────────────────────────────────────
  sumo:[
    "I stepped onto an official sumo scale for the first time today and it read 258 and the official wrote it down like it was nothing — and across the room Dana 'The Wall' Mercer, six years a veteran, finally looked at me. I lost. I'll be back, and I'll be heavier.",
    "Dana says good luck to me now. One season in and the Wall says good luck. The gap between her weight and mine used to be eighty pounds. It's getting small. She's noticed. So have I.",
    "I outweighed Dana Mercer on the board today for the first time. She looked at the numbers and said 'there it is.' Then I pushed her out of the ring with my belly and the crowd chanted my name. My name.",
    "National qualifier. There were cameras. I'm the heaviest competitor in the field by a wide margin, and Dana told me she can't out-weigh me anymore so she'll have to out-think me. She couldn't. I'm too big now. I love being too big.",
    "National finalist. They read my weight into the broadcast and the whole arena went quiet before it roared, and Dana was already clapping. She said she came to feel what it's like to lose to the biggest there's ever been. I gave it to her.",
    "I am the largest sumo competitor this circuit has ever certified. I put my hand on my belly after the match — warm, full, enormous, mine — and thought about the cheerleader who started this. She had no idea. There's more. There's always more.",
  ],
  eating_competitor:[
    "First contest. Timer on the table, crowd watching. I finished three minutes early. Walked out knowing.",
    "Circuit regular now. The other competitors nod when I walk in. The MCs know how to say my name.",
    "New regional record. The old one stood for four years. It stood for four minutes against me.",
    "National contender. Sponsorships. My face on a hot sauce bottle. I accept all of this.",
    "World-record territory. The table can barely hold what I put away. The crowd barely breathes.",
    "I've eaten everything. I've broken everything. Now I just eat, and that is the entire life.",
  ],
  // ── INFLUENCER paths ────────────────────────────────────────────
  feedee_creator:[
    `First collab. I said "we're going to feed each other on camera" and she said yes and we did it and the chat stayed for the whole thing. I've been trying to put a name on what this format is. I keep coming back to: mutual.`,
    `The regular viewers know what to expect now. They come for the numbers. They come to watch both of us get bigger every week. We are both getting bigger every week. The format is working.`,
    `Platform featured the collab. They said "a new format." I said: it's not new, it's just honest. Two women eating together, growing together, the camera seeing all of it. The new audience is staying.`,
    `The brand wanted both of us. They wrote a contract that said "both physical presences in frame." They meant our bellies. Our actual, enormous, warm, camera-filling bellies. I signed it. Of course I signed it.`,
    `One year of weekly collabs. She's heavier. I'm heavier. The subscriber count is 1.1 million. Wren is in the building right now, physically in the building, because she drove four hours to be here. That's what a year looks like.`,
    `Wren is in the room. She's been watching since 258 pounds. I am 820 pounds in this corner and my collab partner is enormous across the table and Wren is watching from outside the camera frame and the platform has never seen a stream like this one. I am not done. We are not done.`,
  ],
  body_positive_creator:[
    "Rebranded the channel. First body-positive post up. My old audience is confused. My new one is enormous.",
    "First brand deal. A clothing company that actually means it. The cheque cleared. I bought dinner.",
    "TEDx talk. Twelve minutes, full house. The standing ovation went on long enough to be uncomfortable. Good.",
    "My face is on a billboard. I drove past it and cried and then ate a full meal and cried more.",
    "Cultural touchstone is a phrase people use about me in articles. I eat well and feel enormous and correct.",
    "The platform is a legacy now. The body is the argument. The argument has been won.",
  ],
  // ── CHEERLEADER paths ───────────────────────────────────────────
  eating_captain:[
    `I weigh ${258} pounds and I stepped on a competition scale for the first time today and a judge read my number aloud and the whole room got quiet. That is a feeling. I want more of that feeling.`,
    `Six months in the circuit and people know my name before I get to the warmup room. I walked in today and someone said 'you're the cheerleader captain' like they'd been waiting to see me. I haven't been a cheerleader captain in a while. I'm something else now.`,
    `Conference championship. I outweighed the previous top number by over a hundred pounds and the judge read mine into the microphone and Maya from Lakewood — who has beaten me every time we've competed — started clapping. She started before anyone else.`,
    `National qualifier. There were cameras at the weigh-in. The weigh-in has cameras now. I weighed in and someone in the crowd said 'oh my god' clearly enough for me to hear it. I considered this a successful weigh-in.`,
    `National champion. They read my name and my number into the national feed and the arena made a sound I've never heard in a room before. Maya was already clapping. She knew before the horn. I knew too.`,
    `I am the largest competitive eating captain in this sport's history. The trophy is substantial. My belly is more substantial. I put my hand on it after the ceremony and thought: this is the record. I built this. There is more to build.`,
  ],
  big_squad_captain:[
    "Told the squad: no more size rules, no more weigh-ins. Two squadmates cried. One said she'd been waiting years.",
    "New pledges are choosing us specifically for the culture. Word has spread. The chapter is full.",
    "National cheerleading press wrote about us. 'The squad that changed the conversation.' Yes we did.",
    "Speaking at the national Greek leadership conference. My slides are very good. My presence is better.",
    "Coaches at other campuses have quietly stopped the weigh-ins. I'll take the quiet version too.",
    "What I built is permanent. The culture outlasts the captain. I am very large and very proud.",
  ],
  // ── BOOKWORM paths ──────────────────────────────────────────────
  eating_diarist:[
    "First newsletter issue. Thirty subscribers. Thirty is enough to start. I sent it. I ate dinner after.",
    "Six hundred subscribers. A literary agent emailed. I reread it four times before replying.",
    "Book deal. Two-book deal, actually. The second one hasn't been written yet. I'm already planning the meals.",
    "Published. The reviews say 'intimate,' 'unsettling,' 'surprisingly funny.' All correct. I ate at the launch.",
    "The book is being taught in a food studies course at a university I didn't attend. I sent them a note.",
    "I wrote the thing. It exists. The writing and the eating were always the same act. I understand that now.",
  ],
  food_researcher:[
    "Season panel approved the self-study. Officially an observation participant. The data I'm collecting is extraordinary.",
    "The institution is taking the season plan seriously. I have a prep station. I have a season plan funding request in. I have snacks.",
    "First hall log filed. Official copy. The reviewers called the methodology 'novel.' The methodology is me.",
    "Cited in three other papers. One of them is from a program I applied to and didn't get in. Interesting.",
    "Panel presentation at the athletics review. I arrived to the auditorium. The auditorium was not entirely prepared.",
    "The observer and the observation participant have fully merged. The experiment is complete. The participant remains.",
  ],
  // ── GAMER paths ─────────────────────────────────────────────────
  eating_streamer:[
    "First gaming + eating stream. Thirty-two viewers became four hundred in two hours. The chat was chaos.",
    "Regular mukbang gaming content now. The viewers who came for the games stay for the eating. Both grow.",
    "Community of dedicated viewers who follow every meal and every match. They send food suggestions. I use them.",
    "Platform featured me. The algorithm loves this exact combination. I've been doing it natively for months.",
    "Mukbang gaming legend. My clips get remixed. My food orders are documented by fans.",
    "The stream is always on. The eating never stops. I am the stream. The stream is me.",
  ],
  speed_eater:[
    "First timed challenge. Beat the record by forty seconds. The chat went silent and then exploded.",
    "Records are falling in order. I write them down. Then I break them. The list is long now.",
    "Regional eating championship, plus a speedrun of the new DLC, same weekend. Both won. Efficient.",
    "National recognition — two records in one week. The gaming community and the eating community overlap more than expected.",
    "I hold simultaneous records in gaming and competitive eating. I'm told this is unprecedented. Obviously.",
    "I've transcended both worlds. Speed means nothing when you're this size, this full, this complete.",
  ],
  ranked_feedee:[
    "Session log complete. I ate through two ranked matches, gained a rank, and finished everything Rae brought. I'm not thinking about any of this.",
    "The extras Rae keeps adding are not mistakes. I have accepted this. I have also accepted the extras. I am heavier than last week.",
    "Rae knows my schedule now. She knows my order. I'm not sure when this became a thing that was happening. It is currently a thing that is happening.",
    "Diamond. Also the desk area has been rearranged and I eat significantly more per session than I used to and Rae's delivery radius apparently includes my couch. These things are unrelated. Probably.",
    "I asked Rae how she knew what I was going to order before I ordered it. She said 'I pay attention.' This is the only answer I got. I've been thinking about it a lot. The food was excellent.",
    "Working as intended. The session runs. The food appears. Rae is here. I am very fat and very good at this game and that's the whole situation, filed under complete.",
  ],
  // ── SORORITY paths ──────────────────────────────────────────────
  chapter_hostess:[
    "First organized chapter feast. Twelve courses. Nobody left early. Nobody left not full.",
    "The feasting traditions are established now. Wednesday is feast night. Everyone knows.",
    "Other chapters are talking about our Wednesday feasts. Three people transferred in specifically for them.",
    "Greek-wide, our chapter is known for the food. Res life has noticed. They've been very quiet about it.",
    "Alumni are funding the feasts. A former sister sent a check with 'for the table' in the memo line.",
    "I am no longer chapter president. I am the feast. The feast continues without me. This is correct.",
  ],
  body_positive_greek:[
    "Proposal: end the weigh-in tradition, end the size requirements. One sister voted against. She later apologized.",
    "New pledges are choosing us because of what we stand for. The chapter is the largest we've ever had.",
    "National Greek press covered us. The article used the word 'radical' twice. We ordered pizza to celebrate.",
    "Speaking at the national Panhellenic leadership conference. My chapter is in the front row. We fill a row.",
    "The national organization quietly changed its guidance on member wellness. We were mentioned in the notes.",
    "What I started is permanent. My chapter grows. My body grows. Everything I built is real.",
  ],
  // ── OVERACHIEVER paths ──────────────────────────────────────────
  competitive_gainer: CG_FILLED_REACTIONS,
  // ── ARTSY paths ─────────────────────────────────────────────────
  installation_artist:[
    "First body-positive installation opened. One critic said 'challenging.' I consider that a win.",
    "Gallery interest from two cities. I will ship the work. I will also ship myself. The logistics are complex.",
    "Review in a major publication: 'unapologetically confrontational.' I am confronting them right now.",
    "Major exhibition, three rooms, one of them is me. Critics don't know where the art ends.",
    "Retrospective. A retrospective of someone who is still in progress. I appreciate the confidence.",
    "The body IS the final installation. The work and the artist have merged. I am the piece.",
  ],
  food_photographer:[
    "First food photography show: sold out. The prints were expensive. They bought them anyway.",
    "Gallery show opened. People stood in front of the biggest prints for a long time without speaking.",
    "A book deal: my images with my text. The publisher said the combination was 'unprecedented.' Good.",
    "Collector interest. A museum in Helsinki acquired three prints. I ate something extraordinary that night.",
    "Museum acquisition in three countries. The work is in permanent collections. So is the artist.",
    "The photographer became the subject. The subject has become the photograph. I've been hanging here for years.",
  ],
  // ── QUIET paths ─────────────────────────────────────────────────
  anonymous_blogger:[
    "First post went up at 2am. I didn't sleep. By morning, forty-three people had read it. That's forty-three.",
    "The following is growing. I don't know most of them. They don't know me. That feels exactly right.",
    "A post went viral. A journalist is trying to find me. I am very findable and also perfectly hidden.",
    "Journalists and podcasters want interviews. I do them by email only. My words, my body, my rules.",
    "I am a cultural phenomenon with no face attached. The anonymity is the whole point. Also the food.",
    "The blog and the body are the same record now. I wrote everything and gained everything. Both are real.",
  ],
  asmr_creator:[
    "First ASMR eating video. I whispered. I chewed slowly. Three hundred people watched in the first hour.",
    "Dedicated following, small and loyal. They leave very quiet comments. We understand each other.",
    "The algorithm found me. New viewers every day. They say it helps them sleep. I say I'm honored.",
    "Mainstream crossover. A content creator I watch cited me as an influence. I watched it four times.",
    "A therapist used one of my videos in a treatment session. She asked my permission first. I gave it.",
    "The sound of me eating has become something people find comfort in. I find comfort in the eating. We're even.",
  ],
  home_nest:[
    "Didn't go out today. Didn't need to. The food came. This is fine. This is better than fine, actually.",
    "I've been noting that I've developed something like a routine. Not on purpose. Things arrive. I eat them. It's comfortable. I haven't minded.",
    "Third delivery today. I usually stop at two. Ordered a third because it seemed like the right next thing. I like knowing what the right next thing is.",
    "Someone from the floor texted asking if I was okay. Said I was fine, just busy. This is accurate. I am busy. There's more to track than you'd think.",
    "The soup place messages me before I order now, to ask if I want the usual. I said yes. I like that the usual is a thing that exists. I like that they know.",
    "I've been here a long time. The room is the same. I'm different — softer, slower, more settled. The chair has accommodated me. I haven't wanted to be anywhere else.",
  ],
  delivery_hive:[
    "The room feels different tonight. Warmer. Softer. The delivery bags by the door don't feel like they belong to anyone else anymore. I keep catching myself touching my stomach without thinking. It's heavier than it was yesterday. I think the walls noticed.",
    "There are footsteps in the hallway that aren't mine. They stop at doors I didn't open. I don't have to ask them to bring things anymore. They just... do. My belly rests heavier against my thighs when I sit now. The room feels like it's breathing with me.",
    "Half the floor doesn't feel like it belongs to the hall anymore. It feels like it belongs to me. The air is thicker here. Warmer. People walk slower when they pass my door. I don't even have to speak. My body does the talking now.",
    "I don't move much anymore. I don't need to. The Hive moves for me. I can feel when a new room softens. It's like a warm pulse somewhere in the building. My body has become the center of something much larger than me. I think I like that.",
    "The whole dorm feels like it's breathing around me. I can feel the warmth in the walls. The deliveries don't even come to my door anymore. They just... arrive where they're needed. I am the heart now. Everything else is just circulation.",
    "I don't know where I end and the Hive begins anymore. My body is the warm center of everything. Rooms don't resist. People don't leave. They settle. They soften. They stay. I am no longer just Maya. I am the place they come home to.",
  ],
  // ── TRANSFER paths ──────────────────────────────────────────────
  campus_legend:[
    "The dining hall staff knows my order before I arrive. A booth has been 'mine' for three months.",
    "Stories are spreading. A freshman I've never met referenced 'the legend of the dining hall.' That's me.",
    "The booth now has my name on it. Unofficially. Then officially. The dining director did it herself.",
    "Future residents hear about me before they arrive. A campus tour guide mentioned me by name. She was kind.",
    "I am campus mythology. Incoming residents are told about me during orientation. I have heard this directly.",
    "I have become the campus. The campus has grown around me. We are one thing now.",
  ],
  salon_appetit:[
    "Première soirée — trois invités, fromage, vin. I said *j'ai faim* and meant it as philosophy.",
    "RA Mori followed the smell to my door. She stayed for dessert. I consider that a review.",
    "They whisper *Chloé's dinners* in the group chats. I pour more wine and let them.",
    "The campus writer watched me eat and called it performance. I called it Thursday.",
    "Rooftop, candlelight, protesters below. I raised my glass. The room ate with me.",
    "La Grande Soirée — twelve settings, black silk, *encore* until the sun. I am the salon.",
  ],
  artisan_gallery:[
    "First resident enrolled. First contact sheet pinned. The camera doesn't lie — only frames truth generously.",
    "Field roll on the quad: abundance everywhere, if you know how to look.",
    "Opening night — eight prints, critics, cheese. I ate in the corner on purpose.",
    "The Living Room: her timeline on the wall, her body live, heavier than the latest frame.",
    "Regional gallery wants the series. AIB calls it evidence. I call it archive.",
    "Permanent collection. Legacy program. I still shoot, still feed, still pin.",
  ],
  food_tourist:[
    "Systematic expedition through every cuisine available within thirty miles. Documenting everything.",
    "The blog has readers from three countries. Two of them recognize dishes from their home regions in my posts.",
    "A publication from my home country ran a feature. My family read it. My grandmother approved of the portions.",
    "Two book deals — one from here, one from home. Both publishers want the same story. I can give them both.",
    "Cultural ambassador is the phrase they use. I prefer 'someone who ate everything and wrote it all down.'",
    "I have tasted everything. I have grown into everything. The journey and the destination are the same.",
  ],
  // ── FARM GIRL paths ──────────────────────────────────────────────
  homestead_queen:[
    "The spread is set. Cast iron on every surface. I made sweet potato pie from scratch at 2am and I do not regret a single bite.",
    "Grandma Mae video-called and saw the setup. She said 'baby, you've got a real kitchen.' Coming from her that's everything.",
    "The recipe box arrived. Six generations of food in one box. I made every dish in four days. I kept notes on all of it.",
    "Mae calls every Sunday now. I always eat while we talk. She knows. She doesn't say anything about it except 'good girl.'",
    "She said I'm going to run out of room. She's right. I take up most of my homestead already. I am the homestead now.",
    "Mae drove up. She walked in and saw me — really saw me — and she started crying and then she started cooking. That's love.",
  ],
  state_fair_queen:[
    "First county fair, first pie table. Darcy from Meadowview looked at me like I was lost. She won. I went home and ate.",
    "Second year. Darcy said 'you again.' I was 60 pounds heavier. She barely won. She noticed.",
    "State qualifier. I crossed Darcy on the scoreboard for the first time. She stopped mid-bite. I kept going.",
    "State finals. Won. Darcy clapped. Full hand-claps, not polite ones — the kind that means she means it. That meant everything.",
    "Tri-state invitational. They built a bigger scale. I am the draw now. People come to see the numbers, not the pies.",
    "Grand invitational. I barely fit the tent. Darcy's in the open bracket. The contest is incidental. I am the fair.",
  ],
  // ── BOOKWORM alt path ────────────────────────────────────────────
  ff_author:[
    "I've been writing. The character is fictional. She happens to be a cheerleader and she happens to gain weight in chapter three. I have genuinely no idea where I got the idea.",
    "Posting anonymously. Fifteen thousand readers now. The chapter where the bookworm character gets stuck in her study carrel has a four-star average on the reaction tracker. I wrote her very carefully.",
    "Someone on the floor quoted a line from the group chat in passing. They didn't look at me. I ate an entire dinner thinking about whether they knew.",
    "Three hundred thousand words posted. Some of it is more honest about what I want than anything I've said out loud. The fandom writes their own versions. I read them late at night.",
    "The most popular character is based on myself. She gets everything she wants. The readership responds very well to this. So do I.",
    "The fiction and the body are the same project. I've known this for a while. The writing is just the form the knowing takes.",
  ],
  // ── FARM GIRL: wife_lessons ─────────────────────────────────────
  wife_lessons:[
    "Darlene kept calling it 'bake night.' I've stopped correcting her. Wanda knew what it was from the start. She sat down and ate and nodded and said 'I was wondering when someone was going to start this.' I love her.",
    "Patrice brought store-bought cookies like she was coming to a potluck. I didn't say anything. By the end she was asking for the full recipe. Taylor's hips are already starting — Patrice said her jeans 'fit different.' I know what that means.",
    "Cheryl came to watch. That's what she told herself. She ate four pieces of cinnamon bread and asked for the recipe on the way out. Madison gained seven pounds last month. Cheryl mentioned it like a personal record. It is.",
    "All six of them now. The room smells like butter for three hours before anyone arrives and for hours after they leave. Ruthanne said she doesn't fit through the same doorways she did last year. Becca said Sofia asked for the strong shake. Good.",
    "Lily figured out what's been in her food. She asked Ruthanne to teach her how to make it herself. Ruthanne came in glowing. That's the goal — when the daughter isn't just growing, she's growing on purpose. Kezia fills the whole sectional now.",
    "Wanda showed me a photo of Kezia. She changed bedrooms because her old one was getting narrow for her hips. She has a reinforced bed. She barely goes out anymore. Wanda is so proud she can barely look at the photo without crying. I understand completely.",
  ],
  // ── PSYCH paths ──────────────────────────────────────────────────
  psych_researcher:[
    "Session data: resident ate considerably beyond their baseline. I ate more than mine as well. I logged both. My notebook is running out of pages.",
    "The resident's response to the feeding dynamic has shifted — more anticipation, less resistance. I'm heavier too. I've started logging the sessions in a separate volume.",
    "I tried to stay clinical today and couldn't quite manage it. The resident was present in a way that I found difficult to categorize. My own data is getting interesting.",
    "I'm eating with the resident now, not just observing and facilitating. I stopped noting it as a deviation and started noting it as a variable. The weight is accumulating. Both of us.",
    "My desk chair requires leverage to exit. I logged that. I also logged how I feel about the session data, which is something I never did in week one of this hall log.",
    "Final session notes: I am very large, the resident is very large, the data is extraordinary, and I stopped pretending it's neutral sometime around stage three. The hall log is complete. The methodology got personal. Both are fine.",
  ],
  // ── ECED path ──────────────────────────────────────────────────
  homeroom_queen:[
    "Tuesday went well. Kayla had seconds. I didn't set out to do anything intentional today — I just noticed what they liked and made more of it. I'm noting that distinction.",
    "I made a richer batch this week. I told myself it was a recipe test. They ate everything. Mrs. Calloway's daughter asked to take some home. I said yes. I'm noting that I said yes quickly.",
    "Mrs. Monroe came inside for the first time. She sat at the table. She had four pieces and talked the whole time and laughed at everything. I didn't want her to leave. I'm noting that I made extra specifically because she was coming.",
    "I realized this week that I plan the Tuesday recipes around who's coming and what they respond to. Bri likes the heavier things. Kayla likes the sweet things. Mrs. Monroe likes everything. I'm noting that this is not random anymore.",
    "Mrs. Calloway brought me something in return. I sat with this for a while. The reciprocity feels significant. I'm noting that I feel warmly toward all six of them now and that I'm going to keep making Tuesdays happen for as long as I can.",
    "End of term. All six of them in the room. Everything I made was gone in an hour. I watched them eat and I felt — I'm not sure I have the language for it. Useful. Purposeful. Like I was exactly where I was supposed to be. I'm noting this.",
  ],
  // ── CULINARY path ──────────────────────────────────────────────
  cultivator:[
    "First session with the taste tester. She ate everything without asking what was in it. I made notes on her appetite, her pace, her stopping point. She has no stopping point. This is going to be methodical.",
    "The taste tester is visibly larger. I didn't note surprise in my log because I'm not surprised. The process is working. I ate the quality-control portions carefully. I gained three pounds this week. I'm logging that.",
    "She fills the chair differently now. I adjusted the portions upward accordingly. Richer base on the milkshake. Ganache on the cake. She asked what changed. I said 'recipe refinement.' She accepted this and finished everything.",
    "The taste tester is at a size that requires some recalibration — the chair, the portions, the approach. I've recalibrated. My own appetite is increasing. I've started keeping a second log for personal data. It seems relevant.",
    "I ate the leftovers after the session today. There were a lot of leftovers. I stayed in the kitchen for a long time. I'm noting that I find this work deeply satisfying in a way that extends well past professional interest.",
    "Last session before harvest. She sits across from me very large, very full, and entirely unaware of how this concludes. I ate alongside her — quality control, always quality control — and I felt full and satisfied and exactly right. My own numbers are considerably higher than when I started. I've stopped being surprised by this.",
  ],
  // ── BOOKWORM path ───────────────────────────────────────────────
  machine_goddess:[
    "First device deployed on a willing floor volunteer. The readouts matched prediction within eight percent. I logged the variance anyway. I also logged how my pulse changed when the belt cycled on.",
    "The workshop smells like solder and vanilla paste now. Three prototypes running concurrently. I keep calibrating my own intake as 'material cost.' The scale agrees with the metaphor more than it should.",
    "A malfunction last week should have been alarming. Instead I stayed up rerunning the failure curve until 3am. The volunteer's belly was enormous afterward. So was mine, from stress-eating beside the bench.",
    "I stopped describing the devices as experiments. They're infrastructure. My body is infrastructure too — raw polymer, heat-formed, repurposed into better machines.",
    "Campus whispers about the engineering resident with the harnesses. I don't correct them. Correction is inefficient. Installation is the point.",
    "Devices tick on bodies I equipped myself. My own mass feeds the builds that feed everyone else. The workshop hums whether I'm in it or not. I find that correct.",
  ],
  community_researcher:[
    "First floor session. I went in as lane captain. I ate what was offered because refusing felt like skewing the intake log. I'm noting my own meals separately from the training log.",
    "The case study is developing. I'm present at more sessions than the season plan technically requires. The residents haven't noticed I'm eating alongside them. I've noticed.",
    "I stopped pretending the log is what I'm there for. I'm still writing, but the writing is increasingly personal. The distinction between captain on the sidelines and captain at the table is getting thin.",
    "I've had to add a second protocol section. The first covers the residents. The second covers me. Both sections have been growing at a similar rate.",
    "The hall log is going to be honest. It was going to be clinical and dispassionate. It's going to be all of that and also honest. I'm a variable. I'm writing myself in.",
    "I'm the largest person in every room I enter for case-study purposes. I've been in a lot of rooms. The intake record on floor immersion is extensive. The final season report will be original.",
  ],
};


export const EVOLVED_OUTFITS = {
  sumo:[
    "Training gear — compression shorts, a thick practice mawashi worn over sweats. Built for the ring, nothing else.",
    "Practice uniform fits like it was made for her body because it was. Her coach measured everything twice.",
    "Competition mawashi, ceremonial and precise. The weight of the garment is nothing compared to the weight she carries.",
    "Championship regalia. Her manager handles the presentation garments now. She receives them without comment.",
    "Ceremonial attire between bouts — a wide kimono-style wrap, open, relaxed. She fills it completely.",
    "She wears what's comfortable. Everything is wide, everything is soft, everything accommodates what she's become.",
  ],
  eating_competitor:[
    "Contest shirt — her sponsor's logo, custom-ordered, already tight at the collar. She wears it with pride.",
    "Circuit gear. Tracksuit in her competition colors, sponsor patches on both sleeves. She's recognizable now.",
    "Competition day: her lucky shirt, three sizes larger than last year's lucky shirt. The luck transferred.",
    "Sponsored athlete gear head to toe. The brand sent custom pieces without being asked. They know what fits.",
    "She travels in her competition colors. Hotels recognize her. The food arrives before she finishes checking in.",
    "Whatever she can find that accommodates her. Competition gear is custom now. She doesn't mind.",
  ],
  feedee_creator:[
    "Content-ready always — camera-friendly outfit, good lighting angles considered, food accessible on the table.",
    "Soft-era aesthetic fully embraced. Flowy pieces in warm colors, everything shot-ready, nothing restrictive.",
    "Her brand has a look: comfortable, abundant, unapologetic. The clothing is part of the content.",
    "Custom pieces from brands that sponsor her. Wide cuts, premium fabric. She wears them on camera first.",
    "Everything wide, everything deliberate, everything designed to be seen doing exactly what it's doing.",
    "The outfit doesn't matter as much as what she's eating. But she looks incredible. Both things are true.",
  ],
  body_positive_creator:[
    "Brand-deal clothing — the good kind, the kind made for her actual body. She wears it on camera first.",
    "Press-ready always. A wardrobe coordinator helps now. The clothes are extraordinary.",
    "She dresses for the platform and for herself simultaneously. The overlap is large. So is she.",
    "Everything she wears becomes merch demand within a week. The stylist has learned to expect this.",
    "Billboard clothing. Iconic pieces. A wardrobe that says exactly what she wants to say.",
    "She wears what exists at this scale. It has been made for her. It fits. She has arrived.",
  ],
  eating_captain:[
    "Squad training gear in team colors, eating bib on top. The combination is both absurd and completely correct.",
    "Team competition uniform, custom-ordered in her specifications. She had input on the design. It shows.",
    "Full captain regalia at events. The title is on the back of her jacket in block letters.",
    "Championship gear. The athletic director commissioned a custom set after the national invite.",
    "Her jacket has more patches than room for patches now. She had an extension panel added.",
    "She wears the captain's sash everywhere. Nothing else fits the way it used to. The sash always fits.",
  ],
  big_squad_captain:[
    "Squad jacket modified by her own hand — the old size requirements cut out, new ethos written in marker on the lining.",
    "The uniform that fits the body, not a body built to fit the uniform. She commissioned it herself.",
    "Chapter captain gear in their colors. Wide, dignified, present. She made the design.",
    "Her conference presentation outfit. A wide-fit suit she wore on the national stage. Donated to the chapter archives.",
    "Custom everything now, all of it chosen deliberately. She knows what she's saying with what she wears.",
    "She dresses like the monument she's become. The chapter follows her lead. The closet is legendary.",
  ],
  eating_diarist:[
    "Cardigan open over a good dress. Writing outfit. She eats while she writes and the outfits accommodate this.",
    "She dresses for the reading series now — events, talks, bookstore signings. Wide linen, good earrings.",
    "Book launch outfit: a wide-cut statement piece she chose six months before the book came out.",
    "Speaking engagement attire. She has a rotation now. Everything wide, everything deliberate, everything documented.",
    "She dresses the way she writes — with intention, with detail, with nothing apologized for.",
    "Whatever fits this body. She has a tailor. The tailor is excellent. The clothes are extraordinary.",
  ],
  food_researcher:[
    "Hall cardigan, custom-ordered. The standard one didn't cover the data. She made a note in the protocol.",
    "Hall casual with a purpose — she needs pockets, always. The blazer accommodates everything.",
    "Presentation attire for panel reviews. Wide-cut, professional, memorable. The slides are also memorable.",
    "Panel outfit. Her institution had a photographer there. The photos are impressive.",
    "Observation gear that accommodates field work, desk work, and being the field. Practical and extraordinary.",
    "She dresses like someone whose hall log has outlasted the original hypothesis. With confidence.",
  ],
  eating_streamer:[
    "Stream outfit — comfortable, camera-ready, no restriction. The snacks are in frame. She is in frame.",
    "Gaming hoodie, eating bib, both sponsors represented. The aesthetic is cohesive by now.",
    "Her branded gear from the platform deal. She wore it live. The chat went immediately to 'new merch?'",
    "She dresses for the camera and for six to eight hours of sitting. Wide, soft, documented.",
    "Merch she designed herself. The sizing runs large because she asked for that specifically.",
    "She wears what fits. Everything is wide. The setup is custom. She is the best part of the setup.",
  ],
  speed_eater:[
    "Competition shirt, timer-ready, sponsor logo centered. She pins the bib herself before every contest.",
    "Her lucky competition tracksuit. It has been let out twice. The luck has not diminished.",
    "Full competition gear, both sponsors represented, her record count in small text on the sleeve.",
    "Championship kit. Her coach had it made when the national record fell. She wore it the next day.",
    "She travels in her competition colors. Everything is custom. The logos are earned.",
    "She wears what accommodates her. Everything does, because everything is made for her now.",
  ],
  ranked_feedee:[
    "Gaming hoodie and worn-in joggers. Slightly short in the hem now. The setup is what matters, not the outfit.",
    "Oversized gaming tee from a sponsorship she forgot applying to. Fits for now. For now.",
    "Wide soft hoodie and stretched-out joggers. She stopped checking if things match. The food matches. That's enough.",
    "Custom wide-cut gaming hoodie that appeared in the delivery pile one day. Fits perfectly. Destiny hasn't asked how.",
    "Soft wide everything. She stopped buying clothes. Things appear and they fit. She's stopped asking questions about this.",
    "She wears what's comfortable, which is now a very specific kind of enormous and soft. The chair was built around her. The clothes followed.",
  ],
  chapter_hostess:[
    "Hosting apron over her chapter formal. The apron has seen more feasts than most dining rooms.",
    "Full chapter formal for Wednesday feasts. She instituted a dress code. She set the example.",
    "Event attire that says 'I am in charge of this table and this table is magnificent.'",
    "Her signature wide-cut blazer and the chapter's formal colors. She has hosted in this outfit at the national level.",
    "She commissions one new hosting outfit per semester. The tradition is documented in chapter records.",
    "She dresses like the feast she's hosting — abundant, deliberate, impossible to ignore.",
  ],
  body_positive_greek:[
    "Chapter colors in a wide-cut blazer she had commissioned when the old one stopped working.",
    "Conference attire. She wore this on a national stage. The outfit has its own legacy.",
    "Full formal in chapter colors, every detail chosen deliberately, nothing apologized for.",
    "Her speaking outfit. She could be recognized by it at this point. That's not an accident.",
    "She dresses for the culture she's building. Intentional. Inclusive. Exactly as large as she is.",
    "Everything is custom. Everything fits. Everything says exactly what she wants it to say.",
  ],
  competitive_gainer: CG_FILLED_OUTFITS,
  installation_artist:[
    "Something she made herself — fabric, found materials, a garment that documents the body wearing it.",
    "Gallery opening attire that is itself a piece. Visitors aren't always sure where the show starts.",
    "Her major exhibition outfit. It was photographed by three publications. It's in the catalogue.",
    "She dresses for the work and the work dresses her. The boundary is genuinely unclear.",
    "Retrospective attire: something that holds the whole arc of the work. She designed it herself.",
    "She wears her body the way she makes installations: with intention, with presence, as the piece itself.",
  ],
  food_photographer:[
    "Gallery opening attire — something that photographs well, because someone will always photograph her.",
    "The outfit she wore when the Helsinki museum acquired the prints. She remembers it exactly.",
    "Book launch clothes — a wide statement piece that appeared in press photos. Recognizable.",
    "She dresses for both sides of the lens now. The subject understands the photographer.",
    "Her studio look: wide linen, room to move, good in the shots her assistant takes behind the scenes.",
    "Everything is custom, everything is deliberate, everything accommodates the body that makes the work.",
  ],
  anonymous_blogger:[
    "Anonymous-compatible — nothing identifiable, nothing logo'd, nothing that would give her away.",
    "She dresses for invisibility and comfort simultaneously. Both are achieved.",
    "Cozy, unremarkable from the outside. The inside is the work. The outside protects it.",
    "She has a consistent aesthetic that nobody has been able to place online. She maintains it carefully.",
    "Wide, soft, present in rooms, invisible in photographs. The balance is intentional.",
    "She dresses for the life she's living, which is enormous and private and exactly as she planned.",
  ],
  asmr_creator:[
    "Soft textures only — the microphone picks up fabric noise, so everything she wears is deliberate.",
    "ASMR-compatible clothing. She's thought about this more than most people think about anything.",
    "Recording day attire: soft fabrics, nothing synthetic, nothing that will interrupt the session.",
    "She dresses for sound now as much as sight. The clothes are very quiet. So is she.",
    "Wide, soft, silent fabric. She moves slowly and everything moves slowly with her.",
    "She wears the textures that are kindest to the microphone. Also the ones kindest to her skin.",
  ],
  home_nest:[
    "Soft oversized tee and wide comfortable shorts. She's home. This is what home looks like.",
    "A very large soft hoodie and wide comfortable pants — both ordered online when the previous comfortable things stopped being comfortable.",
    "Soft wide everything. She's been in this outfit for two days. It's still the right outfit.",
    "Her warmest, widest set. She's stopped owning clothes that are for going out. They all look like this.",
    "The hoodie is enormous and warm and the pants don't require any decisions. This is the right system.",
    "She wears what's soft and accommodating and doesn't require thought. That's all. It fits perfectly.",
  ],
  delivery_hive:[
    "Lavender lounge clothes, soft enough to vanish into the blankets while the first delivery bags gather around the desk.",
    "A wide hoodie in pear-lavender tones, stretched comfortably over her lower-heavy body as the room grows warmer and more organized.",
    "Layered blankets and custom lounge pieces arranged around the mass of her hips and thighs, less outfit than Central Nest uniform.",
    "Soft draped fabric, wide enough to accommodate her stationary shape, threaded with little delivery pins and warm violet light.",
    "An enormous lavender wrap and reinforced cushions; the clothes no longer suggest she will be leaving, only receiving.",
    "What she wears is part blanket, part throne, part room. The Hive dresses around Maya now.",
  ],
  campus_legend:[
    "Her dining hall regular outfit — the clothes she's worn so often here that they're part of the myth.",
    "Comfortable campus gear in her colors. Residents recognize the outfit before they recognize the face.",
    "She dresses like someone who belongs here completely, because she does.",
    "Wide everything. Soft everything. Exactly as present as she is.",
    "The outfit that appears in the campus tour guide's description. She didn't plan this.",
    "She wears what fits. Everything fits because everything was eventually made to fit.",
  ],
  food_tourist:[
    "Travel-ready always — practical, wide-cut, pockets for the notebook and the camera.",
    "Her blog aesthetic: dressed for wherever the food is, which is everywhere.",
    "The outfit she wore in the home-country magazine feature. Both publishers asked to use it.",
    "She dresses for the food, not the other way around. The food is everywhere. So is she.",
    "Cultural bridge attire — something that belongs in two places. She found it. It fits.",
    "Wide, practical, present. Made for someone who is both places at once.",
  ],
  ff_author:[
    "Cardigan open, something soft underneath, laptop always nearby. She's found the writing uniform and she doesn't deviate from it. She eats while she writes. The snacks appear and disappear without her noticing.",
    "An enormous pullover, hair up, the desk organized around two monitors. One for the document, one for the comment section. She checks both with equal seriousness.",
    "Wide linen trousers and a loose top with pockets — the outfit of someone who has committed fully to desk life. She has a look now. It accommodates everything.",
    "Custom-ordered wide pieces in soft, dark colors. The desk chair has been upgraded twice. Everything in her space has been chosen to accommodate her completely.",
    "She dresses for the body she has and the life she's built around it. Everything wide, everything deliberate, everything soft. She looks like what she writes about, which is to say: exactly what she wants.",
    "She wears what fits. Everything fits because everything is made for her now. The room is made for her. The desk is made for her. She writes surrounded by things that understand what she is.",
  ],
  // ── FARM GIRL paths ──────────────────────────────────────────────
  homestead_queen:[
    "Denim overalls over a flannel shirt that she's had since high school. The overalls are cinched at the sides but her belly rounds out the front bib completely. She's warm and smells like cinnamon and brown sugar.",
    "The flannel has been traded for a loose linen top — easier to move in, and the overalls have been retired in favor of wide-leg jeans with an elastic waist she doesn't bother to explain. Her chest fills the top completely.",
    "A wide cotton housedress — she found a seamstress to make it to her measurements — and a full apron tied at the back that does most of the practical work. She looks entirely at home because she is.",
    "She's given up pretending the apron is for protection — it's load-bearing now, the ties cinched around the widest part of her, her belly testing the front pocket. The dress underneath is the widest she owns.",
    "A single enormous piece of wide-cut fabric that functions as both dress and apron. She made it herself. The pattern is from Mae's notebook. She fills it entirely and with great comfort.",
    "The apron is the outfit. It is, structurally, enormous — she had it sewn to fit her — and under it there is a wide cotton shift and nothing else. She is warm and present and the room smells like everything she's made.",
  ],
  state_fair_queen:[
    "Competition tank and stretch shorts — the standard circuit uniform, sized up significantly. Her chest strains the front. She has her entry number pinned to the side because there's no room on the front.",
    "A competition jersey with her name on the back, her region on the front. It was made for someone smaller and she has not replaced it. The fabric pulls across her chest and rides up over her belly at the bottom.",
    "Custom-fitted competition jersey, her name printed large enough to read from the stands. It was made to her measurements two months ago and is already getting tight across the front.",
    "Sponsor logos across the jersey — four of them, which is a measure of how serious this is now. The jersey is wide enough to hold all four and still stretch across the full geography of her chest.",
    "The jersey has become a document. Every patch and print and logo has had to be repositioned as she's grown. The current version was made last month. The seams are already tested.",
    "A competition banner-jersey sewn to her exact measurements by a custom sportswear maker who has done this exactly once before. It fits perfectly. She fills it perfectly. It reads less like a uniform than a flag.",
  ],
  // ── FARM GIRL: wife_lessons ─────────────────────────────────────
  wife_lessons:[
    "Wide gingham apron over a full blouse and a long skirt. She looks like a woman who has owned a kitchen for decades and is correct about it.",
    "The blouse has been replaced with a loose linen top that gives more room across the chest and belly. The apron is still tied properly in the back. She looks warm and purposeful.",
    "A wide cotton dress with the apron over it, the ties cinched behind. Her belly fills the front of the apron completely. There is flour on the bib.",
    "Homemade wide-cut dress with the apron tied in front now — it won't reach around back anymore. She moves through the kitchen with the ease of someone who knows exactly where her body is.",
    "A very wide cotton housedress. The apron is symbolic at this point. She wears it anyway. She'll always wear the apron.",
    "The housedress is enormous and entirely comfortable. The apron still goes on every time, no matter what. Her belly rounds the front of it smooth and warm. The kitchen is organized around her presence.",
  ],
  // ── PSYCH paths ──────────────────────────────────────────────────
  psych_researcher:[
    "Hall cardigan over a blouse. Pristine. Notebook prominent. A 'Hall Log Active' lanyard.",
    "Hall cardigan, wider cut. Stretch professional blouse underneath. Still the lanyard.",
    "Custom hall cardigan, noticeably larger. The blouse underneath strains slightly. Notebooks doubled.",
    "Wide professional hall cardigan. She's given up on fitted anything underneath.",
    "Hall cardigan barely buttons. She wears it open. The blouse beneath is custom-ordered.",
    "Hall cardigan enormous and custom-made. She wears it like a robe. It suits her.",
  ],
  // ── ECED path ──────────────────────────────────────────────────
  homeroom_queen:[
    "A wide cotton apron over a soft button-up and practical trousers. She smells like cinnamon and brown sugar from the morning's test batch.",
    "A loose linen top over stretch trousers, her large apron cinched across the middle. The apron has flour on it before she even arrives.",
    "A wide jersey dress with a practical apron over it. She has a second apron in her bag. She's learned to have a backup.",
    "A soft wide-cut housedress and a full apron tied at the back. She moves through the kitchen like she owns it, which at this point she functionally does.",
    "A roomy printed housedress with deep pockets, her heavy-duty apron layered over the front. The pockets hold the notebook. The apron holds the flour.",
    "An enormous soft tunic over wide-leg trousers, her apron purely ceremonial at this stage. The kitchen has been arranged around her. She fills it warmly.",
  ],
  // ── CULINARY path ──────────────────────────────────────────────
  cultivator:[
    "Chef's coat, well-fitted, a utility apron tied over. Clean knife roll at her hip. She looks entirely professional.",
    "Chef's coat, slightly wider cut. The apron still fits. She's added a second front pocket for the session notebook.",
    "A stretch-panel chef's coat. She had it custom-tailored and doesn't mention this. The apron is a generous cut.",
    "A wide-format chef's jacket, minimal fuss, purely functional. The coat is very large and moves well. She bakes in it.",
    "A custom chef's coat at considerable scale, apron tied at the front with effort. She moves through the kitchen with full authority.",
    "An enormous chef's coat, apron decorative at this point. The kitchen was rearranged around her reach and she approves of the arrangement.",
  ],
  machine_goddess:[
    "Hall cardigan over a hoodie, cargo pants, fingerless gloves. Solder burns on the cuffs. She smells like flux.",
    "Reinforced work coveralls, pockets full of hex keys and calipers. The coat buttons strain when she leans over the bench.",
    "Custom harness-friendly layers — wide belt loops, stretch panels at the waist. Built for wearing her own prototypes.",
    "Industrial coveralls with tool rigging across the chest. Paste stains on the collar. She doesn't notice anymore.",
    "Oversized tech-wear in matte black, LED status pins along the sleeves. Her body fills it like another machine casing.",
    "The workshop clothes are half armor, half uniform — wide, soft, engineered around a body that feeds the builds. She belongs to the lab now.",
  ],
  // ── SWIMMER path: lane captain ─────────────────────────────────
  community_researcher:[
    "Team jacket over a fitted tank, practice shorts, training log always in hand. The unofficial uniform of lane captain. Nothing about her appearance is an accident.",
    "The jackets are looser now — chosen with room in mind. The shorts have been replaced with joggers that accommodate more. She still carries the log.",
    "Zip hoodie over a sports bra she no longer tucks in. Her figure is noticeably fuller under the layers. She's stopped arranging herself for the team photos.",
    "Oversized meet-day hoodie, leggings that hold everything together, slides on her feet. The training log is in a bigger bag now, next to a protein shaker.",
    "Warm-up pullover, stretch joggers, comfortable slides. She carries herself with the ease of someone who has found the outfit that works and has several of it.",
    "She moves slowly, deliberately, the way captains who have lived the season plan eventually move. A wide hoodie open over a soft tee, everything forgiving and full. The log is still there. It always will be.",
  ],
};

