// Feeder-focus subject journals (psych_researcher path) — MIGRATION.md extract.
// Legacy monolith retired (step 6 pilot): bridge stubs; modular slots own week 20+ voice.
export const FEEDER_SUBJECT_JOURNALS = {
  cheerleader:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the peppy, half-embarrassed part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. letting the RA stuff me like this. I notice fullness after our sessions; the peppy, half-embarrassed part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the peppy, half-embarrassed part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  swimmer:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the analytical athlete part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the analytical athlete part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the analytical athlete part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  bookworm:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. hall meal season. I notice fullness after our sessions; the psych-track, clinical part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the psych-track, clinical part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the psych-track, clinical part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. Every time the RA feeds me. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. ultimate hall appetite case study. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  influencer:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the performative, camera-aware part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the performative, camera-aware part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the performative, camera-aware part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  athlete:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the disciplined, competitive part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the disciplined, competitive part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the disciplined, competitive part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  artsy:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the sensory, dramatic part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the sensory, dramatic part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the sensory, dramatic part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  eced:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the warm, maternal part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the warm, maternal part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the warm, maternal part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  overachiever:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the grade-obsessed part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the grade-obsessed part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the grade-obsessed part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  sorority:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the social, ritual part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the social, ritual part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the social, ritual part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  transfer:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the new-hall cautious part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the new-hall cautious part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the new-hall cautious part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  quiet:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. floor program sounded harmless. I notice fullness after our sessions; the sparse, honest part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the sparse, honest part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. Straight-bodied frames like mine adapt quickly. I notice fullness after our sessions; the sparse, honest part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  gamer:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the ironic, late-night part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the ironic, late-night part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the ironic, late-night part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  psych:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the method-notes part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the method-notes part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the method-notes part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  nursing:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the caretaker turned feedee part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the caretaker turned feedee part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the caretaker turned feedee part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  farm_girl:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the plainspoken, hearty part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the plainspoken, hearty part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the plainspoken, hearty part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
  culinary:[
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the kitchen-proud part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the kitchen-proud part of me calls it data, the rest calls it nice.`,
    `My RA pitched the hall meal season — floor favor plus helping a resident sounded structured, not scary. I notice fullness after our sessions; the kitchen-proud part of me calls it data, the rest calls it nice.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Uniforms and waistbands disagree now. My RA praises compliance while the kitchen heat makes honesty easy; I keep showing up hungry on purpose.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
    `Late log — body takes more couch than hallway. My RA treats every new pound like policy fulfilled; I treat every feeding like the point.`,
  ],
};
