import { getStage } from './stages.js';

export const ACTIONS_SINGLE = [
  { id:"restaurant",  label:"🍷 Take to Dinner",             cost:2, gain:[4,9],   desc:"A proper dinner out at the best restaurant near campus.", requiresUnlock:"dinner_action" },
];

export const ACTIONS_HALL = [
  { id:"pizza",        label:"🍕 Floor Pizza Night",         cost:3, cal:[12000,24000], full:40, desc:"An excessive whole-floor pizza order. Everyone indulges." },
  { id:"potluck",      label:"🥘 Floor Potluck",             cost:2, cal:[9000,18000],  full:30, desc:"Everyone brings a dish. Everyone is expected to try everything." },
  { id:"feast",        label:"🦃 Holiday Floor Feast",       cost:5, cal:[28000,52000], full:70, desc:"A full holiday spread. This one really goes far." },
  { id:"group_dinner", label:"👥 Arrange Group Dinner",      cost:3, cal:[14000,30000], full:45, desc:"Take two residents to dinner together. Their bond amplifies the result for both.", requiresUnlock:"group_dinner" },
  { id:"refeast_ritual", label:"👻 Refeast Ritual", cost:4, cal:[8000,16000], full:50, supernaturalOnly:true, desc:"Supernatural Act only — clears hunger curses, bites scarcity pressure, refeeds ascended residents." },
];

/** @deprecated use ACTIONS_HALL */
export const ACTIONS_CLASS = ACTIONS_HALL;

export const FLOOR_SCENES = [
  // ── MOOD-BASED ───────────────────────────────────────────────
  { id:"mood_stressed", target:"student", filter:s=>s.mood==="stressed",
    title:"Burning Out",
    text:s=>`${s.name} folds into the lounge couch like the week sat down with her. An energy drink sweats on the table. Her notebook stays closed on a belly she keeps a hand on.`,
    choices:[
      { label:"Slide her a snack",    effect:{gain:[3,6],mood:"content",rel:5},  result:s=>`You set cookies on her knee. She blinks, then eats them slow, color coming back as the sugar lands.` },
      { label:"Let her vent",          effect:{gain:[0,0],mood:"focused",rel:8},  result:s=>`She offloads deadlines and dorm noise. By the end her shoulders drop. "Thanks, RA."` },
      { label:"Give her busywork",     effect:{gain:[1,3],mood:"focused",rel:2},  result:s=>`A small lounge task she can finish. She locks in. Better than the staring.` },
    ] },
  { id:"mood_tired", target:"student", filter:s=>s.mood==="tired",
    title:"Running on Empty",
    text:s=>`${s.name} is already half-asleep by the second topic. Her chin keeps dropping toward the soft shelf of her chest. Present only in the technical sense.`,
    choices:[
      { label:"Bring coffee and pastries", effect:{gain:[4,8],mood:"content",rel:6}, result:s=>`Thermos, pastry box. ${s.name} revives and eats two before you finish the sentence.` },
      { label:"Call on her gently",        effect:{gain:[0,0],mood:"focused",rel:4}, result:s=>`You say her name soft. She snaps awake, answers well, and stays with you.` },
      { label:"Let her rest in the back",  effect:{gain:[0,0],mood:"tired",  rel:1}, result:s=>`You wave her to the back couch and dim the lights. She naps. Grateful, heavy, still here.` },
    ] },
  { id:"mood_nervous", target:"student", filter:s=>s.mood==="nervous",
    title:"Jittery Energy",
    text:s=>`${s.name} sits near the front, fidgeting. Phone up, phone down. Something has her wound tight enough that her shirt keeps tugging.`,
    choices:[
      { label:"Offer warm comfort food",  effect:{gain:[5,9],mood:"content",rel:7}, result:s=>`Warm tin of baked goods. "For when you need it." She eats the whole thing and unclenches.` },
      { label:"Give her a speaking role", effect:{gain:[0,0],mood:"focused",rel:5}, result:s=>`A structured, easy contribution. She gets through it. The success bleeds the shake out of her hands.` },
      { label:"Check in privately",       effect:{gain:[2,4],mood:"content",rel:9}, result:s=>`You hold her back. She talks. You listen. You leave a snack in her palm for the walk home.` },
    ] },
  { id:"mood_focused", target:"student", filter:s=>s.mood==="focused",
    title:"Deep in the Zone",
    text:s=>`${s.name} has barely looked up. Notes immaculate. A pastry already torn open at the edge of the page like it belongs there.`,
    choices:[
      { label:"Reward her focus with treats", effect:{gain:[3,6],mood:"focused",rel:5}, result:s=>`Chocolate on the side table. She nods, keeps working, and the wrapper is empty by close.` },
      { label:"Offer an extension project",   effect:{gain:[0,0],mood:"focused",rel:3}, result:s=>`Optional extra work. She accepts immediately and starts planning. Exactly what she wanted.` },
      { label:"Leave her to it",              effect:{gain:[0,0],mood:"focused",rel:1}, result:s=>`You do not disturb her. She powers through. The chair keeps her.` },
    ] },
  { id:"mood_excited", target:"student", filter:s=>s.mood==="excited",
    title:"Bubbling Over",
    text:s=>`${s.name} can barely stay in her seat. She has answered three questions you have not asked. The bounce of her makes the chair creak fondly.`,
    choices:[
      { label:"Channel it into a group activity", effect:{gain:[2,5],mood:"excited",rel:4}, result:s=>`You redirect her into a group talk. She facilitates. The snacks you brought vanish in the process.` },
      { label:"Let her lead the segment",         effect:{gain:[0,0],mood:"excited",rel:7}, result:s=>`You let her explain. She thrives. Everyone watches the way she takes the room.` },
      { label:"Feed the energy",      effect:{gain:[5,10],mood:"excited",rel:6}, result:s=>`A celebratory spread. ${s.name} eats through the whole check-in like applause she can swallow.` },
    ] },
  { id:"mood_content", target:"student", filter:s=>s.mood==="content",
    title:"Comfortable and Settled",
    text:s=>`${s.name} is ease today. Deep in the chair, soft smile, barely moving. She looks like she has already arrived.`,
    choices:[
      { label:"Bring something warm to eat",    effect:{gain:[4,7],mood:"content",rel:5}, result:s=>`Warm pastry in front of her. She accepts without breaking the peace and eats it slow.` },
      { label:"Give her a comfortable solo task",effect:{gain:[0,0],mood:"content",rel:3}, result:s=>`Quiet reading, just for her. She is still there twenty minutes after check-in ends.` },
      { label:"Sit and chat",                   effect:{gain:[1,3],mood:"content",rel:8}, result:s=>`You sit on the desk edge and talk. Unhurried. She keeps a hand on her middle the whole time.` },
    ] },
  // ── ARCHETYPE-SPECIFIC ───────────────────────────────────────
  { id:"arch_cheerleader", target:"student", filter:s=>s.archetype==="cheerleader",
    title:"Squad Pressure",
    text:s=>`${s.name} arrives late and flustered. Squad drama. Uniforms, tryouts, politics. She drops onto the couch and the cushions keep the shape of her.`,
    choices:[
      { label:"Take her for comfort food",  effect:{gain:[6,12],mood:"content",rel:8}, result:s=>`Campus diner. She vents over the largest slice of cake on the menu. By the third bite she is already laughing.` },
      { label:"Help her draft a message",   effect:{gain:[0,0], mood:"focused",rel:6}, result:s=>`You help her think it through. She writes it between bites. "Thanks for not just saying it'll be fine."` },
      { label:"Compliment her publicly",    effect:{gain:[2,4], mood:"happy",  rel:7}, result:s=>`You mention something she is good at, in front of everyone. She lights up. The drama shrinks.` },
    ] },
  { id:"arch_swimmer", target:"student", filter:s=>s.archetype==="swimmer",
    title:"Training Spiral",
    text:s=>`${s.name} found a split discrepancy Thursday and has not stopped logging. Sharp, slightly hollow, and she has not mentioned food once even though her suit tells on her.`,
    choices:[
      { label:"Bring food to the team lounge",  effect:{gain:[5,9], mood:"focused",rel:8}, result:s=>`You set down a full meal. She nods, eats without pausing the log. You sit opposite and say nothing.` },
      { label:"Offer floor credit",         effect:{gain:[0,0], mood:"focused",rel:7}, result:s=>`Hall leadership hours. She looks up for the first time in hours. "...Really?" Delight, then back to the splits.` },
      { label:"Lure her out with carb bowls",    effect:{gain:[7,13],mood:"content",rel:9}, result:s=>`Snack-and-strategy, still athletic. Two hours later the food is gone and she looks fueled.` },
    ] },
  { id:"arch_bookworm", target:"student", filter:s=>s.archetype==="bookworm",
    title:"Reading Spiral",
    text:s=>`${s.name} has a hardcover open on the shelf of her belly, highlighter dying in her fist. Chip crumbs in the margin. She looks up, glasses sliding, and calls it studying like the word still covers a bag that is almost gone.`,
    choices:[
      { label:"Quiz her with snacks",  effect:{gain:[5,9], mood:"focused",rel:8}, result:s=>`You quiz. She answers around chips. Right answers, empty bag. She calls it a method with her mouth still full.` },
      { label:"Offer floor credit",         effect:{gain:[0,0], mood:"focused",rel:7}, result:s=>`Hall leadership hours. She looks up for the first time in hours. "...Really?" Delight, then back to the page.` },
      { label:"Lure her out with snacks",    effect:{gain:[7,13],mood:"content",rel:9}, result:s=>`Snack-and-discuss, still intellectual. Two hours later the food is gone and she looks nourished.` },
    ] },
  { id:"arch_influencer", target:"student", filter:s=>s.archetype==="influencer",
    title:"Sponsored Content",
    text:s=>`${s.name} is filming a haul between slides, whispering reviews of your snacks. Followers are invested. So is the camera angle on the new round of her.`,
    choices:[
      { label:"Bring premium snacks for the shoot", effect:{gain:[6,11],mood:"excited",rel:7}, result:s=>`Artisan chocolate, imported cheese. She films delighted. The bite is real after the take. She keeps eating when the light clicks off.` },
      { label:"Ask to see the content",              effect:{gain:[0,0], mood:"excited",rel:9}, result:s=>`She shows you the channel. You tell her it is good. "Nobody ever actually asks." Her smile is bigger than the caption.` },
      { label:"Collaborate on a floor food feature", effect:{gain:[8,14],mood:"excited",rel:8}, result:s=>`She documents a floor food event. A sponsor spread appears the next day. The floor eats very well, and so does she, on camera and off.` },
    ] },
  { id:"arch_athlete", target:"student", filter:s=>s.archetype==="athlete",
    title:"Recovery Week",
    text:s=>`${s.name} says training is lighter. Coach called it recovery. She is restless, energy with nowhere to go except her appetite, a hand already on the new softness at her waist.`,
    choices:[
      { label:"Suggest she use recovery to fuel up", effect:{gain:[7,14],mood:"content",rel:6}, result:s=>`Fuel logic. She treats the plate like a protocol. By evening she has put away an impressive amount and looks pleased with the data.` },
      { label:"Give her an energetic group task",     effect:{gain:[1,3], mood:"focused",rel:5}, result:s=>`You pair her with others who need moving, presenting, debating. She is immediately in her element, still finishing a bar between sentences.` },
      { label:"Talk training and nutrition",          effect:{gain:[2,5], mood:"focused",rel:7}, result:s=>`Athletic nutrition, honest. You learn things about carb-loading that give you ideas. She asks for seconds of the example.` },
    ] },
  { id:"arch_artsy", target:"student", filter:s=>s.archetype==="artsy",
    title:"Creative Block",
    text:s=>`${s.name} stares at a blank page. Thirty minutes. Charcoal in hand. The block sits in her lap like a second body she keeps warming with a palm.`,
    choices:[
      { label:"Arrange a still-life spread",    effect:{gain:[4,9], mood:"content",rel:8}, result:s=>`Fruit, pastries, color. "Draw that." She eats half while drawing. Both improve. The page fills as her belly does.` },
      { label:"Take her on a campus walk",       effect:{gain:[0,0], mood:"dreamy", rel:6}, result:s=>`A quiet loop. She says little. By return she is sketching furiously, a pastry still in the other hand.` },
      { label:"Share a creative struggle",       effect:{gain:[2,4], mood:"dreamy", rel:9}, result:s=>`You tell her about a time you were stuck. She listens with her whole body. Something in her relaxes into the chair.` },
    ] },
  { id:"arch_gamer", target:"student", filter:s=>s.archetype==="gamer",
    title:"Patch Day",
    text:s=>`${s.name} walked in wearing yesterday. Body pillow by the chair, headphones on. New patch. The chair already knows her shape and complains when she turns.`,
    choices:[
      { label:"Bring her delivery order",  effect:{gain:[6,12],mood:"content",rel:7}, result:s=>`Her usual bag, extra sides. She stares, then takes the headphones down. "...How'd you know?" She eats through the loading screen.` },
      { label:"Ask about the patch",        effect:{gain:[0,0], mood:"excited",rel:8}, result:s=>`A genuine question. Twenty minutes of build theory. She leaves the hall energized, still reaching for the last fry.` },
      { label:"Let her game in the back",   effect:{gain:[2,4], mood:"tired",  rel:3}, result:s=>`You move her back, offer notes later. One thumbs-up. She games through the check-in with a bag in her lap.` },
    ] },
  { id:"arch_sorority", target:"student", filter:s=>s.archetype==="sorority",
    title:"Event Planning Crisis",
    text:s=>`${s.name} is in planner mode. Spreadsheet open, phone muted, the look of someone managing something large that will not cooperate. A tasting sample already open at her elbow.`,
    choices:[
      { label:"Offer the hall lounge as venue", effect:{gain:[5,10],mood:"excited",rel:8}, result:s=>`After hours lounge. She vibrates. Catering is spectacular. You are invited, and she plates you last so she can keep eating.` },
      { label:"Help with logistics",           effect:{gain:[0,0], mood:"focused",rel:7}, result:s=>`Ten minutes on the vendor knot. "I didn't think you'd know about this stuff." She finishes the sample while you talk.` },
      { label:"Suggest a potluck component",   effect:{gain:[8,15],mood:"happy",  rel:6}, result:s=>`Potluck. She plans tables, themes, recipes. The floor eats extremely well. So does she, quality-checking every dish.` },
    ] },
  { id:"arch_overachiever", target:"student", filter:s=>s.archetype==="overachiever",
    title:"Impossible Standards",
    text:s=>`${s.name} hands in forty pages for a five-page ask. Three circled "weaknesses." She wants extra credit on top of this, and a snack while you read it.`,
    choices:[
      { label:"Tell her to rest and eat",      effect:{gain:[5,9], mood:"content",rel:6}, result:s=>`The paper is excellent. Rest. Eat. You produce lunch. Silence turns grateful. She finishes everything you plated.` },
      { label:"Give her a real challenge",      effect:{gain:[0,0], mood:"focused",rel:7}, result:s=>`A problem without a clean answer. She dives. The most at peace she has looked all week, still reaching for the side dish.` },
      { label:"Praise her work publicly",       effect:{gain:[2,4], mood:"focused",rel:8}, result:s=>`You read a passage without naming her, then reveal the author. Red. Mortified. Delighted. She hides her smile in another bite.` },
    ] },
  { id:"arch_quiet", target:"student", filter:s=>s.archetype==="quiet",
    title:"Invisible by Choice",
    text:s=>`${s.name} has been in the back corner so long you are not sure when she arrived. Small drawings. Close attention she does not advertise. A pastry already halved on the page.`,
    choices:[
      { label:"Leave her something anonymously", effect:{gain:[3,7], mood:"content",rel:9},  result:s=>`A pastry on her spot. No eye contact. She eats it very slowly. You do not make it a thing. The wrapper is gone when you look back.` },
      { label:"Ask to see her notebook",          effect:{gain:[0,0], mood:"content",rel:10}, result:s=>`She hesitates, then holds it out. The drawings are extraordinary. You say so. Her shoulders drop. She offers you the other half of the pastry.` },
      { label:"Include her in a small group",     effect:{gain:[1,3], mood:"nervous",rel:4},  result:s=>`A small group. She participates, minimally. She does not leave. She thanks you after, still holding the snack.` },
    ] },
  { id:"arch_transfer", target:"student", filter:s=>s.archetype==="transfer",
    title:"Still Adjusting",
    text:s=>`${s.name} is trying everything with the intensity of someone who has not figured out what she likes. Three campus spots, cross-referenced, still hungry, a map already greasy at the folds.`,
    choices:[
      { label:"Bring something she hasn't tried", effect:{gain:[5,9], mood:"happy",  rel:8},  result:s=>`Something unusual, from somewhere she has not found. "This is incredible. Where is this FROM?" She asks for the rest of it.` },
      { label:"Give her a campus food map",        effect:{gain:[4,8], mood:"excited",rel:7},  result:s=>`Your private map, including the places that require knowing where to look. She stares like treasure and starts planning a route that is mostly meals.` },
      { label:"Ask where she's from",              effect:{gain:[0,0], mood:"content",rel:10}, result:s=>`Home. Food, places, people. Twenty minutes. She is surprised how much she missed it. She eats while she talks.` },
    ] },
  // ── WEIGHT-STAGE-BASED ───────────────────────────────────────
  { id:"stage_early", target:"student", filter:s=>getStage(s.lbs).id<=2,
    title:"Still Watching",
    text:s=>`${s.name} pauses to smooth her shirt, frowning at a pull that was not there last week. She mentions gym more. Her hand stays on the new softness anyway.`,
    choices:[
      { label:"Reassure her and bring snacks",    effect:{gain:[4,8],mood:"content",rel:5}, result:s=>`You tell her she looks good. You set out snacks as you say it. She takes some. The gym talk does not come back.` },
      { label:"Redirect to her season plan",        effect:{gain:[0,0],mood:"focused",rel:3}, result:s=>`You pivot to hall goals. The self-scrutiny fades into something she cares about more.` },
      { label:"Introduce 'study fuel' snacks",     effect:{gain:[5,10],mood:"content",rel:4}, result:s=>`Brain food, framed athletic. She tries them all. She does not go to the gym that afternoon.` },
    ] },
  { id:"stage_mid", target:"student", filter:s=>{const id=getStage(s.lbs).id;return id>=3&&id<=4;},
    title:"Finding Her Rhythm",
    text:s=>`${s.name} has made peace with a lot of things. She moves slower, eats more openly, cares less who watches. Ease looks good on her.`,
    choices:[
      { label:"Celebrate her ease with a spread", effect:{gain:[6,12],mood:"content",rel:6}, result:s=>`A table spread, nothing fancy, just abundant. She helps herself without apology.` },
      { label:"Have a candid check-in",            effect:{gain:[0,0],mood:"content",rel:9}, result:s=>`You ask how she has been. She thinks, then says "Good, actually." And means it.` },
      { label:"Assign a comfortable project",      effect:{gain:[2,5],mood:"content",rel:4}, result:s=>`Work at her own pace. She settles into it with the ease of someone who knows her body now.` },
    ] },
  { id:"stage_heavy", target:"student", filter:s=>getStage(s.lbs).id>=5,
    title:"Command of the Room",
    text:s=>`${s.name} takes up space with absolute ease. She settles into the reinforced seat, arranges her things, and looks around like the room was built to hold her.`,
    choices:[
      { label:"Arrange something special for her", effect:{gain:[5,10],mood:"content",rel:8},  result:s=>`Her preferences, her portion, her timing. She notices. "You remembered." Warmth, genuine.` },
      { label:"Ask her to mentor someone",          effect:{gain:[0,0],mood:"content",rel:7},  result:s=>`You ask her to work with someone struggling. She agrees and does it well, patience, zero fanfare.` },
      { label:"Acknowledge her growth",             effect:{gain:[3,7],mood:"content",rel:10}, result:s=>`You say you have noticed how much she has grown. On the floor. Personally. "That actually means something, RA."` },
    ] },
  // ── HALL-WIDE ────────────────────────────────────────────────
  { id:"hall_snack_break", target:"hall",
    title:"Impromptu Snack Break",
    text:"You call a break mid-check-in and produce a box of snacks. No reason given. The floor needs none. Chairs scrape closer.",
    choices:[
      { label:"Basic spread — quick and filling",      effect:{gain:[3,6]},  result:"The floor descends. Gone in four minutes. Check-in resumes with better energy and tighter waistbands." },
      { label:"Premium spread — variety and excess",   effect:{gain:[5,10]}, result:"Pastries, chocolates, something local. They take their time. The check-in ends fifteen minutes late and nobody minds." },
      { label:"Tasting exercise — they rate each one", effect:{gain:[4,8]},  result:"You frame it as sensory evaluation. They review each item with comic rigor. Everybody eats a lot." },
    ] },
  { id:"hall_group_project", target:"hall",
    title:"Group Project Day",
    text:"You announce today's hall plans are cancelled for a meal-plan challenge. Hypothetical menus. The floor gets very into it. Someone has already opened a container.",
    choices:[
      { label:"Let them be creative",             effect:{gain:[2,5]},  result:"The projects are elaborate and taste-tested using supplies they brought for this exact possibility." },
      { label:"Bring tasting supplies",           effect:{gain:[4,9]},  result:"You bring extensive tasting samples. Everyone treats it like a cook-off. They are still comparing plates after closing." },
      { label:"Award points for best proposal",   effect:{gain:[3,7]},  result:"Competition. Three residents present full spreads. Everyone eats everything, including the scoring." },
    ] },
  { id:"hall_birthday", target:"hall",
    title:"Mystery Birthday",
    text:"Someone on the floor has a birthday this week. Word has spread. There is an expectation of cake, and of seconds.",
    choices:[
      { label:"Bring one cake",                    effect:{gain:[3,6]},  result:"A solid cake. The birthday resident gets the first slice. Everyone gets seconds. The box does not survive." },
      { label:"Bring a full dessert spread",        effect:{gain:[6,12]}, result:"Three cakes, cupcakes, tarts. The floor is overwhelmed and grateful and eats everything." },
      { label:"Declare it a week-long celebration", effect:{gain:[4,9]},  result:"Birthday week. Snacks every day. The birthday resident is embarrassed and delighted in equal measure." },
    ] },
  { id:"hall_slump", target:"hall",
    title:"3PM Energy Crash",
    text:"The 3PM slump is real. Heads droop. Someone is asleep. Someone else is asleep more aggressively. Soft bodies, low light, action required.",
    choices:[
      { label:"Snacks and caffeine",    effect:{gain:[4,8]}, result:"Coffee, tea, a mountain of snacks. The floor revives. Several residents look grateful enough to tear up." },
      { label:"Quick movement break",   effect:{gain:[1,3]}, result:"A stretch. Energy returns. You notice several were much more comfortable staying seated." },
      { label:"Dim lights and chill",   effect:{gain:[2,5]}, result:"Lights down, ambient music, snacks in peaceful semi-darkness. The lounge becomes a nest." },
    ] },
  { id:"hall_potluck", target:"hall",
    title:"Floor Potluck",
    text:"You announced a potluck. You underestimated them. The room is lined with containers. The smell is a dare.",
    choices:[
      { label:"Try everything and praise all",       effect:{gain:[6,12]}, result:"You try each dish. Second and third helpings happen under the banner of thorough comparison." },
      { label:"Formalize it with a scoring rubric",  effect:{gain:[4,9]},  result:"You produce a rubric. The floor cares deeply. The stakes make everyone eat more to evaluate." },
      { label:"Abandon pretense",       effect:{gain:[5,11]}, result:"Music on. The floor eats freely for ninety minutes. Best check-in of the semester." },
    ] },
  { id:"hall_extended", target:"hall",
    title:"Extended Session",
    text:"Today runs long. Real engagement. Two hours and nobody has left. Stomachs have started filing complaints in the quiet.",
    choices:[
      { label:"Order delivery for the room",         effect:{gain:[5,10]}, result:"Three different orders. The floor nominates favorites. The food arrives and disappears without stopping the talk." },
      { label:"Break with a spread you brought",     effect:{gain:[3,7]},  result:"A prepared spread from your bag. Someone says this is the best night. You feel it is true." },
      { label:"Push through without food",           effect:{gain:[0,2]},  result:"Nobody gets fed. Grudging respect. Several stomachs register the objection out loud." },
    ] },
];
