// Intimacy scene metadata — choices, flags, effects (prose in textEngine/scenes/intimacy/).
// Generated by scripts/generateIntimacy.mjs
export const INTIMACY_SCENES = [
  {
    "id": "her_weight",
    "label": "Her Weight on You",
    "icon": "🌊",
    "desc": "She lowers herself onto you — sitting, leaning, settling. Her mass becomes a physical fact in your lap and against your chest. The weight is the point.",
    "apCost": 1,
    "minTier": 2,
    "phases": [
      {
        "textKey": "intimacy.her_weight.p0",
        "choices": [
          {
            "id": "wrap_arms",
            "label": "Wrap your arms around her",
            "lbs": 1,
            "rel": 3,
            "flag": "held_her",
            "resultKey": "intimacy.her_weight.ch.wrap_arms"
          },
          {
            "id": "press_belly",
            "label": "Press your hands flat against her belly",
            "lbs": 2,
            "rel": 2,
            "flag": "touched_belly",
            "resultKey": "intimacy.her_weight.ch.press_belly"
          },
          {
            "id": "stay_still",
            "label": "Just hold the weight — don't move",
            "rel": 4,
            "resultKey": "intimacy.her_weight.ch.stay_still"
          }
        ]
      },
      {
        "textKey": "intimacy.her_weight.p1",
        "choices": [
          {
            "id": "rock_gently",
            "label": "Rock her gently — feel the mass shift",
            "lbs": 2,
            "rel": 3,
            "resultKey": "intimacy.her_weight.ch.rock_gently"
          },
          {
            "id": "pull_closer",
            "label": "Pull her tighter against your chest",
            "rel": 4,
            "requires": "held_her",
            "resultKey": "intimacy.her_weight.ch.pull_closer"
          },
          {
            "id": "spread_hands",
            "label": "Spread your hands wide across her belly",
            "lbs": 3,
            "rel": 3,
            "flag": "measured_her",
            "resultKey": "intimacy.her_weight.ch.spread_hands"
          },
          {
            "id": "kiss_neck",
            "label": "Press your lips to her neck",
            "rel": 5,
            "resultKey": "intimacy.her_weight.ch.kiss_neck"
          }
        ]
      },
      {
        "textKey": "intimacy.her_weight.p2",
        "choices": [
          {
            "id": "say_something",
            "label": "Tell her what this is like",
            "rel": 6,
            "flag": "spoke_truth",
            "resultKey": "intimacy.her_weight.ch.say_something"
          },
          {
            "id": "stay_silent",
            "label": "Stay quiet — let the weight speak",
            "rel": 4,
            "resultKey": "intimacy.her_weight.ch.stay_silent"
          },
          {
            "id": "reach_lower",
            "label": "Let your hands drift lower",
            "lbs": 2,
            "rel": 5,
            "requiresNot": "kissed_off",
            "resultKey": "intimacy.her_weight.ch.reach_lower"
          }
        ]
      }
    ],
    "endings": [
      {
        "conditionSrc": "(h)=>h.includes(\"spoke_truth\")&&h.includes(\"measured_her\")",
        "gainBonus": 3,
        "relBonus": 5,
        "textKey": "intimacy.her_weight.end0"
      },
      {
        "conditionSrc": "(h)=>h.includes(\"held_her\")",
        "gainBonus": 2,
        "relBonus": 4,
        "textKey": "intimacy.her_weight.end1"
      },
      {
        "conditionSrc": "()=>true",
        "gainBonus": 1,
        "relBonus": 3,
        "textKey": "intimacy.her_weight.end2"
      }
    ]
  },
  {
    "id": "wall_press",
    "label": "Against the Wall",
    "icon": "🧱",
    "desc": "You press her back against the wall, or she pins you there. The mass of her becomes architectural — a warm, soft structure with its own specific gravity.",
    "apCost": 1,
    "minTier": 2,
    "phases": [
      {
        "textKey": "intimacy.wall_press.p0",
        "choices": [
          {
            "id": "press_in",
            "label": "Press slowly into her softness",
            "lbs": 1,
            "rel": 3,
            "flag": "pressed_in",
            "resultKey": "intimacy.wall_press.ch.press_in"
          },
          {
            "id": "hands_hips",
            "label": "Put your hands on her hips",
            "rel": 3,
            "flag": "held_hips",
            "resultKey": "intimacy.wall_press.ch.hands_hips"
          },
          {
            "id": "let_her_lead",
            "label": "Let her set the pressure",
            "lbs": 2,
            "rel": 4,
            "flag": "she_led",
            "resultKey": "intimacy.wall_press.ch.let_her_lead"
          }
        ]
      },
      {
        "textKey": "intimacy.wall_press.p1",
        "choices": [
          {
            "id": "drag_hands",
            "label": "Run your hands up her sides",
            "lbs": 2,
            "rel": 4,
            "resultKey": "intimacy.wall_press.ch.drag_hands"
          },
          {
            "id": "lift_belly",
            "label": "Cradle the weight of her belly from below",
            "lbs": 3,
            "rel": 3,
            "flag": "held_belly",
            "resultKey": "intimacy.wall_press.ch.lift_belly"
          },
          {
            "id": "press_forehead",
            "label": "Press your forehead to hers",
            "rel": 5,
            "resultKey": "intimacy.wall_press.ch.press_forehead"
          },
          {
            "id": "grind_slow",
            "label": "Press in slow, deliberate circles",
            "lbs": 1,
            "rel": 5,
            "requiresNot": "she_led",
            "resultKey": "intimacy.wall_press.ch.grind_slow"
          }
        ]
      },
      {
        "textKey": "intimacy.wall_press.p2",
        "choices": [
          {
            "id": "whisper_close",
            "label": "Say what you want",
            "rel": 6,
            "flag": "spoke_desire",
            "resultKey": "intimacy.wall_press.ch.whisper_close"
          },
          {
            "id": "stay_pressed",
            "label": "Just stay here, pressed together",
            "rel": 5,
            "resultKey": "intimacy.wall_press.ch.stay_pressed"
          },
          {
            "id": "kiss_jaw",
            "label": "Find her jaw with your lips",
            "lbs": 1,
            "rel": 4,
            "resultKey": "intimacy.wall_press.ch.kiss_jaw"
          }
        ]
      }
    ],
    "endings": [
      {
        "conditionSrc": "(h)=>h.includes(\"spoke_desire\")&&h.includes(\"held_belly\")",
        "gainBonus": 3,
        "relBonus": 5,
        "textKey": "intimacy.wall_press.end0"
      },
      {
        "conditionSrc": "(h)=>h.includes(\"pressed_in\")",
        "gainBonus": 2,
        "relBonus": 4,
        "textKey": "intimacy.wall_press.end1"
      },
      {
        "conditionSrc": "()=>true",
        "gainBonus": 1,
        "relBonus": 3,
        "textKey": "intimacy.wall_press.end2"
      }
    ]
  },
  {
    "id": "belly_focus",
    "label": "Hands on Her Belly",
    "icon": "🤲",
    "desc": "Patient, deliberate attention to her belly — the weight and warmth of it, the softness and depth, the physical reality of all she's grown.",
    "apCost": 1,
    "minTier": 2,
    "phases": [
      {
        "textKey": "intimacy.belly_focus.p0",
        "choices": [
          {
            "id": "press_deep",
            "label": "Press slowly, feeling the full depth",
            "lbs": 3,
            "rel": 3,
            "flag": "pressed_deep",
            "resultKey": "intimacy.belly_focus.ch.press_deep"
          },
          {
            "id": "circle_slow",
            "label": "Move in slow circles",
            "lbs": 2,
            "rel": 4,
            "flag": "circled",
            "resultKey": "intimacy.belly_focus.ch.circle_slow"
          },
          {
            "id": "lift_gently",
            "label": "Try to lift and hold the weight of it",
            "lbs": 2,
            "rel": 4,
            "flag": "lifted",
            "resultKey": "intimacy.belly_focus.ch.lift_gently"
          }
        ]
      },
      {
        "textKey": "intimacy.belly_focus.p1",
        "choices": [
          {
            "id": "knead_sides",
            "label": "Work your hands into the soft sides",
            "lbs": 3,
            "rel": 4,
            "flag": "kneaded_sides",
            "resultKey": "intimacy.belly_focus.ch.knead_sides"
          },
          {
            "id": "press_navel",
            "label": "Focus on the center — the deep softness there",
            "lbs": 4,
            "rel": 3,
            "requires": "pressed_deep",
            "resultKey": "intimacy.belly_focus.ch.press_navel"
          },
          {
            "id": "rest_head",
            "label": "Rest your head against her belly",
            "rel": 6,
            "flag": "rested_close",
            "resultKey": "intimacy.belly_focus.ch.rest_head"
          },
          {
            "id": "whisper_size",
            "label": "Tell her how large she feels",
            "lbs": 2,
            "rel": 5,
            "flag": "named_her",
            "resultKey": "intimacy.belly_focus.ch.whisper_size"
          }
        ]
      },
      {
        "textKey": "intimacy.belly_focus.p2",
        "choices": [
          {
            "id": "say_want_more",
            "label": "Tell her you want her to keep growing",
            "lbs": 5,
            "rel": 7,
            "flag": "asked_more",
            "resultKey": "intimacy.belly_focus.ch.say_want_more"
          },
          {
            "id": "kiss_belly",
            "label": "Press your lips against her belly",
            "lbs": 2,
            "rel": 6,
            "flag": "kissed_belly",
            "resultKey": "intimacy.belly_focus.ch.kiss_belly"
          },
          {
            "id": "keep_hands_moving",
            "label": "Keep your hands moving — silent, deliberate",
            "lbs": 3,
            "rel": 5,
            "resultKey": "intimacy.belly_focus.ch.keep_hands_moving"
          }
        ]
      }
    ],
    "endings": [
      {
        "conditionSrc": "(h)=>h.includes(\"asked_more\")&&h.includes(\"kissed_belly\")",
        "gainBonus": 5,
        "relBonus": 7,
        "textKey": "intimacy.belly_focus.end0"
      },
      {
        "conditionSrc": "(h)=>h.includes(\"rested_close\")||(h.includes(\"kneaded_sides\"))",
        "gainBonus": 3,
        "relBonus": 5,
        "textKey": "intimacy.belly_focus.end1"
      },
      {
        "conditionSrc": "()=>true",
        "gainBonus": 2,
        "relBonus": 3,
        "textKey": "intimacy.belly_focus.end2"
      }
    ]
  },
  {
    "id": "chest_buried",
    "label": "Face in Her Chest",
    "icon": "💫",
    "desc": "You press your face into her chest — the warmth and softness there, the depth of her cleavage, the heavy weight of her breasts settling around you.",
    "apCost": 1,
    "minTier": 2,
    "phases": [
      {
        "textKey": "intimacy.chest_buried.p0",
        "choices": [
          {
            "id": "turn_face",
            "label": "Turn your face and press deeper into the cleavage",
            "lbs": 2,
            "rel": 4,
            "flag": "went_deep",
            "resultKey": "intimacy.chest_buried.ch.turn_face"
          },
          {
            "id": "hands_chest",
            "label": "Bring your hands up to hold the weight of her chest",
            "lbs": 3,
            "rel": 3,
            "flag": "held_chest",
            "resultKey": "intimacy.chest_buried.ch.hands_chest"
          },
          {
            "id": "breathe_slow",
            "label": "Just breathe — slow, against her skin",
            "rel": 5,
            "flag": "breathed_close",
            "resultKey": "intimacy.chest_buried.ch.breathe_slow"
          }
        ]
      },
      {
        "textKey": "intimacy.chest_buried.p1",
        "choices": [
          {
            "id": "find_heartbeat",
            "label": "Press your lips to where her heartbeat is",
            "rel": 6,
            "flag": "found_heart",
            "resultKey": "intimacy.chest_buried.ch.find_heartbeat"
          },
          {
            "id": "squeeze_gently",
            "label": "Squeeze gently from both sides",
            "lbs": 3,
            "rel": 4,
            "requires": "held_chest",
            "resultKey": "intimacy.chest_buried.ch.squeeze_gently"
          },
          {
            "id": "look_up",
            "label": "Look up at her from where you are",
            "rel": 5,
            "resultKey": "intimacy.chest_buried.ch.look_up"
          },
          {
            "id": "say_something_muffled",
            "label": "Say something against her skin",
            "rel": 5,
            "flag": "made_her_laugh",
            "resultKey": "intimacy.chest_buried.ch.say_something_muffled"
          }
        ]
      },
      {
        "textKey": "intimacy.chest_buried.p2",
        "choices": [
          {
            "id": "stay_forever",
            "label": "Make it clear you'd stay here indefinitely",
            "lbs": 1,
            "rel": 7,
            "flag": "chose_to_stay",
            "resultKey": "intimacy.chest_buried.ch.stay_forever"
          },
          {
            "id": "tell_her_gorgeous",
            "label": "Tell her what you think of her body",
            "lbs": 2,
            "rel": 6,
            "flag": "told_her",
            "resultKey": "intimacy.chest_buried.ch.tell_her_gorgeous"
          },
          {
            "id": "let_weight_press",
            "label": "Let her weight press down and stay with it",
            "lbs": 3,
            "rel": 5,
            "resultKey": "intimacy.chest_buried.ch.let_weight_press"
          }
        ]
      }
    ],
    "endings": [
      {
        "conditionSrc": "(h)=>h.includes(\"chose_to_stay\")&&h.includes(\"found_heart\")",
        "gainBonus": 3,
        "relBonus": 6,
        "textKey": "intimacy.chest_buried.end0"
      },
      {
        "conditionSrc": "(h)=>h.includes(\"told_her\")",
        "gainBonus": 2,
        "relBonus": 5,
        "textKey": "intimacy.chest_buried.end1"
      },
      {
        "conditionSrc": "()=>true",
        "gainBonus": 1,
        "relBonus": 4,
        "textKey": "intimacy.chest_buried.end2"
      }
    ]
  },
  {
    "id": "thighs_lap",
    "label": "Between Her Thighs",
    "icon": "🌡",
    "desc": "You sit between her thighs, or she settles them around you — the weight and warmth of them enclosing you, enormous and present.",
    "apCost": 1,
    "minTier": 2,
    "phases": [
      {
        "textKey": "intimacy.thighs_lap.p0",
        "choices": [
          {
            "id": "press_thighs_in",
            "label": "Press into her thighs — feel the depth of them",
            "lbs": 2,
            "rel": 4,
            "flag": "pressed_thighs",
            "resultKey": "intimacy.thighs_lap.ch.press_thighs_in"
          },
          {
            "id": "hands_on_thighs",
            "label": "Put your hands flat on her thighs",
            "lbs": 1,
            "rel": 3,
            "flag": "touched_thighs",
            "resultKey": "intimacy.thighs_lap.ch.hands_on_thighs"
          },
          {
            "id": "settle_in",
            "label": "Settle your weight back against her",
            "rel": 5,
            "flag": "settled_in",
            "resultKey": "intimacy.thighs_lap.ch.settle_in"
          }
        ]
      },
      {
        "textKey": "intimacy.thighs_lap.p1",
        "choices": [
          {
            "id": "measure_thigh",
            "label": "Try to wrap your hand around her thigh",
            "lbs": 3,
            "rel": 4,
            "flag": "measured_thigh",
            "resultKey": "intimacy.thighs_lap.ch.measure_thigh"
          },
          {
            "id": "squeeze_back",
            "label": "Press your knees into her inner thighs",
            "lbs": 2,
            "rel": 5,
            "requires": "pressed_thighs",
            "resultKey": "intimacy.thighs_lap.ch.squeeze_back"
          },
          {
            "id": "lean_back_into_her",
            "label": "Lean back fully, let the belly behind you hold you",
            "rel": 6,
            "flag": "full_embrace",
            "resultKey": "intimacy.thighs_lap.ch.lean_back_into_her"
          },
          {
            "id": "trace_inner_thigh",
            "label": "Trace the inner thigh — slowly",
            "lbs": 2,
            "rel": 5,
            "resultKey": "intimacy.thighs_lap.ch.trace_inner_thigh"
          }
        ]
      },
      {
        "textKey": "intimacy.thighs_lap.p2",
        "choices": [
          {
            "id": "tell_her_thighs",
            "label": "Tell her specifically what her thighs do to you",
            "lbs": 3,
            "rel": 7,
            "flag": "named_thighs",
            "resultKey": "intimacy.thighs_lap.ch.tell_her_thighs"
          },
          {
            "id": "stay_held",
            "label": "Just stay — held between them",
            "rel": 5,
            "resultKey": "intimacy.thighs_lap.ch.stay_held"
          },
          {
            "id": "push_deeper",
            "label": "Work your way deeper into her lap",
            "lbs": 2,
            "rel": 5,
            "resultKey": "intimacy.thighs_lap.ch.push_deeper"
          }
        ]
      }
    ],
    "endings": [
      {
        "conditionSrc": "(h)=>h.includes(\"named_thighs\")&&h.includes(\"full_embrace\")",
        "gainBonus": 4,
        "relBonus": 6,
        "textKey": "intimacy.thighs_lap.end0"
      },
      {
        "conditionSrc": "(h)=>h.includes(\"measured_thigh\")",
        "gainBonus": 3,
        "relBonus": 5,
        "textKey": "intimacy.thighs_lap.end1"
      },
      {
        "conditionSrc": "()=>true",
        "gainBonus": 2,
        "relBonus": 3,
        "textKey": "intimacy.thighs_lap.end2"
      }
    ]
  },
  {
    "id": "under_her",
    "label": "Under Her Weight",
    "icon": "🌑",
    "desc": "She rolls over you — or lowers herself fully — pinning you beneath her weight. The physical reality of all of her pressing down is the entire point.",
    "apCost": 1,
    "minTier": 2,
    "phases": [
      {
        "textKey": "intimacy.under_her.p0",
        "choices": [
          {
            "id": "take_weight",
            "label": "Accept the full weight — don't resist",
            "lbs": 3,
            "rel": 5,
            "flag": "accepted_weight",
            "resultKey": "intimacy.under_her.ch.take_weight"
          },
          {
            "id": "hands_back",
            "label": "Put your hands on her back",
            "lbs": 2,
            "rel": 4,
            "flag": "pulled_down",
            "resultKey": "intimacy.under_her.ch.hands_back"
          },
          {
            "id": "breathing",
            "label": "Focus on breathing under her",
            "rel": 4,
            "flag": "breathed_under",
            "resultKey": "intimacy.under_her.ch.breathing"
          }
        ]
      },
      {
        "textKey": "intimacy.under_her.p1",
        "choices": [
          {
            "id": "wrap_up",
            "label": "Try to wrap your arms around her",
            "lbs": 3,
            "rel": 5,
            "flag": "wrapped_up",
            "resultKey": "intimacy.under_her.ch.wrap_up"
          },
          {
            "id": "shift_under",
            "label": "Shift your hips — feel the weight redistribute",
            "lbs": 2,
            "rel": 4,
            "resultKey": "intimacy.under_her.ch.shift_under"
          },
          {
            "id": "press_belly_up",
            "label": "Press your belly up against hers",
            "lbs": 4,
            "rel": 4,
            "flag": "belly_pressed",
            "requires": "accepted_weight",
            "resultKey": "intimacy.under_her.ch.press_belly_up"
          },
          {
            "id": "say_heavier",
            "label": "Tell her you want her heavier",
            "lbs": 5,
            "rel": 7,
            "flag": "asked_heavier",
            "resultKey": "intimacy.under_her.ch.say_heavier"
          }
        ]
      },
      {
        "textKey": "intimacy.under_her.p2",
        "choices": [
          {
            "id": "stay_under",
            "label": "Ask her to stay — all her weight, right here",
            "lbs": 3,
            "rel": 7,
            "flag": "asked_stay",
            "resultKey": "intimacy.under_her.ch.stay_under"
          },
          {
            "id": "reach_face",
            "label": "Reach up and find her face",
            "rel": 6,
            "resultKey": "intimacy.under_her.ch.reach_face"
          },
          {
            "id": "feel_movement",
            "label": "Let her move over you — feel the mass in motion",
            "lbs": 4,
            "rel": 5,
            "resultKey": "intimacy.under_her.ch.feel_movement"
          }
        ]
      }
    ],
    "endings": [
      {
        "conditionSrc": "(h)=>h.includes(\"asked_heavier\")&&h.includes(\"asked_stay\")",
        "gainBonus": 5,
        "relBonus": 7,
        "textKey": "intimacy.under_her.end0"
      },
      {
        "conditionSrc": "(h)=>h.includes(\"belly_pressed\")",
        "gainBonus": 3,
        "relBonus": 5,
        "textKey": "intimacy.under_her.end1"
      },
      {
        "conditionSrc": "()=>true",
        "gainBonus": 2,
        "relBonus": 4,
        "textKey": "intimacy.under_her.end2"
      }
    ]
  },
  {
    "id": "feed_close",
    "label": "Feed Her While Close",
    "icon": "🍖",
    "desc": "You feed her while she's in your arms or your lap — her belly against you, filling and growing heavier with each bite. Every pound she gains, you feel.",
    "apCost": 2,
    "minTier": 2,
    "phases": [
      {
        "textKey": "intimacy.feed_close.p0",
        "choices": [
          {
            "id": "feed_slow",
            "label": "Feed her slowly — one bite at a time, close",
            "lbs": 3,
            "rel": 4,
            "flag": "fed_slow",
            "feed": false,
            "resultKey": "intimacy.feed_close.ch.feed_slow"
          },
          {
            "id": "feed_more",
            "label": "Encourage her to take more, offer seconds immediately",
            "rel": 3,
            "flag": "fed_more",
            "feed": true,
            "gainRange": [
              18,
              32
            ],
            "resultKey": "intimacy.feed_close.ch.feed_more"
          },
          {
            "id": "whisper_eat",
            "label": "Whisper to her while she eats",
            "lbs": 2,
            "rel": 6,
            "flag": "whispered",
            "feed": false,
            "resultKey": "intimacy.feed_close.ch.whisper_eat"
          }
        ]
      },
      {
        "textKey": "intimacy.feed_close.p1",
        "choices": [
          {
            "id": "feel_expansion",
            "label": "Press your hands flat against her belly — feel it growing",
            "lbs": 4,
            "rel": 5,
            "flag": "felt_growth",
            "feed": false,
            "resultKey": "intimacy.feed_close.ch.feel_expansion"
          },
          {
            "id": "offer_more",
            "label": "Offer the next thing before she asks",
            "rel": 4,
            "flag": "offered_more",
            "feed": true,
            "gainRange": [
              15,
              28
            ],
            "resultKey": "intimacy.feed_close.ch.offer_more"
          },
          {
            "id": "belly_around",
            "label": "Wrap both arms around the full belly — hold what she's taken in",
            "lbs": 3,
            "rel": 6,
            "feed": false,
            "requires": "fed_slow",
            "resultKey": "intimacy.feed_close.ch.belly_around"
          },
          {
            "id": "comment_fullness",
            "label": "Tell her how full she's getting",
            "lbs": 2,
            "rel": 5,
            "flag": "told_full",
            "feed": false,
            "resultKey": "intimacy.feed_close.ch.comment_fullness"
          }
        ]
      },
      {
        "textKey": "intimacy.feed_close.p2",
        "choices": [
          {
            "id": "keep_feeding",
            "label": "Keep feeding — bring more to her lips",
            "rel": 5,
            "flag": "kept_feeding",
            "feed": true,
            "gainRange": [
              15,
              25
            ],
            "resultKey": "intimacy.feed_close.ch.keep_feeding"
          },
          {
            "id": "measure_belly",
            "label": "Try to span the belly with both hands — measure the growth",
            "lbs": 3,
            "rel": 6,
            "flag": "measured_growth",
            "feed": false,
            "resultKey": "intimacy.feed_close.ch.measure_belly"
          },
          {
            "id": "tell_her",
            "label": "Tell her what it's like to hold her while she grows",
            "lbs": 2,
            "rel": 7,
            "flag": "told_her_growth",
            "feed": false,
            "resultKey": "intimacy.feed_close.ch.tell_her"
          }
        ]
      }
    ],
    "endings": [
      {
        "conditionSrc": "(h)=>h.includes(\"told_her_growth\")&&h.includes(\"kept_feeding\")",
        "gainBonus": 5,
        "relBonus": 7,
        "textKey": "intimacy.feed_close.end0"
      },
      {
        "conditionSrc": "(h)=>h.includes(\"measured_growth\")",
        "gainBonus": 4,
        "relBonus": 6,
        "textKey": "intimacy.feed_close.end1"
      },
      {
        "conditionSrc": "()=>true",
        "gainBonus": 3,
        "relBonus": 4,
        "textKey": "intimacy.feed_close.end2"
      }
    ]
  },
  {
    "id": "kissing_pull",
    "label": "Pull Her Close",
    "icon": "💜",
    "desc": "Kissing — her body pressing against you, the weight of her arriving in your arms, the soft mass of her coming against your chest.",
    "apCost": 1,
    "minTier": 2,
    "phases": [
      {
        "textKey": "intimacy.kissing_pull.p0",
        "choices": [
          {
            "id": "pull_tighter",
            "label": "Pull her tighter — both arms, all of her",
            "lbs": 2,
            "rel": 4,
            "flag": "pulled_tight",
            "resultKey": "intimacy.kissing_pull.ch.pull_tighter"
          },
          {
            "id": "hands_face",
            "label": "Hold her face in your hands",
            "rel": 5,
            "flag": "held_face",
            "resultKey": "intimacy.kissing_pull.ch.hands_face"
          },
          {
            "id": "let_her_come",
            "label": "Open your arms and let her fill them",
            "lbs": 1,
            "rel": 4,
            "flag": "she_came_to_you",
            "resultKey": "intimacy.kissing_pull.ch.let_her_come"
          }
        ]
      },
      {
        "textKey": "intimacy.kissing_pull.p1",
        "choices": [
          {
            "id": "grind_in",
            "label": "Press into her belly while kissing",
            "lbs": 3,
            "rel": 5,
            "flag": "pressed_together",
            "resultKey": "intimacy.kissing_pull.ch.grind_in"
          },
          {
            "id": "hands_everywhere",
            "label": "Let your hands find everything",
            "lbs": 2,
            "rel": 5,
            "resultKey": "intimacy.kissing_pull.ch.hands_everywhere"
          },
          {
            "id": "break_look",
            "label": "Pull back to look at her",
            "rel": 6,
            "flag": "looked",
            "resultKey": "intimacy.kissing_pull.ch.break_look"
          },
          {
            "id": "drag_lips",
            "label": "Drag your lips along her jaw and throat",
            "lbs": 1,
            "rel": 5,
            "resultKey": "intimacy.kissing_pull.ch.drag_lips"
          }
        ]
      },
      {
        "textKey": "intimacy.kissing_pull.p2",
        "choices": [
          {
            "id": "say_want_her",
            "label": "Say that you want her — specifically, exactly",
            "lbs": 3,
            "rel": 7,
            "flag": "declared",
            "resultKey": "intimacy.kissing_pull.ch.say_want_her"
          },
          {
            "id": "pull_to_couch",
            "label": "Guide her toward sitting — stay close through the move",
            "lbs": 2,
            "rel": 5,
            "resultKey": "intimacy.kissing_pull.ch.pull_to_couch"
          },
          {
            "id": "stay_standing",
            "label": "Stay just like this — don't move",
            "rel": 6,
            "resultKey": "intimacy.kissing_pull.ch.stay_standing"
          }
        ]
      }
    ],
    "endings": [
      {
        "conditionSrc": "(h)=>h.includes(\"declared\")&&h.includes(\"pressed_together\")",
        "gainBonus": 3,
        "relBonus": 7,
        "textKey": "intimacy.kissing_pull.end0"
      },
      {
        "conditionSrc": "(h)=>h.includes(\"looked\")",
        "gainBonus": 2,
        "relBonus": 6,
        "textKey": "intimacy.kissing_pull.end1"
      },
      {
        "conditionSrc": "()=>true",
        "gainBonus": 1,
        "relBonus": 4,
        "textKey": "intimacy.kissing_pull.end2"
      }
    ]
  },
  {
    "id": "squeeze_thighs",
    "label": "Squeeze Her Thighs",
    "icon": "🫶",
    "desc": "Your hands on her thighs — the soft, heavy warmth of them, the give under your fingers, the depth you find when you squeeze.",
    "apCost": 1,
    "minTier": 2,
    "phases": [
      {
        "textKey": "intimacy.squeeze_thighs.p0",
        "choices": [
          {
            "id": "squeeze_firm",
            "label": "Squeeze firmly — feel the depth of it",
            "lbs": 2,
            "rel": 4,
            "flag": "squeezed_firm",
            "resultKey": "intimacy.squeeze_thighs.ch.squeeze_firm"
          },
          {
            "id": "knead_both",
            "label": "Work both thighs at once",
            "lbs": 3,
            "rel": 3,
            "flag": "kneaded_both",
            "resultKey": "intimacy.squeeze_thighs.ch.knead_both"
          },
          {
            "id": "trace_length",
            "label": "Run your hands from knee to hip",
            "lbs": 1,
            "rel": 5,
            "flag": "traced_length",
            "resultKey": "intimacy.squeeze_thighs.ch.trace_length"
          }
        ]
      },
      {
        "textKey": "intimacy.squeeze_thighs.p1",
        "choices": [
          {
            "id": "inner_thigh",
            "label": "Move to the inner thighs",
            "lbs": 3,
            "rel": 5,
            "flag": "inner_reached",
            "resultKey": "intimacy.squeeze_thighs.ch.inner_thigh"
          },
          {
            "id": "measure_squeeze",
            "label": "Squeeze as hard as you can — measure the depth",
            "lbs": 4,
            "rel": 4,
            "requires": "squeezed_firm",
            "resultKey": "intimacy.squeeze_thighs.ch.measure_squeeze"
          },
          {
            "id": "move_to_buttocks",
            "label": "Let your hands drift higher and back",
            "lbs": 2,
            "rel": 5,
            "flag": "found_buttocks",
            "resultKey": "intimacy.squeeze_thighs.ch.move_to_buttocks"
          },
          {
            "id": "describe_them",
            "label": "Tell her how large her thighs have gotten",
            "lbs": 3,
            "rel": 6,
            "flag": "described",
            "resultKey": "intimacy.squeeze_thighs.ch.describe_them"
          }
        ]
      },
      {
        "textKey": "intimacy.squeeze_thighs.p2",
        "choices": [
          {
            "id": "use_both_hands_inner",
            "label": "Both hands on the inner thigh — slow and firm",
            "lbs": 4,
            "rel": 7,
            "flag": "inner_both",
            "requires": "inner_reached",
            "resultKey": "intimacy.squeeze_thighs.ch.use_both_hands_inner"
          },
          {
            "id": "span_thigh",
            "label": "Span the widest part — measure with both hands",
            "lbs": 3,
            "rel": 6,
            "flag": "spanned",
            "resultKey": "intimacy.squeeze_thighs.ch.span_thigh"
          },
          {
            "id": "just_squeeze_hold",
            "label": "Squeeze and hold — stay in the grip",
            "lbs": 2,
            "rel": 5,
            "resultKey": "intimacy.squeeze_thighs.ch.just_squeeze_hold"
          }
        ]
      }
    ],
    "endings": [
      {
        "conditionSrc": "(h)=>h.includes(\"inner_both\")&&h.includes(\"described\")",
        "gainBonus": 4,
        "relBonus": 6,
        "textKey": "intimacy.squeeze_thighs.end0"
      },
      {
        "conditionSrc": "(h)=>h.includes(\"spanned\")",
        "gainBonus": 3,
        "relBonus": 5,
        "textKey": "intimacy.squeeze_thighs.end1"
      },
      {
        "conditionSrc": "()=>true",
        "gainBonus": 2,
        "relBonus": 4,
        "textKey": "intimacy.squeeze_thighs.end2"
      }
    ]
  },
  {
    "id": "squeeze_chest",
    "label": "Squeeze Her Chest",
    "icon": "💛",
    "desc": "Your hands on her breasts — the weight and warmth of them, the give and depth, the soft impossible fullness of them in your palms.",
    "apCost": 1,
    "minTier": 2,
    "phases": [
      {
        "textKey": "intimacy.squeeze_chest.p0",
        "choices": [
          {
            "id": "cup_both",
            "label": "Cup both breasts — feel the full weight",
            "lbs": 2,
            "rel": 4,
            "flag": "cupped_both",
            "resultKey": "intimacy.squeeze_chest.ch.cup_both"
          },
          {
            "id": "press_together",
            "label": "Press them together gently",
            "lbs": 3,
            "rel": 4,
            "flag": "pressed_together_chest",
            "resultKey": "intimacy.squeeze_chest.ch.press_together"
          },
          {
            "id": "knead_slow",
            "label": "Knead slowly — explore the depth",
            "lbs": 2,
            "rel": 5,
            "flag": "kneaded_chest",
            "resultKey": "intimacy.squeeze_chest.ch.knead_slow"
          }
        ]
      },
      {
        "textKey": "intimacy.squeeze_chest.p1",
        "choices": [
          {
            "id": "lift_weight",
            "label": "Lift — feel the actual weight of them",
            "lbs": 3,
            "rel": 5,
            "flag": "lifted_chest",
            "resultKey": "intimacy.squeeze_chest.ch.lift_weight"
          },
          {
            "id": "thumbs_focus",
            "label": "Focus with your thumbs — find the most sensitive point",
            "lbs": 2,
            "rel": 6,
            "flag": "found_point",
            "requires": "kneaded_chest",
            "resultKey": "intimacy.squeeze_chest.ch.thumbs_focus"
          },
          {
            "id": "face_in",
            "label": "Press your face between them again",
            "lbs": 1,
            "rel": 5,
            "resultKey": "intimacy.squeeze_chest.ch.face_in"
          },
          {
            "id": "tell_her_gorgeous",
            "label": "Tell her what her chest does to you",
            "lbs": 2,
            "rel": 6,
            "flag": "told_her_gorgeous",
            "resultKey": "intimacy.squeeze_chest.ch.tell_her_gorgeous"
          }
        ]
      },
      {
        "textKey": "intimacy.squeeze_chest.p2",
        "choices": [
          {
            "id": "squeeze_firm_chest",
            "label": "Squeeze firmly — both at once",
            "lbs": 4,
            "rel": 6,
            "flag": "squeezed_firm_chest",
            "resultKey": "intimacy.squeeze_chest.ch.squeeze_firm_chest"
          },
          {
            "id": "measure_chest",
            "label": "Try to span one breast fully",
            "lbs": 3,
            "rel": 6,
            "flag": "measured_chest",
            "resultKey": "intimacy.squeeze_chest.ch.measure_chest"
          },
          {
            "id": "never_let_go",
            "label": "Hold them — tell her you'd stay like this",
            "lbs": 2,
            "rel": 7,
            "flag": "declared_chest",
            "resultKey": "intimacy.squeeze_chest.ch.never_let_go"
          }
        ]
      }
    ],
    "endings": [
      {
        "conditionSrc": "(h)=>h.includes(\"declared_chest\")&&h.includes(\"squeezed_firm_chest\")",
        "gainBonus": 4,
        "relBonus": 7,
        "textKey": "intimacy.squeeze_chest.end0"
      },
      {
        "conditionSrc": "(h)=>h.includes(\"measured_chest\")",
        "gainBonus": 3,
        "relBonus": 5,
        "textKey": "intimacy.squeeze_chest.end1"
      },
      {
        "conditionSrc": "()=>true",
        "gainBonus": 2,
        "relBonus": 4,
        "textKey": "intimacy.squeeze_chest.end2"
      }
    ]
  }
];

export const INTIMACY_CONTEXTUAL = {
  "session_high_fullness": {
    "id": "session_high_fullness",
    "label": "Overflowing",
    "icon": "💜",
    "apCost": 0,
    "phases": [
      {
        "textKey": "intimacy.session_high_fullness.p0",
        "choices": [
          {
            "id": "come_close",
            "label": "Come to her — put your hands on her full belly",
            "lbs": 4,
            "rel": 5,
            "flag": "touched_full",
            "resultKey": "intimacy.session_high_fullness.ch.come_close"
          },
          {
            "id": "sit_behind",
            "label": "Sit behind her and hold her from behind",
            "rel": 6,
            "flag": "held_full",
            "resultKey": "intimacy.session_high_fullness.ch.sit_behind"
          },
          {
            "id": "tell_her_full",
            "label": "Tell her she looks incredibly full",
            "lbs": 3,
            "rel": 5,
            "flag": "named_full",
            "resultKey": "intimacy.session_high_fullness.ch.tell_her_full"
          }
        ]
      },
      {
        "textKey": "intimacy.session_high_fullness.p1",
        "choices": [
          {
            "id": "press_gently",
            "label": "Press very gently against the taut belly",
            "lbs": 5,
            "rel": 6,
            "flag": "pressed_full",
            "resultKey": "intimacy.session_high_fullness.ch.press_gently"
          },
          {
            "id": "kiss_belly_full",
            "label": "Press your lips to the taut belly",
            "lbs": 3,
            "rel": 7,
            "flag": "kissed_full",
            "resultKey": "intimacy.session_high_fullness.ch.kiss_belly_full"
          },
          {
            "id": "stay_close",
            "label": "Just stay close — hands and warmth only",
            "rel": 5,
            "resultKey": "intimacy.session_high_fullness.ch.stay_close"
          }
        ]
      }
    ],
    "endings": [
      {
        "conditionSrc": "(h)=>h.includes(\"kissed_full\")&&h.includes(\"touched_full\")",
        "gainBonus": 4,
        "relBonus": 6,
        "textKey": "intimacy.session_high_fullness.end0"
      },
      {
        "conditionSrc": "(h)=>h.includes(\"pressed_full\")",
        "gainBonus": 3,
        "relBonus": 5,
        "textKey": "intimacy.session_high_fullness.end1"
      },
      {
        "conditionSrc": "()=>true",
        "gainBonus": 2,
        "relBonus": 3,
        "textKey": "intimacy.session_high_fullness.end2"
      }
    ]
  },
  "session_tapout": {
    "id": "session_tapout",
    "label": "Past Her Limit",
    "icon": "🔴",
    "apCost": 0,
    "phases": [
      {
        "textKey": "intimacy.session_tapout.p0",
        "choices": [
          {
            "id": "hold_her",
            "label": "Hold her — hands on her full belly, steady",
            "lbs": 3,
            "rel": 6,
            "flag": "held_tap",
            "resultKey": "intimacy.session_tapout.ch.hold_her"
          },
          {
            "id": "rub_slow",
            "label": "Rub her belly very slowly and gently",
            "lbs": 2,
            "rel": 7,
            "flag": "rubbed_tap",
            "resultKey": "intimacy.session_tapout.ch.rub_slow"
          },
          {
            "id": "tell_her_proud",
            "label": "Tell her you're proud of how far she went",
            "lbs": 2,
            "rel": 5,
            "resultKey": "intimacy.session_tapout.ch.tell_her_proud"
          }
        ]
      }
    ],
    "endings": [
      {
        "conditionSrc": "(h)=>h.includes(\"rubbed_tap\")",
        "gainBonus": 3,
        "relBonus": 6,
        "textKey": "intimacy.session_tapout.end0"
      },
      {
        "conditionSrc": "(h)=>h.includes(\"held_tap\")",
        "gainBonus": 2,
        "relBonus": 5,
        "textKey": "intimacy.session_tapout.end1"
      },
      {
        "conditionSrc": "()=>true",
        "gainBonus": 1,
        "relBonus": 3,
        "textKey": "intimacy.session_tapout.end2"
      }
    ]
  },
  "dinner_afterward": {
    "id": "dinner_afterward",
    "label": "After the Dinner",
    "icon": "🌙",
    "apCost": 0,
    "phases": [
      {
        "textKey": "intimacy.dinner_afterward.p0",
        "choices": [
          {
            "id": "move_close",
            "label": "Come around the table — sit beside her",
            "rel": 5,
            "flag": "moved_close",
            "resultKey": "intimacy.dinner_afterward.ch.move_close"
          },
          {
            "id": "comment_full",
            "label": "Tell her what she looks like right now",
            "lbs": 3,
            "rel": 5,
            "flag": "commented",
            "resultKey": "intimacy.dinner_afterward.ch.comment_full"
          },
          {
            "id": "offer_more",
            "label": "Ask if she wants anything else",
            "lbs": 5,
            "rel": 4,
            "flag": "offered_more_after",
            "resultKey": "intimacy.dinner_afterward.ch.offer_more"
          }
        ]
      },
      {
        "textKey": "intimacy.dinner_afterward.p1",
        "choices": [
          {
            "id": "stay_long",
            "label": "Stay long after — no hurry",
            "rel": 7,
            "flag": "stayed_long",
            "resultKey": "intimacy.dinner_afterward.ch.stay_long"
          },
          {
            "id": "hand_on_belly",
            "label": "Put your hand on her belly and leave it there",
            "lbs": 4,
            "rel": 6,
            "flag": "hand_on_belly_after",
            "resultKey": "intimacy.dinner_afterward.ch.hand_on_belly"
          },
          {
            "id": "plan_next",
            "label": "Tell her you want to do this again",
            "lbs": 3,
            "rel": 7,
            "flag": "planned_next",
            "resultKey": "intimacy.dinner_afterward.ch.plan_next"
          }
        ]
      }
    ],
    "endings": [
      {
        "conditionSrc": "(h)=>h.includes(\"planned_next\")&&h.includes(\"hand_on_belly_after\")",
        "gainBonus": 5,
        "relBonus": 7,
        "textKey": "intimacy.dinner_afterward.end0"
      },
      {
        "conditionSrc": "(h)=>h.includes(\"stayed_long\")",
        "gainBonus": 3,
        "relBonus": 5,
        "textKey": "intimacy.dinner_afterward.end1"
      },
      {
        "conditionSrc": "()=>true",
        "gainBonus": 2,
        "relBonus": 3,
        "textKey": "intimacy.dinner_afterward.end2"
      }
    ]
  }
};

export function evalIntimacyEndingCondition(conditionSrc, history) {
  try {
    const fn = new Function('history', `return (${conditionSrc})(history);`);
    return !!fn(history);
  } catch {
    return false;
  }
}
