// Systems expected to participate in the mechanics depth layer (~50% richer secondary reads).
export const MECHANICS_DEPTH_SYSTEMS = [
  { id: 'feeding', file: 'feedingSession.js' },
  { id: 'gain', file: 'gainSystem.js' },
  { id: 'relationshipEcology', file: 'relationshipEcology.js' },
  { id: 'hunger', file: 'hungerAddiction.js' },
  { id: 'talk', file: 'talkSystem.js' },
  { id: 'discontent', file: 'discontent.js' },
  { id: 'resonance', file: 'v2/cravingResonance.js' },
  { id: 'scrutiny', file: 'scrutinyConsequences.js' },
  { id: 'psych', file: 'psychState.js' },
  { id: 'devices', file: 'deviceGating.js' },
  { id: 'deviceDependence', file: 'deviceDependence.js' },
  { id: 'witness', file: 'campusWitness.js' },
  { id: 'hallLounge', file: 'hallLoungeSkills.js' },
  { id: 'hallBlueprint', file: 'hallBlueprint.js' },
  { id: 'hallAmbiance', file: 'hallAmbiance.js' },
  { id: 'pharmacist', file: 'pharmacist.js' },
  { id: 'campusSaturation', file: 'campusSaturation.js' },
  { id: 'intimacy', file: 'intimacyGating.js' },
  { id: 'opposition', file: 'opposition.js' },
  { id: 'oppositionIntegration', file: 'oppositionIntegration.js' },
  { id: 'growthEvents', file: 'growthEvents.js' },
  { id: 'competitiveGainer', file: 'competitiveGainerState.js' },
  { id: 'inventionUpgrades', file: 'inventionUpgrades.js' },
];
