// ═══════════════════════════════════════════════════════════════
// PRE-STREAM UI — themes, choice copy, pixel sprites (16×16, centered)
// ═══════════════════════════════════════════════════════════════

export const STREAM_PIXEL_PALETTE = {
  '.': 'transparent',
  K: '#1a1020',
  k: '#2a2030',
  W: '#f0f4ff',
  R: '#e74c3c',
  r: '#ff6b5a',
  P: '#e056fd',
  p: '#c084fc',
  Y: '#fbbf24',
  y: '#fde68a',
  G: '#4ade80',
  g: '#86efac',
  B: '#38bdf8',
  b: '#7dd3fc',
  O: '#d97706',
  o: '#fbbf24',
  S: '#e8c4b0',
  s: '#c9a088',
  C: '#94a3b8',
  c: '#b8c4d0',
  M: '#f472b6',
  m: '#fbcfe8',
  L: '#a855f7',
  l: '#d8b4fe',
  H: '#0f0a14',
  D: '#8b7355',
  d: '#a08060',
  T: '#3b82f6',
  t: '#60a5fa',
  N: '#1e3a5f',
  n: '#2563eb',
};

/** Short labels rendered on branded hat sprite */
export const BRAND_HAT_LABELS = {
  crunchforge: 'CF',
  fizzpeak: 'FP',
  velvetmelt: 'VM',
  glazeco: 'GZ',
};

/** 16×16 character grids — art centered in canvas */
export const PRE_STREAM_SPRITES = {
  // ── T-shirt (short sleeves, round neck) ─────────────────────
  'outfit.casual': [
    '................',
    '................',
    '....KKKKKKKK....',
    '...KWWWWWWWWK...',
    '..KWWWWWWWWWWK..',
    '..KWWWWWWWWWWK..',
    '...KWWWKWWWWK...',
    '...KWWWWWWWWK...',
    '...KWWWWWWWWK...',
    '...KWWWWWWWWK...',
    '....KWWWWWWK....',
    '.....KKKKKK.....',
    '................',
    '................',
    '................',
    '................',
  ],
  // ── Bikini (triangle top + bottom) ───────────────────────────
  'outfit.revealing': [
    '................',
    '.....KMMMMK.....',
    '....KMMK.KMMK...',
    '....KMMK.KMMK...',
    '.....KSKKSK.....',
    '.....KSSSK.....',
    '.....KSSSK.....',
    '....KKKKKKK.....',
    '....KM...MK.....',
    '....KM...MK.....',
    '.....K...K......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // ── Brand baseball cap (label drawn in StreamPixelIcon) ─────
  'outfit.branded': [
    '................',
    '....bbbbbbb.....',
    '...bbbbbbbbb....',
    '..KRRRRRRRRRK...',
    '..KRRRRRRRRRK...',
    '..KRRRRRRRRRK...',
    '...KSSSSSSSK....',
    '....KSSSSSK.....',
    '.....KKKKK......',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  'bodyCheck.quick': [
    '................',
    '....BBBBBB......',
    '...BSSSSSSB.....',
    '...BSBSSBSB.....',
    '...BSSSSSSB.....',
    '....BBBBBB......',
    '......BBB.......',
    '.....B...B......',
    '................',
    '....KKKKKK......',
    '...KSSSSSSK.....',
    '...KSSSSSSK.....',
    '....KKKKKK......',
    '................',
    '................',
    '................',
  ],
  'bodyCheck.thorough': [
    '................',
    '.....SSSSS......',
    '....SSSSSSS.....',
    '...KSSSSSSSK....',
    '...KSSSSSSSK....',
    '...KSSnnnSSK....',
    '...KSSSSSSSK....',
    '....SSSSSSS.....',
    '.....SSSSS......',
    '.....K...K......',
    '.....K...K......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  'bodyCheck.showoff': [
    '................',
    '....YYYYYY......',
    '...YSSSSSSY.....',
    '...YSSSSSSY.....',
    '...YSSSSSSY.....',
    '....YYYYYY......',
    '.....SSSSS......',
    '....SSSSSSS.....',
    '...SSSSSSSSS....',
    '...SSSSSSSSS....',
    '....SSSSSSS.....',
    '.....SSSSS......',
    '................',
    '................',
    '................',
    '................',
  ],
  // ── Empty round plate (uniform plate color) ─────────────────
  'snack.skip': [
    '................',
    '................',
    '.....ccccc......',
    '....ccccccc.....',
    '...ccccccccc....',
    '...ccccccccc....',
    '...ccccccccc....',
    '....ccccccc.....',
    '.....ccccc......',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // ── Round pizza — one slice worth (top-down circle) ─────────
  'snack.light': [
    '................',
    '................',
    '.....OOOOO......',
    '....OYYYYYO.....',
    '....OYYRYYO.....',
    '....OYYYYYO.....',
    '.....OOOOO......',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // ── Full round pizza ─────────────────────────────────────────
  'snack.heavy': [
    '................',
    '....OOOOOOO.....',
    '...OYYYYYYYO....',
    '...OYRYYRYYO....',
    '...OYYYYYYYO....',
    '...OYRYYRYYO....',
    '...OYYYYYYYO....',
    '....OOOOOOO.....',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  'warmup.skip': [
    '................',
    '...........RR...',
    '..........RRR...',
    '.........RR.....',
    '........RR......',
    '.......RR.......',
    '......RR........',
    '.....RR.........',
    '....RR..........',
    '...RRR..........',
    '..RR............',
    '.RR.............',
    '................',
    '................',
    '................',
    '................',
  ],
  'warmup.stretch': [
    '................',
    '.....K...K......',
    '....K.K.K.K.....',
    '...K..SSS..K....',
    '.....SSSSS......',
    '....SSSSSSS.....',
    '....SSSSSSS.....',
    '.....SSSSS......',
    '.....SSSSS......',
    '.....K...K......',
    '.....K...K......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // ── Half pizza on round plate ───────────────────────────────
  'warmup.eat': [
    '................',
    '.....ccccc......',
    '....ccccccc.....',
    '....cOOOOOc.....',
    '....cOYYYOc.....',
    '....cOYRYOc.....',
    '....cOYYYOc.....',
    '....ccccccc.....',
    '.....ccccc......',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  'setup.minimal': [
    '................',
    '....KK..........',
    '...KSSK.........',
    '...KSSK.........',
    '....KK..........',
    '.......KK.......',
    '......KSSK......',
    '......KSSK......',
    '.......KK.......',
    '................',
    '....KKKKKK......',
    '...KSSSSSSK.....',
    '....KKKKKK......',
    '................',
    '................',
    '................',
  ],
  'setup.comfort': [
    '................',
    '....PPPPPP......',
    '...PSSSSSSP.....',
    '...PSSSSSSP.....',
    '....PPPPPP......',
    '................',
    '....SSSSSSS.....',
    '...SSSSSSSSS....',
    '...SSSSSSSSS....',
    '....SSSSSSS.....',
    '.....K...K......',
    '.....K...K......',
    '................',
    '................',
    '................',
    '................',
  ],
  'setup.production': [
    '................',
    '....YYYYYY......',
    '...Y......Y.....',
    '...Y..KK..Y.....',
    '...Y.KSSK.Y.....',
    '...Y..KK..Y.....',
    '...Y......Y.....',
    '....YYYYYY......',
    '....BBBBBB......',
    '...BSSSSSSB.....',
    '...BSSSSSSB.....',
    '....BBBBBB......',
    '................',
    '................',
    '................',
    '................',
  ],
};

export const PRE_STREAM_THEMES = {
  outfit: {
    accent: '#e056fd',
    accentDim: '#9020b0',
    accentGlow: 'rgba(224,86,253,0.25)',
    bg: 'linear-gradient(165deg,#140818 0%,#1e0a28 45%,#120610 100%)',
    border: '#e056fd55',
    tag: 'OUTFIT CHECK',
    headline: 'What should Destiny wear?',
    question: 'Pick her on-camera look before chat loads in.',
  },
  bodyCheck: {
    accent: '#38bdf8',
    accentDim: '#1d6fa8',
    accentGlow: 'rgba(56,189,248,0.22)',
    bg: 'linear-gradient(165deg,#081018 0%,#0a1a28 45%,#060c14 100%)',
    border: '#38bdf855',
    tag: 'BODY CHECK',
    headline: 'How does she check in?',
    question: 'Does she glance, measure up, or put on a show?',
  },
  snack: {
    accent: '#fbbf24',
    accentDim: '#b8860a',
    accentGlow: 'rgba(251,191,36,0.22)',
    bg: 'linear-gradient(165deg,#141008 0%,#201808 45%,#100c06 100%)',
    border: '#fbbf2455',
    tag: 'PRE-SNACK',
    headline: 'Anything before go-live?',
    question: 'Save room, nibble light, or go in hungry.',
  },
  warmup: {
    accent: '#fb923c',
    accentDim: '#c2410c',
    accentGlow: 'rgba(251,146,60,0.22)',
    bg: 'linear-gradient(165deg,#140c08 0%,#221408 45%,#100804 100%)',
    border: '#fb923c55',
    tag: 'WARM-UP',
    headline: 'How does she warm up?',
    question: 'Stretch, chat, or skip straight to business.',
  },
  setup: {
    accent: '#a78bfa',
    accentDim: '#6d4bc9',
    accentGlow: 'rgba(167,139,250,0.22)',
    bg: 'linear-gradient(165deg,#0c0818 0%,#18102a 45%,#0a0614 100%)',
    border: '#a78bfa55',
    tag: 'STREAM SETUP',
    headline: 'How\'s the stream set up?',
    question: 'Rush it, get comfortable, or go full production.',
  },
};

export const PRE_STREAM_CHOICE_META = {
  'outfit.casual': { hint: 'Balanced', blurb: 'Classic tee. Cozy stream fit.' },
  'outfit.revealing': { hint: '+Audience', blurb: 'Bikini on camera. Chat will notice.' },
  'outfit.branded': { hint: '+Sponsor vibe', blurb: 'Sponsor cap — rep the brand.' },
  'bodyCheck.quick': { hint: 'Balanced', blurb: 'Fast mirror check. Move on.' },
  'bodyCheck.thorough': { hint: '+Capacity', blurb: 'Slow, honest, hands-on.' },
  'bodyCheck.showoff': { hint: '+Audience · +Gain', blurb: 'Give chat the full tour.' },
  'snack.skip': { hint: 'Save room', blurb: 'Empty plate — saving room for the challenge.' },
  'snack.light': { hint: '+Capacity', blurb: 'A slice of round pizza to wake up.' },
  'snack.heavy': { hint: '+Gain · +Risk', blurb: 'Whole round pizza before go-live.' },
  'warmup.skip': { hint: 'Fast start', blurb: 'No preamble. Straight in.' },
  'warmup.stretch': { hint: '+Capacity', blurb: 'Position and loosen up.' },
  'warmup.eat': { hint: '+Gain · +Chat', blurb: 'Half pizza on a plate while chatting.' },
  'setup.minimal': { hint: '−Capacity', blurb: 'Camera on. Good enough.' },
  'setup.comfort': { hint: '+Capacity · +Gain', blurb: 'Pillows, reach, support.' },
  'setup.production': { hint: '+Audience', blurb: 'Lights, angles, overlays.' },
};

export const PRE_STREAM_INTRO = {
  headline: 'Ready to go live?',
  sub: 'Five choices shape how Destiny handles the stream — outfit, body, snacks, warm-up, and setup.',
  cta: 'Set up the stream',
};
