export const IMMOBILE_REDIRECT = {
  0:{ // Brittany — cheerleader
    blob:      "You reach for your keys, then stop. Brittany hasn't left her room in weeks — her thighs press the arms of her reinforced chair, her belly rests warm and settled in her lap, and a restaurant is somewhere between impossible and absurd. She knows you're thinking about dinner. She's already thinking about what you should bring.",
  },
  1:{ // Madeline — bookworm
    blob:      "Madeline documented this, actually. Three weeks ago. She noted, with clinical precision, that she had reached a size where transit to public venues was no longer practical and proposed that you come to her instead. The proposal was filed, annotated, and left on the desk she can barely reach over her belly.",
  },
  2:{ // Kylie — influencer
    blob:      "Going to a restaurant would mean cameras, questions, and the walk from car to table that Kylie physically can't make anymore. She solved this a long time ago: everything comes to her. The cameras come to her, the food comes to her, and so do you.",
  },
  3:{ // Serena — athlete
    blob:      "You think about the restaurant for a moment, then think about Serena's thighs alone and let it go. She hasn't left her apartment since last month — the hallway is manageable, the stairs are not. You're bringing dinner. She's already hungry.",
  },
  4:{ // Fiona — artsy
    blob:      "Fiona hasn't left her studio in three weeks and calls it a residency. Her belly fills the chair in soft warm folds, her arms rest across its expanse, and the work covers every surface around her. She's not going to the restaurant. You're going to her.",
  },
  5:{ // Destiny — gamer
    blob:      "Destiny hasn't moved from her setup in so long the chair has moulded itself to her. Her belly settles between the armrests, her thighs spread to the edges, and the idea of a restaurant is incompatible with every metric of her current lifestyle. You're doing delivery. You know where to find her.",
  },
  6:{ // Tiffany — sorority
    blob:      "Tiffany is the house now — she hosts from her bed, food delivered in waves, the girls coming to her. She stopped going out when the doorframe became a problem, and nobody mentioned it because everyone adjusted around her, which is just how it's always been with Tiffany. You're bringing dinner. She'll tell you where to put it.",
  },
  7:{ // Priya — overachiever
    blob:      "Priya filed a report about this three weeks ago. She cited logistics, efficiency metrics, and a cost-benefit analysis of transit versus delivery, and concluded that you coming to her was the optimal solution. The report is on her desk. She is also mostly on her desk. You're going to her.",
  },
  8:{ // Maya — quiet
    blob:      "Maya doesn't need to say anything about why she's not going out — you can tell from the doorframe and from the way she's settled into her space like something permanent. She's there. She's warm. She's been waiting. Bring her food.",
  },
  9:{ // Chloe — transfer
    blob:      "Chloe made this place home and now she is this place — they named a spot for her in the dining hall and deliver to her room because she stopped being able to make the walk. She's fine with it. She's happier than she's been in years. You're going to her. She'll be glad you came.",
  },
  10:{ // Jasmine — cheerleader
    blob:      "Jasmine hasn't made it down the stairs in two weeks. Her belly fills the entire couch when she sits — warm, soft, spreading wide and forward — and she is emphatically at peace with this. You're bringing dinner. She'll have opinions about the order.",
  },
  11:{ // Emma — bookworm
    blob:      "Emma ordered a reinforced desk chair four months ago and hasn't left its radius since. Her belly rests forward and warm in her lap, papers spread around her, the work continuing regardless. She knows you want to take her to dinner. She'll accept delivery instead and pretend it was her idea.",
  },
  12:{ // Nadia — psych
    blob:      "Nadia hasn't left her office in weeks and she has noted this in her research log with the same detachment she brings to everything else. Her vast form fills the chair, her notebooks spread around her, and she watches anyone who enters with the same clinical attention. She's not going anywhere. You're going to her, and she'll observe you the whole time.",
  },
  13:{ // Aaliyah — athlete
    blob:      "Aaliyah hasn't been outside in three weeks. Her body — vast, warm, the muscle still somewhere underneath the soft weight — fills the room in a way she finds completely acceptable. You're bringing dinner. She'll want a lot of it.",
  },
  14:{ // Mary Jane — farm_girl
    blob:      "Mary Jane hasn't left the homestead in weeks and she doesn't need to. The room comes to her — the deliveries, the cast iron, Grandma Mae's packages, and now you. She'll already know what she wants you to bring. She texted you the list before you even asked.",
  },
};

export const TAP_OUT_DIALOGUE = {
  0: [  // Brittany
    (s) => `${s.name} presses both hands flat against her middle and her eyes go wide, like she's been ambushed by her own body. "Okay. Okay, that's — I'm tapping out, I'm literally tapping out, that doesn't happen to me." She says it with competitive outrage, like her stomach has personally betrayed her.`,
    (s) => `${s.name} sits back heavily, breathing through her nose, one hand splayed over the round curve of her belly. "I know my limits now and this is past them." She says it with more dignity than the situation requires, which is very on-brand. "I'm calling it. Don't look at me like that."`,
    (s) => `${s.name} exhales slowly, settling back into the cushions like someone surrendering a war they picked themselves. "Okay. Done. I'm done." She presses her belly with both hands to confirm the obvious. "That's a record and I'm claiming it and also I need to not move for a while."`,
    (s) => `${s.name} holds up one hand — flat, authoritative, squad-captain energy even now. "I'm calling it." Her enormous belly rises and falls with careful breaths. "I know exactly what I'm doing and what I'm doing right now is stopping, and that is a choice, not a defeat." A beat. "I'm going to need to lie down."`,
  ],
  1: [  // Madeline
    (s) => `${s.name} sets down her fork with precise, deliberate care. "I need to note that I have reached an empirically verifiable limit." She presses her fingers against the tight round swell of her belly. "This is data. I am logging it. The session is over."`,
    (s) => `${s.name} folds her hands on the table in a way that says she is being very professional about this. "My capacity has been exceeded by a statistically significant margin." She breathes carefully. "I'm calling the session. I want it on record that I held out considerably longer than I anticipated."`,
    (s) => `${s.name} looks at her belly with the expression she reserves for a very compelling dataset. "I've exceeded my own documented baseline by approximately — " she pauses to calculate, which is impressive given the circumstances " — a lot." She exhales. "Stopping now. The numbers are extraordinary. I'm going to lie very still and think about them."`,
    (s) => `${s.name} closes her eyes briefly. "The threshold has been passed. Considerably." She rests both hands on her massive, taut belly with scholarly calm. "I want to note that this outcome represents a personal record and I intend to write a very thorough summary." She opens her eyes. "After I stop moving. Which is now."`,
  ],
  2: [  // Kylie
    (s) => `${s.name} puts down her fork and immediately reaches for her phone — then stops, because actually she cannot hold the phone at that angle right now, her stomach is in the way. "Okay. Tapping out." She sounds more surprised than anything. "That's actually — that's a lot of content in there. I need a minute."`,
    (s) => `${s.name} presses her hand against her bloated middle and makes the face of someone recalculating a very important metric. "My engagement rate when I look like this is insane but I also genuinely cannot eat another bite." She breathes slowly. "Calling it. We got the content. I need to horizontal."`,
    (s) => `${s.name} leans back and surveys the situation with the practiced eye of someone who has documented many extreme eating moments. "Okay. That is a look." She presses both hands to the enormous, straining curve of her belly. "We are done for tonight. My body is giving me very clear analytics right now and they say stop."`,
    (s) => `${s.name} holds up a hand. "Done. I'm done." She takes a slow, careful breath over the vast swell of her stomach. "The numbers on my body right now are unreal and I am choosing to appreciate them from a horizontal position." She reaches for her phone with the other hand. "Someone's going to need to help me up eventually. Not yet though."`,
  ],
  3: [  // Serena
    (s) => `${s.name} goes quiet in the way she used to go quiet at the end of a brutal interval set — body accounting for itself. "I'm tapping out." She says it simply, hands on her tight, distended belly. "I've hit my wall. I know what hitting my wall feels like. This is it."`,
    (s) => `${s.name} breathes through her mouth for a moment, slow and controlled, like she's managing something. "Okay. My body is done." She presses her palm flat against her full, round stomach. "I trained long enough to know when to call it. Calling it." She leans back carefully. "Good session though."`,
    (s) => `${s.name} rests both hands on the wide swell of her belly with the focused attention of someone monitoring an important gauge. "I'm past threshold." She exhales steadily. "I spent years ignoring my body's signals. I don't do that anymore." She meets your eyes. "It's saying stop. I'm stopping."`,
    (s) => `${s.name} sits with the particular stillness of a large, powerful body that has reached its absolute limit — no drama, no protest, just the settled authority of a woman who knows herself very well. "That's it for me," she says. Her enormous belly presses firmly against her palms. "I know this feeling. I've earned this feeling. We're done."`,
  ],
  4: [  // Fiona
    (s) => `${s.name} goes very still, eyes unfocusing slightly, like she's listening to something interior. "I think — " She presses a hand to her full, round belly. "I think I'm at my absolute edge." She sounds almost reverent. "There's no more space. That's — that's a complete feeling. I need to stop."`,
    (s) => `${s.name} closes her eyes and breathes very slowly. "My body has become a kind of still life," she says softly. "Everything full and heavy and finished." She rests both hands on the warm curve of her stomach. "I can't continue. I don't want to ruin it." She exhales. "This is the end of it."`,
    (s) => `${s.name} is quiet for a long moment, both hands moving slowly over the enormous swell of her belly like she's mapping it. "There's a point," she says finally, "where fullness becomes its own complete thing. A form." She looks up. "I'm there. I'm absolutely there. I need to stop and just be in it."`,
    (s) => `${s.name} breathes in slowly, the expansion visibly limited by the vast, round mass of her belly, and then out even slower. "That's all I have," she says, with the quiet finality of a completed work. "I am entirely full. Every single part of me." She doesn't move. "I just need to exist in this for a while. The session is over."`,
  ],
  5: [  // Destiny
    (s) => `${s.name} puts her fork down. Looks at her stomach. Looks at you. "I'm tapping out." She says it with zero inflection. "My body has made a unilateral decision and I'm respecting the process." She reclines approximately two inches, which is all she can manage. "This is fine."`,
    (s) => `${s.name} stops eating mid-bite, considers the situation, and sets the food down with the energy of someone closing a tab. "Done," she says. She presses one hand to her bloated belly without looking at it. "Capacity reached. Session ended. I have no further comments." She stares at the ceiling.`,
    (s) => `${s.name} exhales through her nose. "Yeah. That's my limit." She splays one hand over the round, taut dome of her stomach with the same energy she'd use to acknowledge a final boss. "I found the wall. Good to know where it is." She leans back slightly. "I need to not move now. That's happening."`,
    (s) => `${s.name} holds up two fingers. "Tapping out." She places one hand on her colossal, straining belly without ceremony. "I have exceeded my own parameters by a measurable amount and my body has filed a formal complaint." A pause. "I'm going to lie here and load something on my phone. Don't talk to me for ten minutes."`,
  ],
  6: [  // Tiffany
    (s) => `${s.name} dabs the corner of her mouth with a napkin, sets it down, and folds her hands with perfect composure. "I need to call it there." Her belly is visibly strained beneath her top. "I know my limits. I'm choosing to respect them tonight." She smiles serenely. "It was a beautiful session."`,
    (s) => `${s.name} exhales with the quiet grace of someone who has decided that stopping is simply the most elegant choice available. "That's everything I have," she says pleasantly. She rests one hand on her full, round stomach. "I've genuinely outdone myself tonight." She adjusts her posture carefully. "I'm going to need a moment."`,
    (s) => `${s.name} straightens — or tries to; the attempt is limited by the considerable mass of her belly — and settles back instead with effortless poise. "I'm done," she says. "Not because I want to be, but because my body has made a compelling case." She pats her stomach gently. "Magnificent session. I need to not move for some time."`,
    (s) => `${s.name} takes a slow breath over her vast, round belly and looks at you with the serene authority of someone who has never once been embarrassed by herself. "Calling it," she says. She places one hand on her stomach as if resting it on a throne. "I am completely and perfectly full." She closes her eyes. "Come back in an hour."`,
  ],
  7: [  // Priya
    (s) => `${s.name} sets her fork down and immediately produces her phone to note the time. "I'm stopping," she says. "My stomach is at maximum capacity, I can confirm this empirically, and continuing would yield diminishing returns." She presses her hand to her tight belly. "Logging this. Outstanding outcome."`,
    (s) => `${s.name} presses both palms flat against her bloated, distended middle with the expression of someone verifying a calculation. "I've exceeded my own projected limit by twenty-two percent." She breathes carefully. "That's — that's actually excellent data." She leans back. "I need to stop now. I'm stopping. This is me stopping."`,
    (s) => `${s.name} exhales through her nose in a controlled way that suggests she would like to not exhale at all because there is no room. "Threshold crossed. Session complete." She keeps her hands pressed to her enormous, full belly. "The trajectory on tonight's intake is remarkable. I want to discuss it when I can breathe at a normal depth again." A pause. "Which isn't yet."`,
    (s) => `${s.name} looks at her own vast, round belly with the expression of someone reviewing an exceptional quarterly report. "This is past any number I've previously documented," she says. "By a significant margin." She breathes very slowly. "I'm calling it. Everything hurts in a way that is technically interesting." She closes her eyes. "Give me twenty minutes. I'll have a full summary."`,
  ],
  8: [  // Maya
    (s) => `${s.name} places both hands flat on her distended belly and shakes her head — once, small, definitive. That's all. She's done.`,
    (s) => `${s.name} goes still, hands folded over the round swell of her stomach, and looks at you with an expression that is completely legible: this is it, she has no more. She exhales slowly through her nose. Done.`,
    (s) => `${s.name} presses one hand to her enormous, full belly, closes her eyes, and leans back. When she opens them again she gives you a single slow blink. The session is over. She communicates this entirely without words, the way she communicates most things.`,
    (s) => `${s.name} rests both hands on the vast curve of her belly and stays very still for a long moment. Then she looks at you. Her eyes say: full. Completely full. No more. She doesn't move. She doesn't need to say anything else.`,
  ],
  9: [  // Chloe
    (s) => `${s.name} presses her hands to her stomach and her eyes go wide. "Oh. Oh, wow, I think I — I'm tapping out." She sounds genuinely surprised and a little delighted. "I didn't know I could get this full. That's a new thing I know about myself now!"`,
    (s) => `${s.name} leans back and makes a soft, overwhelmed sound. "Okay, I've — I've hit a wall." She rubs her bloated belly with both hands. "This campus keeps giving me new experiences and I guess this is one of them." She laughs weakly. "I need to lie down. Do I lie down? I'm lying down."`,
    (s) => `${s.name} breathes carefully, hands spread wide over the round, straining swell of her stomach. "I really pushed it tonight," she says, half-impressed with herself. "I'm — okay, I'm done. I'm genuinely done." She looks up with a giddy, slightly overwhelmed smile. "That was incredible. I can't move though."`,
    (s) => `${s.name} takes stock of herself — her enormous, packed belly, her general immobility — with the warm, wondering expression of someone who has genuinely, fully settled in somewhere. "I can't believe this is my life," she says. "In the best way." She pats herself gently. "I'm tapping out. I love it here. I can't move. Both true."`,
  ],
  10: [  // Jasmine
    (s) => `${s.name} tries to sit up straighter and can't quite manage it — there's simply too much in the way. "Okay, I'm out," she says, and laughs at herself freely. "My body is sending me very clear notes right now." She presses a hand to her tight, bloated middle. "Loudest notes I've gotten all semester."`,
    (s) => `${s.name} breathes out long and slow, hands resting on her full, round belly. "I know my body," she says. "I've been in it a long time. It's telling me we're done." She grins. "We're done." There's no distress in it — just physical fact, delivered with the ease of someone who has always been comfortable in herself.`,
    (s) => `${s.name} goes through what looks like a dancer's instinct to rebalance — then stops, because rebalancing around the enormous swell of her belly requires a different centre of gravity than she's used to. "Okay," she says. "I found the limit." She settles back. "I'm done. That was a lot and I mean that as a compliment."`,
    (s) => `${s.name} splays both hands over her vast, heavy belly and holds them there, feeling the fullness, the warmth, the sheer mass of it. "Done," she says simply. She's not distressed. She's not surprised. She's a woman who knows her body better than most, and her body is simply, completely, spectacularly full. "Good session," she says.`,
  ],
  11: [  // Emma
    (s) => `${s.name} sets down her fork and reaches for her tea with slightly unsteady hands. "I think I've reached a natural endpoint," she says carefully. She presses her hand to her full, rounded belly. "There's — there are definitely sensations happening that I would describe as terminal fullness." She blinks. "I need to stop. I am stopping."`,
    (s) => `${s.name} looks at her belly with genuine scholarly interest, which would be more convincing if she weren't also clearly struggling to breathe at full depth. "This is a fascinating physiological state," she says. "I would very much like to write about it." She exhales carefully. "After I stop being in it. Which needs to happen now. I'm done."`,
    (s) => `${s.name} closes her book — she'd been holding it as a prop and they both know it — and folds her hands over the round, enormous swell of her stomach. "Calling it," she says quietly. "I've eaten well past the point a reasonable person would have stopped and I have no regrets, but I am physically finished." She breathes slowly. "I might write a short essay about this later."`,
    (s) => `${s.name} looks down at herself — the vast, round mass of her belly pressing against her cardigan, her hands resting on it like bookends — and smiles softly. "I am extraordinarily full," she says. "I've exceeded every previous benchmark." She tucks her pen behind her ear. "I'm stopping now. I want to lie somewhere soft and think about everything I just ate. Is that available?"`,
  ],
  12: [  // Roxanne
    (s) => `${s.name} stops mid-sentence — she'd been talking about something entirely unrelated — and presses both hands to her stomach. "Oh. Okay. That's it." She looks genuinely impressed. "That is absolutely the end of it. I have found the wall." She slumps back in her chair dramatically. "Wow. Okay. That happened."`,
    (s) => `${s.name} breathes in and the breath stops short, blocked by her bloated, straining belly, and she makes a short, surprised sound. "Okay, we're done," she says. She pats her stomach with both hands. "I have hit maximum. I feel enormous and full and honestly kind of incredible but also I cannot eat another bite. Session over."`,
    (s) => `${s.name} leans back with the boneless energy of someone who has genuinely given everything. "That," she says, voice lower than usual, "is my entire capacity." She spreads her hands wide over the enormous swell of her belly. "All of it. Every bit." She closes her eyes. "I feel like a completed piece. Like the work is done." She exhales. "Done. Done done done."`,
    (s) => `${s.name} goes still — which is rare for her — and the stillness is its own kind of loudness. "I'm tapping out," she says. "And I want it noted that I held on for a long time and gave everything I had and this belly is a masterpiece and I need to stop now." She presses her hands to the vast, full curve of herself. "Someone write that down. That's my artist's statement."`,
  ],
  13: [  // Aaliyah
    (s) => `${s.name} leans back and hooks her thumbs in her waistband, assessing. "Yeah, that's it," she says. Matter-of-fact, no drama. She presses her hand to her tight, bloated belly. "I've played through pain before. This isn't pain. This is just done." She grins. "Good game."`,
    (s) => `${s.name} does the thing athletes do when they've hit their limit — a slow exhale, a stillness, a quiet accounting. "I'm out," she says. "My body's talking to me." She rests a hand on the round, full curve of her stomach. "I've learned to listen to it. Took long enough." She leans back. "That was a good session."`,
    (s) => `${s.name} straightens — tries to — and the significant mass of her belly makes itself known in a very practical way. She laughs, low and easy. "Alright, alright." She keeps both hands on her stomach, feeling its weight. "I know when a game's over." She settles back. "Called it. I'm done. That was a lot."`,
    (s) => `${s.name} is quiet for a moment, both palms resting on the enormous, round swell of her belly, feeling it the way she'd feel the score at the end of a game — just the clean fact of it. "Done," she says. She doesn't need more words than that. She leans back carefully, slowly, the weight of herself a real and present thing. "Good session."`,
  ],
  14: [  // Mary Jane
    (s) => `${s.name} sets both palms flat on her belly and goes still for a second. "Okay," she says, in the considering voice of someone taking stock. "I think that's it." She presses gently. "That's full. That's real full." She looks at you. "I don't quit, just so you know. But that's full."`,
    (s) => `${s.name} breathes out slowly through her nose, both hands on the full round of her belly, and nods once the way you nod when you accept something inevitable. "I'm done," she says. "I know my body. That's done." She stays still for a moment, feeling the weight of it. "Good session," she adds. She means it.`,
    (s) => `${s.name} leans back carefully — a slow, weighted thing — and keeps both hands resting on her enormous belly, feeling the warmth and tightness of it. "I pushed it," she says, almost admiringly. "I really pushed it." She exhales slow. "I'm out. But I'll be back." She sounds completely certain of this.`,
    (s) => `${s.name} is still for a long moment, both hands pressed into the warm give of her belly, and then she says, quietly, "That's everything I have." She doesn't sound disappointed. She sounds like someone who gave everything and knows it. "I'm tapping out. That was real." She looks at you. "You're going to have to come back and let me beat that."`,
  ],
  default: [
    (s) => `${s.name} puts her hands flat on her middle and shakes her head. "I'm done," she says. Her voice is steady. Her belly is full and round and she is past her limit in every measurable sense. "I can't."`,
    (s) => `${s.name} leans back carefully, both hands resting on the bloated swell of her stomach. "That's it for me," she says. She sounds sure. "I found my wall tonight." She breathes slowly. "I'm done."`,
    (s) => `${s.name} presses her palms against her enormous, full belly and meets your eyes. "I'm tapping out." She says it plainly — no apology, no drama. "I'm completely full and I'm stopping." She exhales. "Good session."`,
    (s) => `${s.name} sits very still, hands on the vast, warm swell of her belly, breathing slowly and carefully. "Done," she says. One word. Final. She doesn't try to move. She just exists in the fullness of it, which is considerable, and that's enough.`,
  ],
};

// Unique tap-out dialogue at 250% fullness (extreme, clothes-bursting, immobilized by fullness)
export const TAP_OUT_250 = {
  0:  (s) => `${s.name}'s uniform seams give out — one clean pop, then another, the fabric splitting across her enormous belly as she slumps backward with a gasp. "Okay. OKAY." She spreads her arms wide like she's surrendering to gravity. "That is a record. That is a personal record. I cannot move and my clothes are done for and I am claiming this." Her belly is enormous and round and rock-hard with fullness, pressing against everything. "I need someone to call a car because I am not walking home like this." She can't stand up. She's not trying.`,
  1:  (s) => `${s.name} sets down her fork with precise deliberate care and watches her shirt split open across the belly seam with the expression of someone documenting a lab result. "Noted," she says quietly. "Seam failure at approximately 250 percent capacity. I am unable to stand. I am unable to exit the room under my own power. I will require assistance." She places her hands flat on the taut vast dome of her belly. "This is the most full I have ever been and I want it on record that I held out this long."`,
  2:  (s) => `${s.name} immediately grabs her phone. "This is content," she breathes, before anything else. Her top has split up the side and she is far too stuffed to adjust it or care. "I cannot move. I cannot fit in my car. I cannot stand up from this chair." She frames herself in the camera. "I ate enough for a family of five and I look absolutely incredible and I am stuck here." She is genuinely immobilized. "Can someone get me a blanket? I'm living here now. This is my life now."`,
  3:  (s) => `${s.name}'s athletic jacket pops two buttons across her belly in quick succession and she watches them fly with an athlete's focus. "Okay," she says, very calm. "That's a personal record. That's a body-weight competition personal record." She tries to stand. She gets six inches. She sits back down. "I'm going to need to walk that off for approximately four hours and also I can't walk right now." Her belly presses against the table from below. "I'm not done being proud of this yet." She genuinely isn't.`,
  4:  (s) => `${s.name}'s dress tears along the side seam with a sound like applause and she tilts her head at it, curious and entirely unbothered. "The piece has changed," she says. Her belly is an enormous tight dome pressing outward in all directions. "I've become something that clothing cannot contain and I find that genuinely interesting." She cannot move from the chair. She looks down at herself with the quiet attention of an artist studying a model. "I want to draw this. Someone draw this. I cannot reach my sketchbook from here."`,
  5:  (s) => `The gaming chair's armrest mechanisms give out simultaneously on both sides — snap, snap — and ${s.name} sinks into the widened seat like something settling into orbit. Her shirt has long since surrendered at the belly. "Okay so chat would not believe this," she says, very quiet, like she's narrating to an imaginary stream. "I am literally stuck. Not exaggerating for content. Physically stuck in the chair." She tries to push herself up. Nothing happens. "I am so full I have achieved immobility and I want you all to know I am extremely proud of this and also someone needs to help me."`,
  6:  (s) => `${s.name}'s dress splits quietly down the side and she acknowledges it with a single slow blink. "That was a vintage piece," she says, with the dignity of someone receiving bad news with composure. "I'll have it repaired." She cannot stand. She can barely shift her weight. Her belly presses forward into the table, vast and drum-tight. "I need you to know I am handling this with grace." She folds her hands on the swell of her belly. "I require assistance getting home and I will not be discussing it further." She absolutely means this.`,
  7:  (s) => `${s.name} watches her blouse split across the belly with the expression of someone whose spreadsheet has returned an unexpected value. "Seam failure. Noted." She tries to stand. Sits back. "Motor function temporarily impaired by caloric excess. Logging it." Her belly presses outward in all directions, enormous and completely full. "I have exceeded every previous record by a considerable margin." She picks up her phone to enter the data. "I'll need a car. Not because of the size —" she pauses. "Entirely because of the size. I cannot fit through the door without significant effort and I'm not going to try right now."`,
  8:  (s) => `${s.name} doesn't speak for a moment. Her shirt has split at the side. Her belly presses the table outward slightly. She puts one hand flat on herself and exhales once, slow. "Oh," she says. That's all. She doesn't try to move. She sits with it. After a long moment: "I'm staying here for a while." It is not a question or an apology. She is simply full — more full than she has ever been — and she is sitting with that, and it is enough, and the rest of the world can wait.`,
  9:  (s) => `${s.name}'s jersey tears across the belly in one long horizontal rip and she looks down at it like a coach reviewing footage. "Hm." She tries to stand. Gets two inches. "I can't stand up," she says, in the tone of someone noting a training variable. "I physically cannot stand up right now." She tries again. Nothing. "That's — okay. That's data." Her belly is a vast, tight, magnificent dome pressing against everything in range. "I've eaten enough to fuel a full practice session for the whole team." She almost sounds proud. She is proud. "Call me a car."`,
  10: (s) => `${s.name}'s wrap dress unravels in slow motion and she watches it with wide, delighted eyes. "It's a happening," she breathes. Her belly pushes outward enormous and full, the skin stretched, pressing the table, pressing the chair arms, pressing everything. She can't stand. She's barely trying. "I have become immovable through art. Through eating. Through the complete and total commitment to the process." She opens her arms wide. "This is the piece. I am the piece. Someone document this before I can move again." She absolutely cannot move. She is absolutely thrilled.`,
  11: (s) => `${s.name}'s cardigan splits neatly at the button between her belly and her chest and she watches it with the calm of someone whose hypothesis has been confirmed. "Structural failure at point of maximum fullness," she says. "As predicted." She tries to push back from the table. "I cannot move. I am full to the point of immobility and this is consistent with the data." Her belly presses the table forward slightly. "I want it noted that I am completely fine and also I need someone to call a ride because I cannot fit in my own car right now." She says this the same way she'd say anything else.`,
  12: (s) => `${s.name}'s uniform bursts at the waist in three places at once — pop pop pop — and she throws her head back and laughs. "OKAY. OKAY." She grabs the edge of the table because she can't stand without it and finds that standing isn't actually happening. "I am literally stuck. I am literally too full to leave." Her belly is an enormous tight dome she can't see past. "This is the best this has ever been. This is the greatest day." She can't stop laughing. She also cannot move. "Someone's gonna have to help me out of this chair. I don't even care."`,
  13: (s) => `${s.name}'s dress gives way cleanly along the left side seam and she exhales slowly. "Right," she says. She tries to stand. Does not stand. "I need a plan." She puts both hands on her belly, assessing. "I cannot currently fit through the door at this fullness level. I require a moment." She thinks. "I'm going to need at least twenty minutes, someone to help me up, and a change of clothes." She says this with complete organizational calm. "Text the chapter. Tell them I'm running late. Don't explain."`,
  14: (s) => `${s.name}'s shirt tears across the belly and she looks down at it with an expression that shifts from surprise to delighted disbelief. "Back home this literally never —" She starts laughing. She can't stop. Her belly is enormous and round and drum-tight with fullness and she cannot stand up. "I cannot get up. I am too full to get in a car. I am too full to fit in a car." She presses both hands flat on the globe of her belly. "This campus," she says, like it's an answer to everything. She's still laughing.`,
  default: (s) => `${s.name}'s clothes give out in three places at once and she looks down at the wreckage with the calm of someone who saw this coming. Her belly is enormous, tight, pressing everything. She tries to stand. Does not stand. "I'm done," she says. "I'm very full. I am genuinely unable to leave this chair at the moment and I need you to understand that this is fine." She is very still. "Give me twenty minutes."`,
};

// Intro text shown at the start of private sessions with blob/ascended students (professor comes to her)
export const BLOB_PRIVATE_INTRO = {
  0:  (s) => `${s.name} doesn't come to you anymore — you come to her. You find her in the reinforced space they cleared for her, belly vast and warm and taking up most of the room. You haul yourself up the outer curve of her, hand over hand through the warm rolls, the soft geography of her enormous body. She narrates the whole time. "Left side's easier," she calls down, "hold the second fold." You settle onto the great shelf of her chest, eye level with her face. She looks completely satisfied. "Okay," she says. "Let's go." You get to work.`,
  1:  (s) => `You arrive with the food and ${s.name} acknowledges you with the composed nod of someone who expected you exactly when you arrived. Climbing her is a physical undertaking: you go fold by fold, the warm soft mass of her enormous belly below you, her vast thighs spread wide on the reinforced platform. She has left a detailed note about the approach. You follow it. You settle atop the broad warm shelf of her chest. "I've been thinking," she says, as if you've simply sat down across a table, "about the mechanisms of this." You get to work.`,
  2:  (s) => `${s.name} already has three cameras set up for this. "I've been documenting the approach," she tells you, when you start climbing. "The audience finds it compelling." You go hand-over-hand up the magnificent soft mass of her body — warm rolls, the vast curve of her belly, the enormous slope of her sides — and settle onto the great shelf of her chest. She adjusts one of the cameras remotely. "Okay. Give me something good." She has never been more herself. You get to work.`,
  3:  (s) => `${s.name} gives you a route before you start. "Second fold, then cut left, use the shelf at the hip — it's load-bearing, it'll hold you." She treats it like a training circuit. You follow her instructions, climbing the warm vast geography of her enormous body — thick rolls of soft flesh, the weight and warmth of her immense belly below you — and settle onto the broad shelf of her chest. "Good," she says, with a coach's approval. "Hydration first, then we get into it." You get to work.`,
  4:  (s) => `${s.name} has been waiting for you and she has thoughts about the approach. "Enter from the right," she says. "The light is better from the right." You climb the impossible scale of her — the vast soft folds, the warm landscape of her belly and sides and hips — and haul yourself up to the shelf of her enormous chest. She watches you the whole time with the steady attention of an artist studying a composition. "Yes," she says. "Like that. Exactly like that." You get to work.`,
  5:  (s) => `${s.name} has engineered this. A reinforced handhold attached to the second fold. A custom platform on her left side at hip height. She is immensely practical about what she is. "I timed the last approach at forty-three seconds," she says, when you start climbing. "See if you can beat it." You haul yourself up the soft warm mass of her enormous body — fold by fold, the enormous belly below you like a landscape — and settle onto the warm shelf of her chest. She checks her watch. "Forty-one. New record." You get to work.`,
  6:  (s) => `${s.name} receives you. That's the word for it. You climb — hand over hand up the warm soft rolls, the vast landscape of her enormous belly spread below you — and haul yourself up to the broad shelf of her chest, and she receives you there with the dignity of someone for whom this is the correct order of things. "You're punctual," she says. "I appreciate punctuality." She folds her hands in her enormous lap and waits. You get to work.`,
  7:  (s) => `${s.name} has documented the optimal approach. She reads it to you from her phone as you climb — "second fold, use the hip shelf, angle forty-five degrees at the upper roll" — and you follow the instructions precisely, hauling yourself up the warm soft mass of her enormous body until you settle onto the great shelf of her chest. "Four seconds faster than last time," she notes. "The method is improving." She puts the phone down. You get to work.`,
  8:  (s) => `${s.name} says nothing when you arrive. She watches you start to climb — the warm soft folds of her enormous body, the vast belly below you like a warm continent — and she is very still, and her eyes follow you, and she does not speak until you've settled onto the shelf of her enormous chest. Then: "You made it." Two words. A fact. She looks at you with those quiet eyes and waits. You get to work.`,
  9:  (s) => `${s.name} times you. "Three, two, one —" and you start climbing, hand over hand up the warm massive rolls of her body, the enormous soft belly below you, the warm shelf of her hip, the vast slope of her sides. She counts the whole way. "Thirty-eight seconds," she announces, when you settle onto the broad warm shelf of her chest. "That's a personal record for me too." She hands you the first course before you've even steadied yourself. You get to work.`,
  10: (s) => `${s.name} has set the scene. Candles on every horizontal surface she could reach. She considers the approach part of the ritual. You climb — fold by fold up the warm soft geography of her enormous body, the vast belly below you, the great curved slope of her sides — and haul yourself up to the shelf of her chest. She looks at you with full artist's attention. "Every time you do that," she says, "I want to paint it." She hands you what you need. You get to work.`,
  11: (s) => `${s.name} has left instructions. Not a note — a full typed document, printed, laminated, attached to the first fold with a clip. Approach guide, handhold locations, weight distribution notes. You follow it precisely, climbing the warm soft mass of her enormous body, and settle onto the broad shelf of her chest. She looks up from her book. "You followed the guide," she says, pleased. "Most people don't follow the guide." She closes the book. You get to work.`,
  12: (s) => `${s.name} starts cheering before you're halfway up. "COME ON. LET'S GO. YOU'VE GOT IT." She narrates the whole climb — the warm soft folds, the vast belly below you, the enormous curved slope of her sides — in the enthusiastic play-by-play of someone who genuinely loves this. You haul yourself onto the broad warm shelf of her chest and she gives you a round of applause. "NEW RECORD," she announces, for nothing specific. She is so pleased to see you. You get to work.`,
  13: (s) => `${s.name} has arranged everything in advance. She gives you a route with the efficiency of someone who has thought about this and determined the optimal solution. You climb her — fold by fold up the warm vast mass of her body, the enormous belly below you, the wide soft slope of her sides — and settle onto the great shelf of her chest. She checks something off a mental list. "Good," she says. "Let's be efficient about this." You get to work.`,
  14: (s) => `${s.name} laughs the whole time you're climbing. "I still can't believe this is my life," she says, warmly, not complaining — more like marveling. You haul yourself up the warm soft mass of her enormous body, fold by fold, the vast belly below you warm as sunlight, and settle onto the great shelf of her chest. She's still smiling. "Back home," she says, "I used to think 'I want to be part of somewhere.' And now look." She hands you the first course. You get to work.`,
  default: (s) => `You come to her — she hasn't been able to come to you for a while. You climb the warm vast geography of her body, hand over hand through the soft rolls, the enormous belly below you, the wide shelf of her hips. You settle atop the great warm plateau of her chest, eye level with her face. She looks at you with the calm of someone completely at home in what she is. You get to work.`,
};

export const INIT_STUDENTS = [
  { id:0,  name:"Brittany", archetype:"cheerleader",  role:"Cheer Captain",       age:19, bodyType:"pear",      lbs:118, startLbs:118, desc:"Squad captain, tight ponytail, commands the room with a look.",         favFood:"protein shakes", hobby:"cheerleading",  personality:"commanding",  relationship:20, triggeredEvents:[], mood:"happy" },
  { id:1,  name:"Madeline", archetype:"bookworm",     role:"Sociology PhD",       age:20, bodyType:"straight",  lbs:125, startLbs:125, desc:"Lanky, cardigans, glasses perpetually sliding.",                       favFood:"granola bars",   hobby:"research",      personality:"analytical",  relationship:20, triggeredEvents:[], mood:"focused" },
  { id:2,  name:"Kylie",    archetype:"influencer",   role:"Content Creator",      age:18, bodyType:"hourglass", lbs:122, startLbs:122, desc:"Perfectly contoured, phone always raised, brand in every gesture.",     favFood:"acai bowls",     hobby:"content",       personality:"confident",   relationship:20, triggeredEvents:[], mood:"excited" },
  { id:3,  name:"Serena",   archetype:"athlete",      role:"Track Sprinter",       age:21, bodyType:"athletic",  lbs:145, startLbs:145, desc:"Compact and muscled, always in compression gear, restless energy.",     favFood:"pasta",          hobby:"track",         personality:"competitive", relationship:20, triggeredEvents:[], mood:"focused" },
  { id:4,  name:"Fiona",    archetype:"artsy",        role:"Fine Art Major",       age:22, bodyType:"straight",  lbs:115, startLbs:115, desc:"Flowy linen, paint under nails, mismatched earrings.",                 favFood:"cheese boards",  hobby:"painting",      personality:"dreamy",      relationship:20, triggeredEvents:[], mood:"content" },
  { id:5,  name:"Destiny",  archetype:"gamer",        role:"Pro Streamer",         age:19, bodyType:"apple",     lbs:155, startLbs:155, desc:"Oversized hoodie, headphones around neck, always on her phone.",       favFood:"ramen",          hobby:"gaming",        personality:"dry",         relationship:20, triggeredEvents:[], mood:"tired" },
  { id:6,  name:"Tiffany",  archetype:"sorority",     role:"Chapter President",    age:20, bodyType:"hourglass", lbs:128, startLbs:128, desc:"Pastel everything, perfect blowout, Greek letters on tote.",           favFood:"rosé and brie",  hobby:"events",        personality:"social",      relationship:20, triggeredEvents:[], mood:"happy" },
  { id:7,  name:"Priya",    archetype:"overachiever", role:"Triple Major",         age:21, bodyType:"straight",  lbs:120, startLbs:120, desc:"Planner out, colour-coded highlighters, three laptops open.",         favFood:"anything fast",  hobby:"studying",      personality:"driven",      relationship:20, triggeredEvents:[], mood:"stressed" },
  { id:8,  name:"Maya",     archetype:"quiet",        role:"Studio Art Minor",     age:18, bodyType:"pear",      lbs:130, startLbs:130, desc:"Oversized sweater, back row, notebook full of careful drawings.",      favFood:"pastries",       hobby:"journaling",    personality:"observant",   relationship:20, triggeredEvents:[], mood:"content" },
  { id:9,  name:"Chloe",    archetype:"transfer",     role:"Exchange Student",     age:20, bodyType:"apple",     lbs:135, startLbs:135, desc:"On exchange from Dublin, here for one year. Has already discovered the dining hall and has thoughts about American portions — specifically that they're excessive, and that she wants more.",     favFood:"anything American she hasn't tried yet",    hobby:"eating her way through the campus map",     personality:"dry",     relationship:20, triggeredEvents:[], mood:"bemused" },
  { id:10, name:"Reneé",    archetype:"culinary",     role:"Culinary Arts Junior",  age:20, bodyType:"rotund",    lbs:148, startLbs:148, desc:"Always has flour somewhere on her and something to taste. She talks about food the way other people talk about music.",       favFood:"whatever she's been testing", hobby:"cooking",     personality:"sensory",    relationship:20, triggeredEvents:[], mood:"focused" },
  { id:11, name:"Kaylee",   archetype:"nursing",      role:"Nursing Student",      age:21, bodyType:"fertility_goddess", lbs:132, startLbs:132, desc:"Third-year nursing student, warm and attentive, the one who asks how you're doing and means it.", favFood:"comfort food",   hobby:"caregiving",    personality:"nurturing",   relationship:20, triggeredEvents:[], mood:"warm" },
  { id:12, name:"Nadia",    archetype:"psych",         role:"Psychology PhD",       age:22, bodyType:"voluptuous", lbs:117, startLbs:117, desc:"PhD track, notebook always open, the one who watches from the back of the room — not shy, evaluating.", favFood:"black coffee and whatever's in front of her", hobby:"people-watching", personality:"clinical", relationship:20, triggeredEvents:[], mood:"observant" },
  { id:13, name:"Daisy",    archetype:"eced",          role:"Student Teacher",      age:21, bodyType:"mom_bod",   lbs:138, startLbs:138, desc:"Always has snacks in her bag and treats everyone like they need looking after. Warm, practical, somehow always smells like cookies.", favFood:"home-cooked comfort food", hobby:"baking", personality:"nurturing",  relationship:20, triggeredEvents:[], mood:"warm" },
  { id:14, name:"Mary Jane", archetype:"farm_girl",    role:"Agriculture Student",  age:20, bodyType:"hourglass", lbs:125, startLbs:125, desc:"Junior ag major from down south. Big smile, bigger chest, and she brought six kinds of homemade jam to the first day of class.", favFood:"sweet potato pie", hobby:"cooking", personality:"sunny", relationship:20, triggeredEvents:[], mood:"cheerful" },
  { id:15, name:"Lilith",   archetype:"predator",     role:"???",                  age:20, bodyType:"hourglass",  lbs:80,  startLbs:80,  desc:"She appeared at the start of semester and hasn't been to a single class you can confirm. Dark clothes, the kind of stillness that isn't shyness.", favFood:"???", hobby:"???", personality:"predatory", relationship:0, triggeredEvents:[], mood:"content", hidden:true },
  { id:16, name:"Sophia",   archetype:"pharmacy_grad", role:"Pharmacy Grad Student", age:23, bodyType:"pear",      lbs:122, startLbs:122, desc:"Sharp, anxious, lab coat always pressed. Hair tied back, calculations double-checked. She talks about wellness research the way other people talk about salvation.", favFood:"meal replacement bars", hobby:"formulation", personality:"anxious", relationship:18, triggeredEvents:[], mood:"stressed", addictionLevel:0, hungerTier:0, weeksWithoutPlayerFeed:0 },
  { id:17, name:"Indiana Bones", archetype:"explorer", role:"Relic Hunter", age:22, bodyType:"straight", lbs:128, startLbs:128, desc:"Archaeology major with mud on her boots and a whip coiled in her backpack. She mapped this campus before the university admitted it existed — and she insists every hallway hides something worth digging up.", favFood:"trail mix and stolen dining hall rolls", hobby:"forbidden cartography", personality:"roguish", relationship:10, triggeredEvents:[], mood:"curious", hidden:true },
  { id:18, name:"Talia", archetype:"inventor", role:"Engineering Student", age:21, bodyType:"straight", lbs:118, startLbs:118, desc:"Hoodie under a lab coat, grease on her fingers, eyes that measure everything. She talks about bodies the way other people talk about circuit diagrams — inputs, outputs, optimization problems waiting to be solved.", favFood:"meal replacement paste", hobby:"prototyping", personality:"clinical", relationship:18, triggeredEvents:[], mood:"focused" },
];

export { initDeviceState } from './talia.js';
export { initPsychState } from './psychState.js';
