// ═══════════════════════════════════════════════════════════════
// SCENES BARREL — imports every scene file so the full module
// registry is populated. Used by scripts/textLint.mjs and the
// DebugPanel sweeps. Game code should keep importing scene files
// individually (smaller graphs); add every NEW scene file here.
// ═══════════════════════════════════════════════════════════════
import '../modules.js';
import '../lexicon/index.js';
import './attitude.js';
import './campusExplorationText.js';
import './campusDevice/index.js';
import './campusSoftening.js';
import './destinyOffstream.js';
import './diary.js';
import './diaryPhaseD.js';
import './diaryBase.js';
// import './evolvedDiary.js'; — removed Phase A; diary.js is single source
import './hiveIntake.js';
import './hungerArchetypeBehavior.js';
import './hungerInterrupt/index.js';
import './hungerInterruptPersonal.js';
import './hungerLexicon.js';
import './stream.js';
import './streamChatIngest.js';
import './streamExtended.js';
import './streamPreStream/index.js';
import './streamPreStreamBrand.js';
import './talkCodas.js';
import './talkEncourage.js';
import './talkCheckIn.js';
import './talkCompliment.js';
import './talkSuggest.js';
import './talkRefusal.js';
import './talkCommandFinish.js';
import './intimacy/index.js';
import './body/index.js';
import './session/index.js';
import './oppositionSalonGallery.js';
import './opposition/aibHearing.js';
import './opposition/agendaFire.js';
import './opposition/counterOutcome.js';
import './opposition/weighInMandatory.js';
import './supernatural/ascension.js';
import './supernatural/thinVoice.js';
import './supernatural/refeedSurge.js';
import './supernatural/scarcityCurse.js';
import './jealousyReaction.js';
import './feedVoice/index.js';
import './cultivator/index.js';
import './hunt/index.js';
import './campusEvent/index.js';
import './deviceFlavor.js';
import './opposition/endgameBeat.js';
import './dinner/index.js';
import './growthEvent/index.js';
import './weeklyEvent/index.js';
import './weighIn/index.js';
import './deviceBody.js';
import './deviceTick/index.js';
import './suddenGrowth/index.js';
import './talia/index.js';
import './eating/index.js';
import './clothing/index.js';
import './campus/index.js';
import './immobility/index.js';
import './psychShift/index.js';
import './interior/index.js';
import './npcReactions.js';
import './earlyGain/index.js';
import './forceFeeder/index.js';
import './squadStageCoverage.js';
import './squadKeyedDepth.js';
import '../modules.js';
