// The Squad — Lead: A4 Architect | Support: A5 Editor
// Auto-generated — run: node scripts/generateMonolithFragmentDepth.mjs
// Wildcard depth for anonymous decomposed monolith _N.fM fragment pools.
// Remaining monolith fragments.
import { registerModuleVariants } from '../engine.js';

registerModuleVariants("_143.f0", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_143.f1", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_144.f0", [{ when: {}, weight: 3, text: ["Warmth and weight settle between you — unhurried, present, real.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_144.f1", [{ when: {}, weight: 3, text: ["Soft flesh yields; she exhales, pleased and patient.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_144.f2", [{ when: {}, weight: 3, text: ["Warmth and weight settle between you — unhurried, present, real.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_145.f0", [{ when: {}, weight: 3, text: ["Warmth and weight settle between you — unhurried, present, real.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_145.f1", [{ when: {}, weight: 3, text: ["Warmth and weight settle between you — unhurried, present, real.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_146.f0", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_146.f1", [{ when: {}, weight: 3, text: ["The moment deepens; neither of you suggests stopping.", "Warmth and weight settle between you — unhurried, present, real."] }]);
registerModuleVariants("_147.f0", [{ when: {}, weight: 3, text: ["Warmth and weight settle between you — unhurried, present, real.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_147.f1", [{ when: {}, weight: 3, text: ["Warmth and weight settle between you — unhurried, present, real.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_148.f0", [{ when: {}, weight: 3, text: ["Soft flesh yields; she exhales, pleased and patient.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_148.f1", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_149.f0", [{ when: {}, weight: 3, text: ["Warmth and weight settle between you — unhurried, present, real.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_149.f1", [{ when: {}, weight: 3, text: ["Soft flesh yields; she exhales, pleased and patient.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_150.f0", [{ when: {}, weight: 3, text: ["Warmth and weight settle between you — unhurried, present, real.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_150.f1", [{ when: {}, weight: 3, text: ["Warmth and weight settle between you — unhurried, present, real.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_151.f0", [{ when: {}, weight: 3, text: ["The moment deepens; neither of you suggests stopping.", "Warmth and weight settle between you — unhurried, present, real."] }]);
registerModuleVariants("_151.f1", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_152.f0", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_152.f1", [{ when: {}, weight: 3, text: ["The moment deepens; neither of you suggests stopping.", "Warmth and weight settle between you — unhurried, present, real."] }]);
registerModuleVariants("_153.f0", [{ when: {}, weight: 3, text: ["She stays where she is — vast, warm, willing to be felt.", "The moment deepens; neither of you suggests stopping."] }]);
registerModuleVariants("_153.f1", [{ when: {}, weight: 3, text: ["The moment deepens; neither of you suggests stopping.", "Warmth and weight settle between you — unhurried, present, real."] }]);
registerModuleVariants("_153.f2", [{ when: {}, weight: 3, text: ["Warmth and weight settle between you — unhurried, present, real.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_154.f0", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_154.f1", [{ when: {}, weight: 3, text: ["She stays where she is — vast, warm, willing to be felt.", "The moment deepens; neither of you suggests stopping."] }]);
registerModuleVariants("_155.f0", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_155.f1", [{ when: {}, weight: 3, text: ["She stays where she is — vast, warm, willing to be felt.", "The moment deepens; neither of you suggests stopping."] }]);
registerModuleVariants("_156.f0", [{ when: {}, weight: 3, text: ["Warmth and weight settle between you — unhurried, present, real.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_156.f1", [{ when: {}, weight: 3, text: ["Soft flesh yields; she exhales, pleased and patient.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_156.f2", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_157.f0", [{ when: {}, weight: 3, text: ["Soft flesh yields; she exhales, pleased and patient.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_157.f1", [{ when: {}, weight: 3, text: ["The moment deepens; neither of you suggests stopping.", "Warmth and weight settle between you — unhurried, present, real."] }]);
registerModuleVariants("_158.f0", [{ when: {}, weight: 3, text: ["She stays where she is — vast, warm, willing to be felt.", "The moment deepens; neither of you suggests stopping."] }]);
registerModuleVariants("_158.f1", [{ when: {}, weight: 3, text: ["Soft flesh yields; she exhales, pleased and patient.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_159.f0", [{ when: {}, weight: 3, text: ["Soft flesh yields; she exhales, pleased and patient.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_159.f1", [{ when: {}, weight: 3, text: ["The moment deepens; neither of you suggests stopping.", "Warmth and weight settle between you — unhurried, present, real."] }]);
registerModuleVariants("_159.f2", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_160.f0", [{ when: {}, weight: 3, text: ["The moment deepens; neither of you suggests stopping.", "Warmth and weight settle between you — unhurried, present, real."] }]);
registerModuleVariants("_160.f1", [{ when: {}, weight: 3, text: ["Soft flesh yields; she exhales, pleased and patient.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_160.f2", [{ when: {}, weight: 3, text: ["She stays where she is — vast, warm, willing to be felt.", "The moment deepens; neither of you suggests stopping."] }]);
registerModuleVariants("_161.f0", [{ when: {}, weight: 3, text: ["Soft flesh yields; she exhales, pleased and patient.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_161.f1", [{ when: {}, weight: 3, text: ["She stays where she is — vast, warm, willing to be felt.", "The moment deepens; neither of you suggests stopping."] }]);
registerModuleVariants("_162.f0", [{ when: {}, weight: 3, text: ["She stays where she is — vast, warm, willing to be felt.", "The moment deepens; neither of you suggests stopping."] }]);
registerModuleVariants("_162.f1", [{ when: {}, weight: 3, text: ["Soft flesh yields; she exhales, pleased and patient.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_162.f2", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_163.f0", [{ when: {}, weight: 3, text: ["She stays where she is — vast, warm, willing to be felt.", "The moment deepens; neither of you suggests stopping."] }]);
registerModuleVariants("_163.f1", [{ when: {}, weight: 3, text: ["Warmth and weight settle between you — unhurried, present, real.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_164.f0", [{ when: {}, weight: 3, text: ["She stays where she is — vast, warm, willing to be felt.", "The moment deepens; neither of you suggests stopping."] }]);
registerModuleVariants("_164.f1", [{ when: {}, weight: 3, text: ["Warmth and weight settle between you — unhurried, present, real.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_165.f0", [{ when: {}, weight: 3, text: ["The moment deepens; neither of you suggests stopping.", "Warmth and weight settle between you — unhurried, present, real."] }]);
registerModuleVariants("_165.f1", [{ when: {}, weight: 3, text: ["Warmth and weight settle between you — unhurried, present, real.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_166.f0", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_166.f1", [{ when: {}, weight: 3, text: ["The moment deepens; neither of you suggests stopping.", "Warmth and weight settle between you — unhurried, present, real."] }]);
registerModuleVariants("_167.f0", [{ when: {}, weight: 3, text: ["The moment deepens; neither of you suggests stopping.", "Warmth and weight settle between you — unhurried, present, real."] }]);
registerModuleVariants("_167.f1", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_168.f0", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_168.f1", [{ when: {}, weight: 3, text: ["Contact sharpens by degrees until want is the only language left.", "She stays where she is — vast, warm, willing to be felt."] }]);
registerModuleVariants("_168.f2", [{ when: {}, weight: 3, text: ["Soft flesh yields; she exhales, pleased and patient.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_169.f0", [{ when: {}, weight: 3, text: ["Numbers climb; fabric strains where softness insists.", "She breathes through the reading — pleased, present, unashamed."] }]);
registerModuleVariants("_169.f1", [{ when: {}, weight: 3, text: ["The scale groans softly as weight settles across the platform.", "Numbers climb; fabric strains where softness insists."] }]);
registerModuleVariants("_170.f0", [{ when: {}, weight: 3, text: ["Soft flesh yields; she exhales, pleased and patient.", "Contact sharpens by degrees until want is the only language left."] }]);
registerModuleVariants("_170.f1", [{ when: {}, weight: 3, text: ["The moment deepens; neither of you suggests stopping.", "Warmth and weight settle between you — unhurried, present, real."] }]);
