// The Squad — Lead: A4 Architect | Support: A5 Editor
// Auto-generated — run: node scripts/generateNamedPoolDepth.mjs
// Wildcard depth for named thin pools (echo, dream, ritual, v2.depth, emb, etc.).
import { registerModuleVariants } from '../engine.js';

registerModuleVariants("bodyType.desc", [{ when: {}, weight: 3, text: ["{word.movement}", "{word.size}"] }]);
registerModuleVariants("clothing.desc", [{ when: {}, weight: 3, text: ["{word.garment.top}", "{word.garment.waist}"] }]);
registerModuleVariants("opposition.aib.unlocked", [{ when: {}, weight: 3, text: ["Institutional teeth find language for appetite — folders thick, concern performed.", "Vance taps once. Cooperation expected. Your hall feels the room lean."] }]);
registerModuleVariants("opposition.aib.open", [{ when: {}, weight: 3, text: ["Vance taps once. Cooperation expected. Your hall feels the room lean.", "Garden candles outside; dinner smells inside. Restraint flickers, appetite wins."] }]);
registerModuleVariants("opposition.proxy.ascetic_circle", [{ when: {}, weight: 3, text: ["Garden candles outside; dinner smells inside. Restraint flickers, appetite wins."] }]);
registerModuleVariants("supernatural.act.open", [{ when: {}, weight: 3, text: ["Runes glow. Scarcity arrives wearing wellness language like a crown.", "Skin too tight on memory-mass. Luminous hunger beneath, honest and enormous."] }]);
registerModuleVariants("supernatural.thinReveal", [{ when: {}, weight: 3, text: ["The hollow act flickers — famine language failing against real appetite.", "Skin too tight on memory-mass. Luminous hunger beneath, honest and enormous."] }]);
registerModuleVariants("cultivator.digest.enormous.latePlus3", [{ when: {}, weight: 3, text: ["Digestion settles. Kitchen still functions around her permanent presence."] }]);
registerModuleVariants("cultivator.digest.colossal.latePlus3", [{ when: {}, weight: 3, text: ["Integration complete. Reneé reviews data from within her immensity — calm, correct."] }]);
registerModuleVariants("scrutiny.tierUp.body._d45", [{ when: {}, weight: 3, text: ["Institutional attention sharpens. Growth has paperwork now.", "Tier rises. The body on record grows harder to explain away."] }]);
registerModuleVariants("emb.action.raid_pantry", [{ when: {}, weight: 3, text: ["Fullness gathers while shame schedules a late arrival.", "Crumbs, wrappers, evidence. The body keeps score warmly."] }]);
registerModuleVariants("emb.action.secret_binge", [{ when: {}, weight: 3, text: ["She eats standing, sitting, publicly — appetite honest in every register.", "Hunger steered from within. She obeys and calls it craving."] }]);
registerModuleVariants("emb.action.seduce_appetite", [{ when: {}, weight: 3, text: ["Fullness gathers while shame schedules a late arrival."] }]);
registerModuleVariants("emb.action.mirror_confession", [{ when: {}, weight: 3, text: ["She eats standing, sitting, publicly — appetite honest in every register."] }]);
registerModuleVariants("emb.action.text_ra", [{ when: {}, weight: 3, text: ["She eats standing, sitting, publicly — appetite honest in every register."] }]);
registerModuleVariants("emb.action.roommate_tempt", [{ when: {}, weight: 3, text: ["Fullness gathers while shame schedules a late arrival."] }]);
registerModuleVariants("emb.action.public_eating", [{ when: {}, weight: 3, text: ["Crumbs, wrappers, evidence. The body keeps score warmly."] }]);
registerModuleVariants("ritual.generic.depth", [{ when: {}, weight: 3, text: ["Courses stack like architecture. The hall eats with ceremonial hunger."] }]);
registerModuleVariants("ritual.communion_snack", [{ when: {}, weight: 3, text: ["The ritual lingers after plates empty — butter, surrender, resonance pleased.", "Shared plate, shared heat — intimacy measured in bites."] }]);
registerModuleVariants("ritual.communion_snack.beat", [{ when: {}, weight: 3, text: ["Courses stack like architecture. The hall eats with ceremonial hunger."] }]);
registerModuleVariants("ritual.communion_snack.after", [{ when: {}, weight: 3, text: ["The ritual lingers after plates empty — butter, surrender, resonance pleased."] }]);
registerModuleVariants("ritual.hall_banquet", [{ when: {}, weight: 3, text: ["The ritual lingers after plates empty — butter, surrender, resonance pleased."] }]);
registerModuleVariants("ritual.leviathan_vigil", [{ when: {}, weight: 3, text: ["Courses stack like architecture. The hall eats with ceremonial hunger."] }]);
registerModuleVariants("ritual.generic", [{ when: {}, weight: 3, text: ["Shared plate, shared heat — intimacy measured in bites."] }]);
registerModuleVariants("echo.type.stage_up.depth", [{ when: {}, weight: 3, text: ["Fabric surrendered. Appetite did not. The echo preserves both."] }]);
registerModuleVariants("echo.type.weigh_in.depth", [{ when: {}, weight: 3, text: ["Immobile and content — vastness settled, food brought to her."] }]);
registerModuleVariants("echo.type.dinner_unbutton.depth", [{ when: {}, weight: 3, text: ["She crossed a threshold the room still feels when you revisit it."] }]);
registerModuleVariants("echo.type.immobility.depth", [{ when: {}, weight: 3, text: ["She crossed a threshold the room still feels when you revisit it."] }]);
registerModuleVariants("echo.type.corruption_tier.depth", [{ when: {}, weight: 3, text: ["The moment returns warmer — appetite sharper, body more present than memory promised."] }]);
registerModuleVariants("echo.type.evolution.depth", [{ when: {}, weight: 3, text: ["She crossed a threshold the room still feels when you revisit it."] }]);
registerModuleVariants("echo.type.weigh_in", [{ when: {}, weight: 3, text: ["Want reorganized around yes. Hunger spoke without filter."] }]);
registerModuleVariants("echo.type.stage_up", [{ when: {}, weight: 3, text: ["Evolution caught mid-breath — form chosen, appetite amplified."] }]);
registerModuleVariants("echo.type.immobility", [{ when: {}, weight: 3, text: ["Digits climbed. She watched without flinching. Growth acknowledged."] }]);
registerModuleVariants("echo.replay", [{ when: {}, weight: 3, text: ["Memory-flesh yields under attention. Each revisit adds sensory proof.", "You return to the moment. Her belly still sways in archive-physics."] }]);
registerModuleVariants("dream.floating_cake.depth", [{ when: {}, weight: 3, text: ["She eats in the dream because the dream insists. Fullness follows."] }]);
registerModuleVariants("dream.feast_hall.depth", [{ when: {}, weight: 3, text: ["Sleep opens appetite's country — symbolic, generous, impossible to map awake."] }]);
registerModuleVariants("dream.honey_river.depth", [{ when: {}, weight: 3, text: ["Dream logic: portions without ceiling, warmth without apology."] }]);
registerModuleVariants("dream.mirror_feast.depth", [{ when: {}, weight: 3, text: ["Torches, courses, belly as throne — honored, fed, impossible to ignore."] }]);
registerModuleVariants("dream.gravity_well.depth", [{ when: {}, weight: 3, text: ["She wakes humming — hands to belly before eyes open."] }]);
registerModuleVariants("dream.leviathan_dream.depth", [{ when: {}, weight: 3, text: ["Reflection eats with her. Fullness doubles across glass."] }]);
registerModuleVariants("dream.wake.depth", [{ when: {}, weight: 3, text: ["Sweetness coats want. Permission tastes like honey and distance."] }]);
registerModuleVariants("dream.endless_buffet", [{ when: {}, weight: 3, text: ["Sleep opens appetite's country — symbolic, generous, impossible to map awake."] }]);
registerModuleVariants("dream.floating_cake", [{ when: {}, weight: 3, text: ["Mountain-dream: sauce-rivers, landscape appetite, mutual consumption."] }]);
registerModuleVariants("dream.feast_hall", [{ when: {}, weight: 3, text: ["Food orbits mass. Mouth opens; orbit decays into warmth."] }]);
registerModuleVariants("dream.honey_river", [{ when: {}, weight: 3, text: ["Mountain-dream: sauce-rivers, landscape appetite, mutual consumption."] }]);
registerModuleVariants("dream.mirror_feast", [{ when: {}, weight: 3, text: ["She wakes humming — hands to belly before eyes open."] }]);
registerModuleVariants("dream.gravity_well", [{ when: {}, weight: 3, text: ["Food orbits mass. Mouth opens; orbit decays into warmth."] }]);
registerModuleVariants("dream.leviathan_dream", [{ when: {}, weight: 3, text: ["Reflection eats with her. Fullness doubles across glass."] }]);
registerModuleVariants("clothing.v2.depth", [{ when: {}, weight: 3, text: ["Campus air tastes of butter, permission, consequence deferred."] }]);
registerModuleVariants("memory.v2.depth", [{ when: {}, weight: 3, text: ["Institutional eyes narrow; plates stay generous anyway.", "Growth reads in posture, fabric, the room learning her shape."] }]);
registerModuleVariants("origin.v2.depth", [{ when: {}, weight: 3, text: ["Before cameras: mirror, outfit, appetite rehearsed in private."] }]);
registerModuleVariants("ascension.v2.depth", [{ when: {}, weight: 3, text: ["Appetite deepens the scene by degrees. Neither of you rushes."] }]);
registerModuleVariants("forceFeed.v2.depth", [{ when: {}, weight: 3, text: ["Institutional eyes narrow; plates stay generous anyway.", "Growth reads in posture, fabric, the room learning her shape."] }]);
registerModuleVariants("feedVoice.v2.depth", [{ when: {}, weight: 3, text: ["Hunger has a voice now. It sounds like belonging."] }]);
registerModuleVariants("cultivator.v2.depth", [{ when: {}, weight: 3, text: ["Technology meets flesh — remote warmth, unintended discovery.", "Campus air tastes of butter, permission, consequence deferred."] }]);
registerModuleVariants("roster.v2.depth", [{ when: {}, weight: 3, text: ["Growth reads in posture, fabric, the room learning her shape.", "Warmth and weight settle — unhurried, present, sensually real."] }]);
registerModuleVariants("scrutiny.v2.depth", [{ when: {}, weight: 3, text: ["Growth reads in posture, fabric, the room learning her shape.", "Warmth and weight settle — unhurried, present, sensually real."] }]);
registerModuleVariants("discontent.v2.depth", [{ when: {}, weight: 3, text: ["Growth reads in posture, fabric, the room learning her shape.", "Warmth and weight settle — unhurried, present, sensually real."] }]);
registerModuleVariants("campusNav.v2.depth", [{ when: {}, weight: 3, text: ["Appetite deepens the scene by degrees. Neither of you rushes.", "Before cameras: mirror, outfit, appetite rehearsed in private."] }]);
registerModuleVariants("earlyGain.v2.depth", [{ when: {}, weight: 3, text: ["Hunger has a voice now. It sounds like belonging."] }]);
registerModuleVariants("gossip.v2.depth", [{ when: {}, weight: 3, text: ["Growth reads in posture, fabric, the room learning her shape.", "Warmth and weight settle — unhurried, present, sensually real."] }]);
registerModuleVariants("campusDevice.v2.depth", [{ when: {}, weight: 3, text: ["Institutional eyes narrow; plates stay generous anyway.", "Growth reads in posture, fabric, the room learning her shape."] }]);
registerModuleVariants("campusSecret.v2.depth", [{ when: {}, weight: 3, text: ["Campus air tastes of butter, permission, consequence deferred.", "Hunger has a voice now. It sounds like belonging."] }]);
registerModuleVariants("journal.v2.depth", [{ when: {}, weight: 3, text: ["Before cameras: mirror, outfit, appetite rehearsed in private.", "History sits in belly and memory — meals crossed like thresholds."] }]);
registerModuleVariants("streamPre.v2.depth", [{ when: {}, weight: 3, text: ["Technology meets flesh — remote warmth, unintended discovery.", "Campus air tastes of butter, permission, consequence deferred."] }]);
