// The Squad — Lead: A4 Architect | Phase B.2 keyed persona depth
// Auto-generated — run: node scripts/generateKeyedDepth.mjs
// Adds supplemental lines to keyed cells under the ≥3-text volume floor.
import { registerModuleVariants } from '../engine.js';

registerModuleVariants('immob.settledState', [{ when: {"studentId":5,"stageMin":10,"stageMax":10}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":10,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":14,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":0,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":1,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":2,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":3,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":4,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":6,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":7,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":8,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":9,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":11,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":12,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":13,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":15,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":16,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":17,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.spaceObs', [{ when: {"studentId":3,"stageMin":11}, weight: 4, text: ["The room holds her."] }]);
registerModuleVariants('immob.spaceObs', [{ when: {"studentId":7,"stageMin":11}, weight: 4, text: ["The room holds her."] }]);
registerModuleVariants('immob.attempt', [{ when: {"stageMin":10}, text: ["A transfer attempt — assisted, incremental, honest about the physics."] }]);
registerModuleVariants('immob.attempt', [{ when: {"stageMin":11}, text: ["She considers movement — a shift, not a journey."] }]);
registerModuleVariants('immob.assistance', [{ when: {"stageMin":10}, text: ["Mass settles where she puts it."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":0,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":1,"stageMin":11,"corruption":[1]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":2,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":3,"stageMin":11,"corruption":[1]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":4,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":5,"stageMin":11,"corruption":[0]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":6,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":7,"stageMin":11,"corruption":[0]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":8,"stageMin":11,"corruption":[1]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":9,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":10,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":11,"stageMin":11,"corruption":[1]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":12,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":13,"stageMin":11,"corruption":[1]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":14,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":15,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":16,"stageMin":11,"corruption":[0]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":17,"stageMin":11,"corruption":[1]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"corruption":[0]}, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"corruption":[1]}, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"stageMin":11}, weight: 2, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.hint.food', [{ when: {"courtHintTier":[1]}, text: ["\"Bring me what I actually want,\" she says, not unkindly. \"You know what that is.\""] }]);
registerModuleVariants('immob.hint.food', [{ when: {"courtHintTier":[2]}, text: ["She eyes what you brought and mentions, lightly, that she'd prefer something different next time."] }]);
registerModuleVariants('immob.hint.food', [{ when: {"courtHintTier":[3]}, text: ["She eyes what you brought and mentions, lightly, that she'd prefer something different next time."] }]);
registerModuleVariants('immob.pref.food', [{ when: {"courtBoonTier":["early"]}, text: ["She eats like someone whose preference was finally honored — unhurried, thorough, pleased."] }]);
registerModuleVariants('immob.arrival.devotion', [{ when: {"corruption":[2]}, weight: 2, text: ["{subject.name} settles under your care, warm and vast and wholly content to be exactly where she is.","{subject.name} closes her eyes into the care and does not hurry to open them."] }]);
registerModuleVariants('immob.arrival.devotion', [{ when: {"studentId":0,"stageMin":10}, weight: 4, text: ["{subject.name} settles under your care, warm and vast and wholly content to be exactly where she is.","{subject.name} closes her eyes into the care and does not hurry to open them."] }]);
registerModuleVariants('immob.arrival.devotion', [{ when: {"studentId":10,"stageMin":10}, weight: 4, text: ["{subject.name} settles under your care, warm and vast and wholly content to be exactly where she is.","{subject.name} closes her eyes into the care and does not hurry to open them."] }]);
registerModuleVariants('immob.arrival.devotion', [{ when: {"studentId":8,"stageMin":10}, weight: 4, text: ["{subject.name} settles under your care, warm and vast and wholly content to be exactly where she is."] }]);
registerModuleVariants('immob.arrival.devotion', [{ when: {"studentId":12,"stageMin":10}, weight: 4, text: ["{subject.name} settles under your care, warm and vast and wholly content to be exactly where she is."] }]);
registerModuleVariants('immob.arrival.devotion', [{ when: {"studentId":5,"stageMin":10}, weight: 4, text: ["{subject.name} settles under your care, warm and vast and wholly content to be exactly where she is."] }]);
registerModuleVariants('immob.arrival.devotion', [{ when: {"studentId":14,"stageMin":10}, weight: 4, text: ["{subject.name} settles under your care, warm and vast and wholly content to be exactly where she is."] }]);
registerModuleVariants('shift.denial', [{ when: {"corruption":[2]}, text: ["\"It's fine,\" she says — meaning temporary. She hopes."] }]);
registerModuleVariants('shift.coda', [{ when: {"corruption":[1]}, text: ["Destiny is already thinking about the next meal. The week rolls forward."] }]);
registerModuleVariants('shift.coda', [{ when: {"corruption":[2]}, text: ["Destiny is already thinking about the next meal. The week rolls forward."] }]);
registerModuleVariants('shift.scene', [{ when: {"lastCorruptionShift":true}, text: ["The old story loosens at the edges."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"studentId":12,"corruption":[1],"stageMin":4}, weight: 4, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"corruption":[0],"stageMax":2}, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"corruption":[0],"stageMin":2,"stageMax":3,"gainStance":"opposed"}, weight: 2, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"corruption":[0],"stageMin":2,"stageMax":3,"gainStance":"reluctant"}, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"corruption":[0],"stageMin":2,"stageMax":3,"gainStance":"secret"}, weight: 2, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"corruption":[0],"stageMin":2,"stageMax":3,"gainStance":"neutral"}, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"stageMin":3,"corruption":[0]}, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"stageMin":5,"corruption":[1]}, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"stageMin":7}, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"corruption":[2],"stageMin":4}, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"fixationTierMin":1,"stageMin":2}, weight: 2, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"fixationTierMin":2,"stageMin":3}, weight: 3, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"fixationTierMin":3,"stageMin":3}, weight: 4, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"obsessionTierMin":1,"stageMin":3}, weight: 2, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"obsessionTierMin":2,"stageMin":4}, weight: 3, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"shameTierMin":1,"corruption":[0],"stageMin":2}, weight: 2, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"shameTierMin":2,"corruption":[0],"stageMin":3}, weight: 3, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"dependenceTierMin":1,"corruption":[1],"stageMin":3}, weight: 2, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"dependenceTierMin":2,"stageMin":4}, weight: 3, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"studentId":3,"stageMin":6,"corruption":[0]}, weight: 4, text: ["Tiffany realizes your gaze caught the squeeze past the booth. She does not mind."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"studentId":6,"stageMin":5,"relationship":[2,3]}, weight: 4, text: ["Serena hears the chair complain and files it under adaptation, not defeat."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"studentId":9,"stageMin":7}, weight: 4, text: ["Serena hears the chair complain and files it under adaptation, not defeat."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"studentId":11,"stageMin":6,"corruption":[1]}, weight: 4, text: ["Serena hears the chair complain and files it under adaptation, not defeat."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"studentId":17,"stageMin":8}, weight: 4, text: ["Serena hears the chair complain and files it under adaptation, not defeat."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"stageMin":8}, text: ["Serena hears the chair complain and files it under adaptation, not defeat."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"relationship":[0,1],"stageMin":6}, text: ["Serena hears the chair complain and files it under adaptation, not defeat.","The desk arm marks her hip. Evidence of a new training load."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"relationship":[2,3],"stageMin":6}, text: ["Serena hears the chair complain and files it under adaptation, not defeat.","The desk arm marks her hip. Evidence of a new training load."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"stageMin":10}, text: ["Serena hears the chair complain and files it under adaptation, not defeat."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"studentId":2,"corruption":[2],"stageMin":5}, weight: 4, text: ["Tiffany treats every pound like a rush vote — passed, celebrated, seconded."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"studentId":6,"corruption":[2],"stageMin":6}, weight: 4, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"studentId":13,"corruption":[1],"stageMin":5}, weight: 4, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"studentId":14,"corruption":[2],"stageMin":7}, weight: 4, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"corruption":[2],"stageMin":6}, weight: 2, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"corruption":[2],"stageMin":10}, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"obsessionTierMin":1,"corruption":[1,2],"stageMin":4}, weight: 2, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"obsessionTierMin":2,"corruption":[1,2],"stageMin":5}, weight: 3, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"obsessionTierMin":3,"stageMin":5}, weight: 4, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"fixationTierMin":1,"corruption":[1,2],"stageMin":3}, weight: 2, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"fixationTierMin":2,"stageMin":4}, weight: 3, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"dependenceTierMin":1,"corruption":[1,2],"stageMin":4}, weight: 2, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"dependenceTierMin":2,"stageMin":5}, weight: 3, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
