// The Squad — Lead: A4 Architect | Phase B.2 keyed persona depth
// Auto-generated — run: node scripts/generateKeyedDepth.mjs
// Adds supplemental lines to keyed cells under the ≥3-text volume floor.
import { registerModuleVariants } from '../engine.js';

registerModuleVariants('campus.location', [{ when: {"nodeId":"quad"}, text: ["The campus hums with its usual foot traffic and appetite."] }]);
registerModuleVariants('campus.location', [{ when: {"nodeId":"library"}, text: ["The campus hums with its usual foot traffic and appetite."] }]);
registerModuleVariants('campus.location', [{ when: {"nodeId":"dining_hall"}, text: ["The campus hums with its usual foot traffic and appetite."] }]);
registerModuleVariants('campus.location', [{ when: {"nodeId":"gym"}, text: ["The campus hums with its usual foot traffic and appetite."] }]);
registerModuleVariants('campus.location', [{ when: {"nodeId":"garden"}, text: ["The campus hums with its usual foot traffic and appetite."] }]);
registerModuleVariants('campus.find', [{ when: {"campusTierMin":3}, text: ["You pocket foraged campus herbs — mint, berries, something worth carrying."] }]);
registerModuleVariants('campus.dev.vulnerability', [{ when: {"archetype":"cheerleader"}, text: ["crossing your line of sight"] }]);
registerModuleVariants('campus.dev.vulnerability', [{ when: {"archetype":"bookworm"}, text: ["crossing your line of sight"] }]);
registerModuleVariants('campus.dev.vulnerability', [{ when: {"archetype":"influencer"}, text: ["crossing your line of sight"] }]);
registerModuleVariants('campus.dev.vulnerability', [{ when: {"archetype":"athlete"}, text: ["crossing your line of sight"] }]);
registerModuleVariants('campus.dev.vulnerability', [{ when: {"targetType":"npc","role":"faculty"}, text: ["crossing your line of sight"] }]);
registerModuleVariants('campus.dev.vulnerability', [{ when: {"targetType":"npc","role":"staff"}, text: ["crossing your line of sight"] }]);
registerModuleVariants('campus.dev.vulnerability', [{ when: {"targetType":"npc"}, text: ["crossing your line of sight"] }]);
registerModuleVariants('campus.dev.reaction', [{ when: {"deviceId":"endless_hunger_engine","modeId":"sustain"}, text: ["The gain is already showing."] }]);
registerModuleVariants('campus.dev.reaction', [{ when: {"deviceId":"endless_hunger_engine"}, text: ["The gain is already showing."] }]);
registerModuleVariants('campus.dev.reaction', [{ when: {"deviceId":"feeding_mask","modeId":"capture"}, text: ["The gain is already showing."] }]);
registerModuleVariants('campus.dev.reaction', [{ when: {"deviceId":"feeding_mask","deviceDependenceTierMin":1}, text: ["The gain is already showing."] }]);
registerModuleVariants('slender.bodyNotice', [{ when: {"isGaining":true,"stageMax":3}, weight: 2, text: ["still slender in the doorway"] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":5,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Okay.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":8,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":13,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":17,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":0,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":2,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":3,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":4,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":6,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":7,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":9,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":10,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":11,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":12,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":14,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":15,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"studentId":16,"gainStance":"neutral","corruption":[0],"stageMax":4}, weight: 4, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.neutral', [{ when: {"gainStance":"neutral","stageMax":2}, text: ["\"Cool. Next.\""] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":2,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She traces the new curve like she is studying brushwork."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":4,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":10,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":12,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":14,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":1,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":3,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":6,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":7,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":8,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":9,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":11,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":13,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":16,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":17,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":0,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"studentId":5,"gainStance":"secret","corruption":[0],"stageMax":4}, weight: 4, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"gainStance":"secret","hungerTierMin":2}, weight: 2, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.secret', [{ when: {"gainStance":"secret","isGaining":true}, text: ["She checks the angle in the mirror and does not look away fast enough."] }]);
registerModuleVariants('slender.mirror', [{ when: {"gainStance":"opposed","stageMin":2,"stageMax":4}, weight: 2, text: ["She catches her reflection and pauses a beat longer than necessary."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":0,"corruption":[0],"stageMax":3}, weight: 4, text: ["Madeline annotates the meal in her head between bites. The plate empties anyway."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":1,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":2,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":3,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":4,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":5,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":6,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":7,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":8,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":9,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":10,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":11,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":12,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":13,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":14,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":15,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":16,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"studentId":17,"corruption":[0],"stageMax":3}, weight: 4, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('slender.eatPause', [{ when: {"gainStance":"neutral","stageMax":3}, text: ["Brittany eats like fueling — portioned, committed, already thinking about the next plate."] }]);
registerModuleVariants('eat.settleIn', [{ when: {"stageMin":4}, text: ["{subject.name} takes her seat and orients toward the food without preamble."] }]);
registerModuleVariants('eat.settleIn', [{ when: {"stageMin":7}, text: ["{subject.name} takes her seat and orients toward the food without preamble."] }]);
registerModuleVariants('eat.settleIn', [{ when: {"stageMin":10}, weight: 2, text: ["{subject.name} takes her seat and orients toward the food without preamble."] }]);
registerModuleVariants('eat.settleIn', [{ when: {"campusLocale":"cafeteria"}, text: ["{subject.name} takes her seat and orients toward the food without preamble."] }]);
registerModuleVariants('eat.settleIn', [{ when: {"campusLocale":"dorm_room"}, text: ["{subject.name} takes her seat and orients toward the food without preamble."] }]);
registerModuleVariants('eat.settleIn', [{ when: {"mealContext":"binge"}, weight: 2, text: ["{subject.name} takes her seat and orients toward the food without preamble."] }]);
registerModuleVariants('eat.firstBite', [{ when: {"hungerTierMin":2}, weight: 2, text: ["Brittany logs the first bite like data — portion, macro, intention. Then she takes it."] }]);
registerModuleVariants('eat.firstBite', [{ when: {"hungerTierMin":3}, weight: 3, text: ["Brittany logs the first bite like data — portion, macro, intention. Then she takes it."] }]);
registerModuleVariants('eat.firstBite', [{ when: {"corruption":[0],"stageMin":2}, text: ["Brittany logs the first bite like data — portion, macro, intention. Then she takes it."] }]);
registerModuleVariants('eat.firstBite', [{ when: {"corruption":[0],"stageMax":3,"gainStance":"reluctant"}, weight: 2, text: ["Brittany logs the first bite like data — portion, macro, intention. Then she takes it."] }]);
registerModuleVariants('eat.firstBite', [{ when: {"corruption":[0],"stageMax":3,"gainStance":"neutral"}, text: ["Brittany logs the first bite like data — portion, macro, intention. Then she takes it."] }]);
registerModuleVariants('eat.firstBite', [{ when: {"corruption":[1]}, text: ["Brittany logs the first bite like data — portion, macro, intention. Then she takes it."] }]);
registerModuleVariants('eat.firstBite', [{ when: {"corruption":[2]}, text: ["Brittany logs the first bite like data — portion, macro, intention. Then she takes it."] }]);
registerModuleVariants('eat.firstBite', [{ when: {"stageMin":6}, text: ["Brittany logs the first bite like data — portion, macro, intention. Then she takes it."] }]);
registerModuleVariants('eat.midMeal', [{ when: {"mealContext":"binge"}, weight: 2, text: ["Halfway through, the pace does not slow — if anything it steadies into purpose."] }]);
registerModuleVariants('eat.bitePace', [{ when: {"hungerTierMin":2}, text: ["steadily"] }]);
registerModuleVariants('eat.bitePace', [{ when: {"hungerTierMin":3}, weight: 2, text: ["steadily"] }]);
registerModuleVariants('eat.bitePace', [{ when: {"corruption":[0]}, text: ["steadily"] }]);
registerModuleVariants('eat.bitePace', [{ when: {"corruption":[2]}, text: ["steadily"] }]);
registerModuleVariants('eat.pacing', [{ when: {"hungerTierMin":3}, weight: 2, text: ["Each bite requires a small breath around fullness; she takes the breath and continues.","Hunger and fullness trade places; she keeps going."] }]);
registerModuleVariants('eat.pacing', [{ when: {"stageMin":7,"fullnessMin":0.6}, text: ["She eats {eat.bitePace} — the plate emptying faster than conversation could keep up.","Hunger and fullness trade places; she keeps going."] }]);
registerModuleVariants('eat.portionObs', [{ when: {"stageMin":0,"stageMax":4}, text: ["the plate thinning despite fullness already present"] }]);
registerModuleVariants('eat.portionObs', [{ when: {"fullnessMin":0.5}, text: ["portions disappearing with quiet efficiency"] }]);
registerModuleVariants('eat.portionObs', [{ when: {"stageMin":5}, text: ["portions disappearing with quiet efficiency"] }]);
registerModuleVariants('eat.portionObs', [{ when: {"mealContext":"binge"}, weight: 2, text: ["portions disappearing with quiet efficiency"] }]);
registerModuleVariants('eat.hungerClause', [{ when: {"hungerTierMin":2}, text: ["Hunger has been driving for an hour. The food is finally in range."] }]);
registerModuleVariants('eat.hungerClause', [{ when: {"hungerTierMin":3}, weight: 2, text: ["She was hungry before she sat down — the meal is overdue."] }]);
registerModuleVariants('eat.hungerClause', [{ when: {"inWithdrawal":true}, weight: 3, text: ["She was hungry before she sat down — the meal is overdue."] }]);
registerModuleVariants('eat.hungerClause', [{ when: {"addictionLevelMin":3}, weight: 2, text: ["She was hungry before she sat down — the meal is overdue."] }]);
registerModuleVariants('eat.bodyResponse', [{ when: {"bodyType":"apple","stageMin":4}, text: ["her middle softening visibly with each course","waistband working harder as the meal progresses"] }]);
registerModuleVariants('eat.bodyResponse', [{ when: {"bodyType":"pear","stageMin":4}, text: ["her middle softening visibly with each course","waistband working harder as the meal progresses"] }]);
registerModuleVariants('eat.bodyResponse', [{ when: {"fullnessMin":0.8}, text: ["her middle softening visibly with each course"] }]);
registerModuleVariants('eat.soundTex', [{ when: {"hungerTierMin":2}, text: ["the small sounds of urgent eating","plates scraping closer without being asked"] }]);
registerModuleVariants('eat.soundTex', [{ when: {"hungerTierMin":3}, weight: 2, text: ["fork moving faster than conversation"] }]);
registerModuleVariants('eat.soundTex', [{ when: {"stageMin":6}, text: ["fork moving faster than conversation"] }]);
registerModuleVariants('eat.aftermath', [{ when: {"corruption":[2],"fullnessMin":0.6}, text: ["She sits back, satisfied in the ordinary way."] }]);
registerModuleVariants('eat.aftermath', [{ when: {"stageMin":6,"fullnessMin":0.7}, text: ["She sits back, satisfied in the ordinary way."] }]);
registerModuleVariants('eat.aftermath', [{ when: {"stageMin":9}, text: ["She sits back, satisfied in the ordinary way."] }]);
registerModuleVariants('eat.aftermath', [{ when: {"hungerTierMin":3,"fullnessMin":0.5}, text: ["She sits back, satisfied in the ordinary way."] }]);
registerModuleVariants('eat.foodDesc', [{ when: {"mealContext":"breakfast"}, text: ["the meal"] }]);
registerModuleVariants('eat.foodDesc', [{ when: {"mealContext":"binge"}, text: ["the meal"] }]);
registerModuleVariants('eat.foodDesc', [{ when: {"mealContext":"snack"}, text: ["the meal"] }]);
registerModuleVariants('eat.foodDesc', [{ when: {"mealContext":"campus_meal"}, text: ["the meal"] }]);
registerModuleVariants('eat.aroma', [{ when: {"studentId":10}, weight: 3, text: ["heat and salt and the promise of more"] }]);
registerModuleVariants('eat.aroma', [{ when: {"mealContext":"binge"}, text: ["butter and garlic threading the air","something rich enough to make the room smaller"] }]);
registerModuleVariants('cloth.discovery', [{ when: {"clothingState":"button_pop"}, text: ["{subject.name} notices the strain before the failure — fabric honest about what comes next."] }]);
registerModuleVariants('cloth.discovery', [{ when: {"clothingState":"zipper_fail"}, text: ["{subject.name} notices the strain before the failure — fabric honest about what comes next."] }]);
registerModuleVariants('cloth.discovery', [{ when: {"clothingState":"seam_split"}, text: ["{subject.name} notices the strain before the failure — fabric honest about what comes next."] }]);
registerModuleVariants('cloth.discovery', [{ when: {"clothingState":"waistband_surrender"}, text: ["{subject.name} notices the strain before the failure — fabric honest about what comes next."] }]);
registerModuleVariants('cloth.discovery', [{ when: {"stageMin":6}, text: ["{subject.name} notices the strain before the failure — fabric honest about what comes next."] }]);
registerModuleVariants('cloth.discovery', [{ when: {"stageMin":10}, text: ["{subject.name} notices the strain before the failure — fabric honest about what comes next."] }]);
registerModuleVariants('cloth.struggleVerb', [{ when: {"stageMin":6}, text: ["tugs"] }]);
registerModuleVariants('cloth.struggleVerb', [{ when: {"bodyType":"apple","stageMin":4}, text: ["tugs","adjusts"] }]);
registerModuleVariants('cloth.struggleVerb', [{ when: {"bodyType":"pear","stageMin":4}, text: ["tugs","adjusts"] }]);
registerModuleVariants('cloth.struggle', [{ when: {"clothingState":"sleeve_restriction"}, text: ["She {cloth.struggleVerb} the fabric without success."] }]);
registerModuleVariants('cloth.struggle', [{ when: {"clothingState":"shirt_rise"}, text: ["She {cloth.struggleVerb} the fabric without success."] }]);
registerModuleVariants('cloth.struggle', [{ when: {"clothingState":"bra_protest"}, text: ["She {cloth.struggleVerb} the fabric without success."] }]);
registerModuleVariants('cloth.moment', [{ when: {"clothingState":"button_pop"}, weight: 2, text: ["The fabric gives — soft tok, thread surrendering."] }]);
registerModuleVariants('cloth.moment', [{ when: {"stageMin":6}, text: ["The fabric gives — soft tok, thread surrendering."] }]);
registerModuleVariants('cloth.failBeat', [{ when: {"corruption":[0]}, text: ["The outfit capitulates in a small, audible way."] }]);
registerModuleVariants('cloth.failBeat', [{ when: {"corruption":[2]}, text: ["The outfit capitulates in a small, audible way."] }]);
registerModuleVariants('cloth.failBeat', [{ when: {"stageMin":8}, text: ["The outfit capitulates in a small, audible way."] }]);
registerModuleVariants('cloth.failSound', [{ when: {"clothingState":"button_pop"}, text: ["a quiet rip along the seam"] }]);
registerModuleVariants('cloth.failSound', [{ when: {"clothingState":"seam_split"}, text: ["a soft tok against the floor"] }]);
registerModuleVariants('cloth.failSound', [{ when: {"clothingState":"zipper_fail"}, text: ["a soft tok against the floor"] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":0,"corruption":[0]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":0,"corruption":[2]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":2,"corruption":[0]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":2,"corruption":[2]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":3,"corruption":[0]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":3,"corruption":[1]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":5,"corruption":[0]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":5,"corruption":[2]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":6,"corruption":[1]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":7,"corruption":[0]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":8,"corruption":[0]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":9,"corruption":[2]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":10,"corruption":[1]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":11,"corruption":[0]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":12,"corruption":[2]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":13,"corruption":[1]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":14,"corruption":[2]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":15,"corruption":[2]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":16,"corruption":[0]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":17,"corruption":[1]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":1,"corruption":[0]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('cloth.reaction', [{ when: {"studentId":4,"corruption":[0]}, weight: 4, text: ["{subject.name} looks at the damage and exhales."] }]);
registerModuleVariants('campus.moveSentence', [{ when: {"stageMin":8}, weight: 2, text: ["{subject.name} {word.adv.pace|suffix: }{word.moveVerb.campus} {campus.destination}{word.adv.sizeQual|prefix: }."] }]);
registerModuleVariants('campus.moveSentence', [{ when: {"stageMin":10}, weight: 3, text: ["{subject.name} {word.adv.pace|suffix: }{word.moveVerb.campus} {campus.destination}{word.adv.sizeQual|prefix: }."] }]);
registerModuleVariants('campus.destination', [{ when: {"campusLocale":"elevator"}, text: ["down the hall"] }]);
registerModuleVariants('campus.destination', [{ when: {"campusLocale":"gym"}, text: ["down the hall"] }]);
registerModuleVariants('campus.obstacle', [{ when: {"studentId":0,"campusLocale":"gym","stageMin":6}, weight: 4, text: [" — phones lifting to film the squeeze past"] }]);
registerModuleVariants('campus.obstacle', [{ when: {"studentId":2,"campusLocale":"hallway","stageMin":5}, weight: 4, text: [" — equipment groaning under captain's weight"] }]);
registerModuleVariants('campus.obstacle', [{ when: {"studentId":15,"campusLocale":"hallway","stageMin":7}, weight: 4, text: [" — equipment groaning under captain's weight"] }]);
registerModuleVariants('campus.obstacle', [{ when: {"campusLocale":"hallway","stageMin":5}, text: [" — equipment groaning under captain's weight"] }]);
registerModuleVariants('campus.obstacle', [{ when: {"campusLocale":"lecture_hall","stageMin":4}, text: [" — equipment groaning under captain's weight"] }]);
registerModuleVariants('campus.obstacle', [{ when: {"campusLocale":"stairwell","stageMin":6}, text: [" — equipment groaning under captain's weight"] }]);
registerModuleVariants('campus.obstacle', [{ when: {"campusLocale":"elevator","stageMin":7}, text: [" — equipment groaning under captain's weight"] }]);
registerModuleVariants('campus.obstacle', [{ when: {"campusLocale":"cafeteria","stageMin":5}, text: [" — equipment groaning under captain's weight"] }]);
registerModuleVariants('campus.obstacle', [{ when: {"campusLocale":"gym","stageMin":3}, text: [" — equipment groaning under captain's weight"] }]);
registerModuleVariants('campus.obstacle', [{ when: {"stageMin":8}, weight: 2, text: [" — equipment groaning under captain's weight"] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"studentId":3,"campusLocale":"gym","stageMin":5,"stageMax":9}, weight: 4, text: ["Destiny's chair has learned her. The desk has not. She plays from the bed now."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"studentId":5,"campusLocale":"dorm_room","stageMin":5,"stageMax":9}, weight: 4, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"studentId":6,"campusLocale":"cafeteria","stageMin":5,"stageMax":9}, weight: 4, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"studentId":7,"campusLocale":"lecture_hall","stageMin":5,"stageMax":9}, weight: 4, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"studentId":8,"campusLocale":"hallway","stageMin":5,"stageMax":9}, weight: 4, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"studentId":9,"campusLocale":"cafeteria","stageMin":5,"stageMax":9}, weight: 4, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"studentId":10,"campusLocale":"cafeteria","stageMin":5,"stageMax":9}, weight: 4, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"studentId":11,"campusLocale":"stairwell","stageMin":5,"stageMax":9}, weight: 4, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"studentId":12,"campusLocale":"hallway","stageMin":5,"stageMax":9}, weight: 4, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"studentId":13,"campusLocale":"cafeteria","stageMin":5,"stageMax":9}, weight: 4, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"studentId":14,"campusLocale":"cafeteria","stageMin":5,"stageMax":9}, weight: 4, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"studentId":16,"campusLocale":"elevator","stageMin":5,"stageMax":9}, weight: 4, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"studentId":17,"campusLocale":"stairwell","stageMin":5,"stageMax":9}, weight: 4, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"campusLocale":"dorm_room","stageMin":5}, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"campusLocale":"lecture_hall","stageMin":7}, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.spaceObs', [{ when: {"stageMin":9}, text: ["Serena knows which machines still fit. The list shortens every month."] }]);
registerModuleVariants('campus.soundTex', [{ when: {"stageMin":5}, text: ["the floor registering her decision to move","furniture bracing in advance"] }]);
registerModuleVariants('campus.soundTex', [{ when: {"stageMin":7}, text: ["footfalls heavier than they used to be"] }]);
registerModuleVariants('campus.soundTex', [{ when: {"stageMin":9}, text: ["footfalls heavier than they used to be"] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":5,"stageMin":10,"stageMax":10}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":10,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":14,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":0,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":1,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":2,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":3,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":4,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":6,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":7,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":8,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":9,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":11,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":12,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":13,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":15,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":16,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.settledState', [{ when: {"studentId":17,"stageMin":11}, weight: 4, text: ["{subject.name} rests, vast and warm."] }]);
registerModuleVariants('immob.spaceObs', [{ when: {"studentId":3,"stageMin":11}, weight: 4, text: ["The room holds her."] }]);
registerModuleVariants('immob.spaceObs', [{ when: {"studentId":7,"stageMin":11}, weight: 4, text: ["The room holds her."] }]);
registerModuleVariants('immob.attempt', [{ when: {"stageMin":10}, text: ["A transfer attempt — assisted, incremental, honest about the physics."] }]);
registerModuleVariants('immob.attempt', [{ when: {"stageMin":11}, text: ["She considers movement — a shift, not a journey."] }]);
registerModuleVariants('immob.assistance', [{ when: {"stageMin":10}, text: ["Mass settles where she puts it."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":0,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":1,"stageMin":11,"corruption":[1]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":2,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":3,"stageMin":11,"corruption":[1]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":4,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":5,"stageMin":11,"corruption":[0]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":6,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":7,"stageMin":11,"corruption":[0]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":8,"stageMin":11,"corruption":[1]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":9,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":10,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":11,"stageMin":11,"corruption":[1]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":12,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":13,"stageMin":11,"corruption":[1]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":14,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":15,"stageMin":11,"corruption":[2]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":16,"stageMin":11,"corruption":[0]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"studentId":17,"stageMin":11,"corruption":[1]}, weight: 4, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"corruption":[0]}, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"corruption":[1]}, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.register', [{ when: {"stageMin":11}, weight: 2, text: ["She rests without commentary."] }]);
registerModuleVariants('immob.hint.food', [{ when: {"courtHintTier":[1]}, text: ["\"Bring me what I actually want,\" she says, not unkindly. \"You know what that is.\""] }]);
registerModuleVariants('immob.hint.food', [{ when: {"courtHintTier":[2]}, text: ["She eyes what you brought and mentions, lightly, that she'd prefer something different next time."] }]);
registerModuleVariants('immob.hint.food', [{ when: {"courtHintTier":[3]}, text: ["She eyes what you brought and mentions, lightly, that she'd prefer something different next time."] }]);
registerModuleVariants('immob.pref.food', [{ when: {"courtBoonTier":["early"]}, text: ["She eats like someone whose preference was finally honored — unhurried, thorough, pleased."] }]);
registerModuleVariants('immob.arrival.devotion', [{ when: {"corruption":[2]}, weight: 2, text: ["{subject.name} settles under your care, warm and vast and wholly content to be exactly where she is.","{subject.name} closes her eyes into the care and does not hurry to open them."] }]);
registerModuleVariants('immob.arrival.devotion', [{ when: {"studentId":0,"stageMin":10}, weight: 4, text: ["{subject.name} settles under your care, warm and vast and wholly content to be exactly where she is.","{subject.name} closes her eyes into the care and does not hurry to open them."] }]);
registerModuleVariants('immob.arrival.devotion', [{ when: {"studentId":10,"stageMin":10}, weight: 4, text: ["{subject.name} settles under your care, warm and vast and wholly content to be exactly where she is.","{subject.name} closes her eyes into the care and does not hurry to open them."] }]);
registerModuleVariants('immob.arrival.devotion', [{ when: {"studentId":8,"stageMin":10}, weight: 4, text: ["{subject.name} settles under your care, warm and vast and wholly content to be exactly where she is."] }]);
registerModuleVariants('immob.arrival.devotion', [{ when: {"studentId":12,"stageMin":10}, weight: 4, text: ["{subject.name} settles under your care, warm and vast and wholly content to be exactly where she is."] }]);
registerModuleVariants('immob.arrival.devotion', [{ when: {"studentId":5,"stageMin":10}, weight: 4, text: ["{subject.name} settles under your care, warm and vast and wholly content to be exactly where she is."] }]);
registerModuleVariants('immob.arrival.devotion', [{ when: {"studentId":14,"stageMin":10}, weight: 4, text: ["{subject.name} settles under your care, warm and vast and wholly content to be exactly where she is."] }]);
registerModuleVariants('shift.denial', [{ when: {"corruption":[2]}, text: ["\"It's fine,\" she says — meaning temporary. She hopes."] }]);
registerModuleVariants('shift.coda', [{ when: {"corruption":[1]}, text: ["Destiny is already thinking about the next meal. The week rolls forward."] }]);
registerModuleVariants('shift.coda', [{ when: {"corruption":[2]}, text: ["Destiny is already thinking about the next meal. The week rolls forward."] }]);
registerModuleVariants('shift.scene', [{ when: {"lastCorruptionShift":true}, text: ["The old story loosens at the edges."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"studentId":12,"corruption":[1],"stageMin":4}, weight: 4, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"corruption":[0],"stageMax":2}, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"corruption":[0],"stageMin":2,"stageMax":3,"gainStance":"opposed"}, weight: 2, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"corruption":[0],"stageMin":2,"stageMax":3,"gainStance":"reluctant"}, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"corruption":[0],"stageMin":2,"stageMax":3,"gainStance":"secret"}, weight: 2, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"corruption":[0],"stageMin":2,"stageMax":3,"gainStance":"neutral"}, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"stageMin":3,"corruption":[0]}, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"stageMin":5,"corruption":[1]}, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"stageMin":7}, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"corruption":[2],"stageMin":4}, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"fixationTierMin":1,"stageMin":2}, weight: 2, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"fixationTierMin":2,"stageMin":3}, weight: 3, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"fixationTierMin":3,"stageMin":3}, weight: 4, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"obsessionTierMin":1,"stageMin":3}, weight: 2, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"obsessionTierMin":2,"stageMin":4}, weight: 3, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"shameTierMin":1,"corruption":[0],"stageMin":2}, weight: 2, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"shameTierMin":2,"corruption":[0],"stageMin":3}, weight: 3, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"dependenceTierMin":1,"corruption":[1],"stageMin":3}, weight: 2, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.selfObs', [{ when: {"dependenceTierMin":2,"stageMin":4}, weight: 3, text: ["Brittany inventories softness like a stat line she has not named yet."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"studentId":3,"stageMin":6,"corruption":[0]}, weight: 4, text: ["Tiffany realizes your gaze caught the squeeze past the booth. She does not mind."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"studentId":6,"stageMin":5,"relationship":[2,3]}, weight: 4, text: ["Serena hears the chair complain and files it under adaptation, not defeat."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"studentId":9,"stageMin":7}, weight: 4, text: ["Serena hears the chair complain and files it under adaptation, not defeat."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"studentId":11,"stageMin":6,"corruption":[1]}, weight: 4, text: ["Serena hears the chair complain and files it under adaptation, not defeat."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"studentId":17,"stageMin":8}, weight: 4, text: ["Serena hears the chair complain and files it under adaptation, not defeat."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"stageMin":8}, text: ["Serena hears the chair complain and files it under adaptation, not defeat."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"relationship":[0,1],"stageMin":6}, text: ["Serena hears the chair complain and files it under adaptation, not defeat.","The desk arm marks her hip. Evidence of a new training load."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"relationship":[2,3],"stageMin":6}, text: ["Serena hears the chair complain and files it under adaptation, not defeat.","The desk arm marks her hip. Evidence of a new training load."] }]);
registerModuleVariants('interior.sizeRealize', [{ when: {"stageMin":10}, text: ["Serena hears the chair complain and files it under adaptation, not defeat."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"studentId":2,"corruption":[2],"stageMin":5}, weight: 4, text: ["Tiffany treats every pound like a rush vote — passed, celebrated, seconded."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"studentId":6,"corruption":[2],"stageMin":6}, weight: 4, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"studentId":13,"corruption":[1],"stageMin":5}, weight: 4, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"studentId":14,"corruption":[2],"stageMin":7}, weight: 4, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"corruption":[2],"stageMin":6}, weight: 2, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"corruption":[2],"stageMin":10}, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"obsessionTierMin":1,"corruption":[1,2],"stageMin":4}, weight: 2, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"obsessionTierMin":2,"corruption":[1,2],"stageMin":5}, weight: 3, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"obsessionTierMin":3,"stageMin":5}, weight: 4, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"fixationTierMin":1,"corruption":[1,2],"stageMin":3}, weight: 2, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"fixationTierMin":2,"stageMin":4}, weight: 3, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"dependenceTierMin":1,"corruption":[1,2],"stageMin":4}, weight: 2, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
registerModuleVariants('interior.gainPride', [{ when: {"dependenceTierMin":2,"stageMin":5}, weight: 3, text: ["Kylie likes the number climbing. The feed will too. She is ready for both."] }]);
