const BODY_DESCS = {
  pear: [
    // 0 — Slight
    `A wispy, angular frame — her face is sharp at the cheekbones and jaw, neck slender, collarbones pronounced and visible. Her arms are thin enough that the tendons show at the wrist. Her torso is flat, ribs faintly countable through thin fabric. Her hips are present but narrow, her thighs long and slim with a visible gap from ankle to pelvis. She moves quickly, effortlessly, taking up very little space.`,
    // 1 — Slim
    `A slender, easy frame — her face is smooth and lightly rounded at the cheeks, a neat jaw, clear neck. Her arms are slim with a little softness at the upper arm. Her torso is flat with just the gentlest suggestion of a belly when she sits. Hips flare slightly, thighs touch at the very top. She moves easily, clothes falling off her without effort.`,
    // 2 — Soft
    `Her face has filled out softly — fuller cheeks, a rounded jaw, the angular edges gone. Her neck is smooth and slightly thicker. Her arms have lost their boniness; the upper arms are soft and rounded. Her chest has quietly grown — her bra fits noticeably tighter, the cups fuller than they were — a subtle change that becomes obvious in fitted tops. Her torso shows a small, soft belly poking forward at the navel. The dramatic lower-body development is beginning: hips visibly wider, thighs pressing together from mid-thigh down, a noticeable curve at the seatline.`,
    // 3 — Chubby
    `Her face is noticeably rounder — full cheeks, a soft double chin forming when she looks down, her neck thicker and smooth. Her shoulders have softened; her upper arms are pillowy, dimpled at the elbow. Her bust has grown clearly larger, pulling at the necklines of her shirts, the soft weight of it resting heavier on her ribcage. Her belly rounds forward visibly below the navel, a soft apron forming. But the real story is her lower half: hips wide enough to brush doorframes, thighs thick and pressed together from hip to knee, her bottom full and heavy and pulling at waistbands. She's begun to move with the slight, shifting gait of someone with real weight between her thighs.`,
    // 4 — Plump
    `Her face is genuinely round and full — cheeks soft and prominent, a clear double chin now, her neck smooth and thick. Her shoulders round and padded; her arms heavy, the upper arms deeply soft and swinging when she moves. Her bust is very large now, heavy and full, pulling the front of her shirts downward, shaping everything she wears around it. Her belly hangs forward in a distinct apron, navel pointing slightly down. Below the waist she is striking: hips genuinely wide, thighs massive and round, their inner surfaces in continuous contact from groin to knee, the skin warm and dimpled. Sitting, her thighs spread wide and her bottom overflows a standard chair on both sides. Stairs are taken one at a time now.`,
    // 5 — Heavy
    `Her face is very full — soft round cheeks touching her shoulders when she turns, a full double chin that rests against her neck when she looks forward, small ears framed by softness. Her neck is thick and smooth, her shoulders wide and padded. Her upper arms are heavy, the flesh swinging freely, the crease at her elbow deep. Her bust is enormous and heavy, resting on the upper shelf of her belly when she sits, straining every button. Her belly hangs forward and down in a substantial apron, the lower roll resting on the tops of her thighs. Her lower body is overwhelming: hips enormously wide, her profile from behind defined by the vast sweep of her thighs and bottom, flesh overfilling every chair she attempts. Walking is a full-body event — a slow, rolling gait, her thighs displaced outward by each other's mass.`,
    // 6 — Fat
    `Her face is a soft, round abundance — full cheeks resting on her shoulders, layers of chin stacked smoothly, her eyes set deep in softness. Her neck has largely merged with her shoulders. Her arms hang at an angle from her sides, pushed outward by the mass of her torso; the upper arms are enormous bolsters of soft flesh, the elbows deeply dimpled. Her bust is tremendous — rolls above and below it, the weight of it pressing into the belly beneath. Her belly cascades forward in heavy overlapping rolls, the lowest apron hanging past her hips. Her lower body is extraordinary: hips that fill hallways, thighs that require a wide, rolling gait, the flesh of her inner thighs extending past her knees, her bottom an enormous soft shelf that dominates any surface she sits on, overflowing chairs generously.`,
    // 7 — Very Fat
    `Her face has become its own landscape — a soft, full moonface, cheeks wide and prominent, the chin a continuous smooth slope to her chest. Her neck is gone, replaced by the soft curve between face and shoulder. Her arms project nearly horizontally from her body, their lower surfaces deeply concave, the upper arms vast and swaying. Her bust is vast and immense, pressing outward against the rolls of her torso, functional but enormous. Her torso is immense: several heavy belly rolls, the apron hanging to mid-thigh when she stands. Her lower body is the dominant fact of her figure: hips that must turn sideways to clear doorframes, thighs that brush together continuously from waist to knee, the inner flesh extended further still, her seat a vast soft monument that requires custom furniture. Movement is deliberate, a wide rolling walk, each step placed with the care of significant mass.`,
    // 8 — Enormous
    `Her face is soft and vast — a wide moonface framed entirely by softness, the features gentle and small in their abundance of cheek and chin. Her shoulders are rounded mountains; her arms rest at steep angles from her sides and she cannot bring them together in front of her without effort. Her bust is a vast, heavy presence, its weight resting fully on the upper belly rolls beneath, the flesh of it spilling to either side. Her torso is an enormous soft landscape: the belly hanging in deep, heavy rolls, the lowest apron resting on her thighs even while she stands. Her lower half is staggering — hips that fill any standard doorway from side to side, thighs that require a wide stance simply to stand upright, her bottom an overwhelming shelf of soft flesh that no standard seating can accommodate. She moves with the careful, swaying momentum of someone managing enormous weight, each step deliberate, each surface chosen for what it can hold.`,
    // 9 — Immobile
    `Her face is a soft, vast terrain — wide and round, the features barely distinct from the surrounding softness, her chin a smooth cascade to her chest. Her upper body is immense: arms that can barely move, hands soft and dimpled. Her bust is part of the general mass of her torso now, enormous and heavy, layered with folds above and below, its weight pressing down into the great shelf of her belly. Her belly cascades in enormous, layered rolls, the lowest extending far in front of her, the flesh warm and deep and heavy. Her lower body is geography: hips that extend far beyond her shoulders when viewed from above, thighs of extraordinary circumference, each one a presence unto itself, their inner surfaces continuous from groin to knee and beyond. She is barely mobile — a shuffle of inches possible on good days, her enormous mass requiring assistance for anything beyond shifting position. She fills and overwhelms any furniture built to accommodate her.`,
    // 10 — Blob
    `Her face is a soft, warm island of expression in a vast sea of flesh — gentle features, full cheeks, a serene expression that floats above the enormity below. Her bust and belly and lower body have ceased to be distinct regions; she is a continuous expanse of layered, warm, soft flesh, the hip-heavy silhouette of her pear shape amplified to breathtaking extremes. The inner surfaces of her thighs press together for their full enormous length. Her bottom is an immovable monument of soft flesh. Her arms are largely embedded in the great soft mass of her sides. She is the largest thing in any room she occupies, her lower body alone filling the width of the reinforced furniture built for her. She does not move. She does not need to.`,
  ],
  hourglass: [
    // 0 — Slight
    `A fine, narrow frame — her face angular and precise, cheekbones prominent, jaw defined. Her neck is long and slender. Her shoulders are narrow, arms very thin, the muscle visible at the forearm. Her torso is almost flat with minimal chest; a small, distinct waist flares to narrow hips. Her legs are long, slim, and toned. She moves quickly and takes up very little space.`,
    // 1 — Slim
    `A neat, balanced figure — her face smooth and symmetrical, cheeks lightly rounded, a clean jaw. Her neck is slim. Shoulders trim, arms slender with a softness at the upper arm. Her waist nips in cleanly; her hips flare gently from it, creating the beginning of the classic curve. Her legs are toned and slim. She moves with natural ease.`,
    // 2 — Soft
    `Her face has filled out gently — cheeks softer, jaw line rounder, a hint of softness at the chin. Her neck is slightly fuller. Her bust has grown noticeably — the cups of her bras fill completely, the fabric of her shirts pulling across the chest — the hourglass shape asserting itself early and decisively. Her waist is still visible but has softened, losing its sharp definition. Her hips have widened further; her thighs are touching. A small, round belly has appeared between waist and hip. The curves are larger in every direction — she fills her clothes more completely.`,
    // 3 — Chubby
    `Her face is full and soft — round cheeks, a smooth jawline that has lost its angles, the beginning of a second chin when she looks down. Her neck is fuller. Her bust is large and heavy now, pulling at her necklines, the weight of it always present, shaping every shirt and jacket around itself. Below it, a definite belly rounds forward, softening the once-sharp waist. Her hips are strikingly wide, her thighs thick and in constant contact, her bottom full and round. The hourglass is still visible but has grown dramatically in every dimension. She moves with a gentle sway.`,
    // 4 — Plump
    `Her face is genuinely round — full, soft cheeks, a distinct double chin, her neck smooth and thick. Her bust is very large, heavy, shaping everything she wears — necklines gape, buttons strain, the weight of her chest pulls shirts forward. Her waist has largely disappeared, replaced by a round, prominent belly that protrudes forward and rests over her waistband. Her hips are very wide, her thighs massively thick and dimpled, pressing together from groin to knee, her bottom overflowing chairs. The hourglass shape is now an amplified, overwhelming version of itself — every curve at enormous scale. She walks with a visible waddle.`,
    // 5 — Heavy
    `Her face is full and soft, cheeks resting on her shoulders when she turns, a generous double chin, small ears set in softness. Her bust is enormous and heavy, resting on the upper swell of her belly when she stands, the weight of it requiring support that strains against it. Her waist is gone entirely; her torso is round and full from chest to hips. Her belly is a prominent, heavy globe hanging forward below the navel. Her hips are extraordinarily wide — the widest part of a very wide figure — her thighs vast and warm, her bottom an enormous soft presence that dominates everything she sits on. Despite the extreme curves she carries herself with a kind of authority.`,
    // 6 — Fat
    `Her face is a soft, round fullness — cheeks wide and prominent, chin resting on her chest, her profile almost circular. Her bust is tremendous, its weight pulling forward and downward, layered with rolls of soft flesh above and below, the sheer mass of it shaping her entire silhouette. Her belly is a heavy, round mass that hangs forward significantly, rolls visible above and below the navel. Her hips are staggering in their width — she turns sideways to navigate narrow spaces — her thighs enormous, dimpled, pressing together continuously, her bottom a vast soft shelf. The curves that defined her have been amplified to an extreme: enormous in every direction, overwhelming in every dimension.`,
    // 7 — Very Fat
    `Her face is vast and soft — a full, round moonface where the jaw, cheeks, and multiple chins merge into a warm, continuous softness. Her neck has disappeared into the mass of her shoulders and chest. Her bust is tremendous and heavy beyond ordinary description, pressing outward and downward, the flesh of it merging into the great rolls of her belly beneath. Below it her belly hangs in deep, heavy rolls. Her hips cannot be described in ordinary terms — they extend far beyond her shoulders in profile, requiring wide doorways and custom seating. Her thighs are enormous and constant in their contact; her bottom is a monument that overwhelms any surface it meets. She moves with the deliberate care of someone managing very great mass.`,
    // 8 — Enormous
    `Her face is a wide, soft moonface framed entirely by soft flesh, her features gentle and sweet. Her bust is an immense, heavy presence — the flesh of it vast and warm, spilling to either side when she reclines, pressing forward and down into the great rolls of her belly. Her torso is immense in every direction: bust, belly, rolls, the layered softness of a body that has expanded far beyond any standard frame. Her hips project far to either side; her arms hang at steep angles, pushed out by the mass of her sides. Her lower body is extraordinary: thighs of vast circumference, a bottom that requires specially reinforced seating, the flesh of her inner thighs hanging past her knees. She moves only slowly and with great deliberateness.`,
    // 9 — Immobile
    `Her face is a small, soft, serene island in the expanse of her upper body — cheeks wide, multiple chins cascading softly. Her bust is part of the great continuous landscape of her torso: enormous, heavy, resting fully on the shelf of her belly, the flesh of it pooling to the sides, indistinct now from the surrounding abundance. Her bust, belly, hips, and lower body have become a continuous, enormous landscape of soft flesh, rolls and folds layered upon each other, her sides extending far beyond any standard measurement. Her thighs are individually enormous; together they fill the width of a small sofa. The hourglass shape she once carried has become something vaster and more complete — every curve amplified to its most extreme expression. She does not move independently.`,
    // 10 — Blob
    `Her face is gentle and serene, floating above an incomprehensible abundance of warm, soft flesh. Her bust and belly and hips — the great curves that once defined her silhouette — have merged into one breathtaking, continuous mass that presses outward in every direction, filling the reinforced furniture built around her. The flesh of her inner thighs presses together for their full, extraordinary length. Her arms are largely immobile, embedded in the soft rolls of her sides. She is a vast, warm, permanent presence. Everything in the room is organized around what she has become. She is immobile, and overwhelming, and entirely herself.`,
  ],
  straight: [
    // 0 — Slight
    `An angular, spare frame — her face lean and angular, cheekbones and jaw prominent, the hollows of her temples visible. Her neck is long and thin. Her shoulders are narrow and bony; her arms are very thin, the wrists small. Her torso is flat in every direction — minimal chest, no visible waist curve, hip bones slightly prominent. Her legs are long and thin. She moves very easily.`,
    // 1 — Slim
    `A lean, straight figure — her face smooth and lightly defined, clean jaw, neat features. Her neck is slim. Her shoulders are narrow, arms slender. Her torso is flat from chest to hip with very little variation; the waist doesn't nip in. Legs are lean and straight. She moves with easy efficiency.`,
    // 2 — Soft
    `Her face has softened — cheeks rounder, jaw less defined, the early suggestion of a chin. Her neck is slightly fuller. Her upper arms have lost their leanness and developed a gentle softness. Her chest has filled out noticeably — her bras are tighter, the fabric straining across newly full cups. Her belly has appeared: a small, round pouch pushing forward below the navel, visible through fitted shirts. Her hips and thighs have rounded only slightly — the softening is even across her whole body, no dramatic curves, just a uniform gentle rounding everywhere.`,
    // 3 — Chubby
    `Her face is noticeably fuller — round cheeks, the jaw softened, a second chin forming when she looks down. Her neck is thick and smooth. Her upper arms are padded and soft, the flesh spilling slightly over elbow joints. Her bust has grown significantly — full and heavy, pulling at necklines and adding real weight to her chest. Her torso has rounded everywhere: a definite belly pushing forward and down, a rounded back. Her hips are wider but remain relatively balanced with her upper body. Her thighs have thickened, pressing together from mid-thigh. The softening is still relatively even — she is round all over rather than dramatically bottom or top heavy.`,
    // 4 — Plump
    `Her face is very full — prominent round cheeks, a clear double chin, her neck smooth and wide. Her arms are heavy, the upper arms soft and swinging slightly. Her bust is large and heavy, shaping the front of her shirts, its weight a constant physical presence. Her belly is the dominant feature of her torso now: a round, prominent globe hanging forward and down, rolls visible above and below the navel. Her hips have widened proportionally; her thighs are thick and touch continuously. She is full and round in every direction, the weight distributed evenly across her entire body. She breathes more heavily climbing stairs.`,
    // 5 — Heavy
    `Her face is round and full, the cheeks wide and soft, multiple chins visible, her neck smooth and thick. Her shoulders have rounded and padded. Her arms hang with significant mass, the upper arms large soft cylinders, the forearms thick. Her bust is very large, its weight resting on the upper belly, heavy and full. Her belly hangs forward heavily in a prominent apron, rolls stacked above it. Her hips are wide; her thighs thick and constantly in contact; her bottom heavy and round. The weight is remarkably even — no dominant feature, just a large, full, round body in every measurement. She walks with a slow, deliberate gait.`,
    // 6 — Fat
    `Her face is a soft, full moonface — round cheeks sitting high, multiple chins, her neck all but absorbed into her shoulders. Her arms are large and hang at an angle, the upper arms enormous and swinging. Her bust is large and heavy, part of the vast, even roundness of her torso — chest, belly, and back all at significant scale, the belly hanging in heavy rolls. Her hips and thighs and bottom match the upper body in scale, the full-body evenness maintained. She is large and round and soft in every direction, filling chairs, doorframes, and rooms without any single point of dramatic emphasis. Just everywhere.`,
    // 7 — Very Fat
    `Her face has become a vast, soft roundness — a moonface where the jaw and cheeks and chins form one continuous gentle curve. She moves very slowly, her arms barely able to hang at her sides, the rolls of her torso displacing them outward. Her bust is large and heavy, pressing forward into the rolls of her belly. Her belly hangs in deep, heavy folds. Her back is as round as her front. Her hips and thighs and bottom are enormous and match the scale of her upper body. She fills doorways and requires custom furniture. Every movement is effortful.`,
    // 8 — Enormous
    `She is an enormous, round presence. Her face is small and sweet at the center of a vast, soft head. Her arms project at extreme angles, mostly decorative now. Her bust is vast and heavy, its weight indistinct from the immense round mass of her torso — front, sides, and back all equally vast — with the belly hanging far in front of her and the back equally full. Her lower body matches completely: thighs of great circumference, a bottom that overflows the largest furniture. She fills the largest chairs and extends beyond them. Movement requires care and assistance.`,
    // 9 — Immobile
    `Her face is soft and small and visible at the summit of an enormous, even, continuous softness that fills the room. Her bust is part of the great round mass of her torso, heavy and vast, resting on the belly beneath it, the flesh rolling outward to either side. Her upper and lower body have lost their distinction, merging into one immense whole — an even, spherical abundance of warm flesh in every direction. Her thighs press together for their full vast length. Her belly hangs in deep, heavy rolls. The room has been organized around her, and she fills it completely. She does not move independently.`,
    // 10 — Blob
    `Her face is serene and small at the summit of what she has become — a breathtaking, still, enormous presence. Her bust and belly and back and hips are one continuous, immense roundness of layered soft flesh, the even distribution of her body type amplified to its absolute extreme. She presses outward in every direction with equal, overwhelming completeness. Her thighs are individually vast; together they fill the span of reinforced furniture built specifically for her. She is the heaviest, most evenly distributed thing in any room she occupies. Everything else adjusts around her.`,
  ],
  apple: [
    // 0 — Slight
    `A very slim figure that leans toward the torso: her face is lean and precise, cheekbones prominent, jaw clean. Her neck is slender. Her shoulders are narrow; arms thin. Her torso is flat with a very slight tendency to carry weight through the midsection, not yet visible but structurally present. Her hips are narrow, legs long and slim. She moves quickly and very lightly.`,
    // 1 — Slim
    `A slender, neatly proportioned figure — her face clean-lined and smooth, a well-defined jaw. Her neck is slim. Her torso is trim with a very gentle forward suggestion at the belly that would only be noticed on close inspection. Her hips are relatively narrow compared to her torso. Legs are slim and long. She moves easily and quickly.`,
    // 2 — Soft
    `Her face has rounded out at the cheeks; her jaw is softer. Her neck has filled slightly. Her torso shows its apple nature: a round, soft belly is forming decisively — the midsection is where weight goes first and most noticeably. It presses forward below the navel and softens the waistline entirely. Her chest has filled out more than her hips have — the bust growing rounder and fuller, a subtle change relative to the belly's more dramatic expansion. Her arms have softened at the upper arm. Her hips and thighs remain relatively slim by comparison — the contrast is becoming noticeable.`,
    // 3 — Chubby
    `Her face is full and round — cheeks prominent, jaw soft, the beginning of a double chin. Her neck is thick and smooth. Her belly is the defining feature: round and forward, hanging over the waistband, the navel shifting downward. She carries the bulk of her weight here — her torso is significantly rounder than her lower half. Her bust has grown — full and round, sitting above the belly — though it is the belly that commands the eye. Her arms are thickening quickly: upper arms soft and padded. Her hips and thighs are modest by comparison, giving her a distinctive round-bellied, full-armed silhouette.`,
    // 4 — Plump
    `Her face is very round and full — a soft, wide face, clear double chin, smooth thick neck. Her arms are heavily padded, upper arms large and soft. Her bust has grown large — full and heavy — though it is the torso below it that is the primary event: a massive, heavy belly that hangs forward in a prominent apron, resting below the navel, pulling at every waistband. Her back is correspondingly round. Her lower half — hips, thighs, bottom — is significantly slimmer than her upper body, giving her a distinctive front-heavy appearance. Breathing is audible after any exertion.`,
    // 5 — Heavy
    `Her face is full and soft, multiple chins, her neck absorbed into her shoulders. Her arms are enormous — the upper arms are large bolsters of soft flesh, the forearms thick. Her bust is large and heavy, pressing forward above the vast belly, though the belly overwhelms it in scale. Her belly is the axis of her body: an enormous, heavy mass that hangs far forward and down, the lowest apron resting on the tops of her thighs when she sits. Her sides are deep; her back is round and full. Her lower half remains significantly smaller — the contrast between the enormous belly and the relatively modest hips and thighs is striking. She walks with a forward lean to balance the mass in front.`,
    // 6 — Fat
    `Her face is a soft, round fullness — moonface features, chin resting on her chest. Her arms hang at steep angles, displaced by the mass of her torso. Her bust is large and heavy, sitting above the enormous belly, the two together forming the staggering forward mass of her silhouette. Her belly is extraordinary: an enormous, hanging mass that extends far in front of her, rolls deep and heavy, the lowest apron hanging to mid-thigh. Her chest and belly and back are all immense. Her lower half, while significantly grown, remains clearly smaller than the torso — the apple shape is dramatically amplified. She walks with the slow, careful gait of someone managing a very heavy front.`,
    // 7 — Very Fat
    `Her face is soft and round, barely visible above the mass of her upper body. Her bust presses forward above the vast landscape of her belly — large and heavy in its own right, though dwarfed by the belly beneath it. She can see almost nothing of her lower half over that belly. The belly is the primary physical fact of her existence: vast, heavy, hanging in deep rolls, extending far in front and to the sides. Her arms are large but functionally mostly immobile, embedded in the rolls of her sides. Her lower body has grown but remains less vast than the enormous torso. Movement is slow and requires considerable effort and planning.`,
    // 8 — Enormous
    `She is defined by her belly. It is the largest thing in the room. Her face is small and soft above the mass; her arms are barely functional. Her bust sits above the great forward expanse of her belly — enormous in absolute terms, a significant mass of warm soft flesh — but everything refers back to the belly as the dominant fact. The belly extends so far in front that she cannot see her feet, cannot reach past it, cannot easily navigate around it. The rest of her body — back, sides, lower half — are all very large, but everything refers back to the belly. She fills the largest available furniture and overflows it.`,
    // 9 — Immobile
    `Her face is a small, serene presence above the immense soft landscape of her body. Her bust is part of the great forward mass of her torso — large and heavy, pressing into the rolls above her belly, the flesh of it warm and abundant. Her belly is the room. It extends forward in enormous, layered rolls of warm soft flesh, each roll deep and heavy, the lowest apron resting far out in front of her. Her arms are embedded in the vast rolls of her sides. Her lower body is barely distinguishable from the general mass, her thighs and hips present but overwhelmed by the sheer forward dominance of her belly. She does not move. The room accommodates her.`,
    // 10 — Blob
    `Her face is gentle and present above the summit of an overwhelming, still presence organized around the enormous mass of her belly. Her bust presses forward into the great landscape of flesh — large and soft and warm — part of the continuous forward expanse that defines her. Her belly is an incomprehensible volume of warm, layered soft flesh, extending forward and to the sides, the lowest rolls reaching far out before her. Her arms are immobile, embedded. Her lower body is present but secondary — hips and thighs buried in the general enormity. She fills the room. The room fills around her. She is vast, and warm, and permanent.`,
  ],
  athletic: [
    // 0 — Slight
    `A compact, powerfully lean figure — her face is clean-featured and angular, jaw defined, cheekbones visible. Her neck is lean with visible muscle. Her shoulders are broad for her frame, narrow hips below. Her arms are lean and muscular — bicep and forearm clearly defined, no excess tissue. Her torso is flat and hard, the abdominals visible, minimal body fat. Her legs are long, powerful, and very lean — quadriceps and calves defined through the skin. She moves quickly and efficiently, every movement economical.`,
    // 1 — Slim
    `A lean, athletic build — her face clean and defined, strong jaw, clear features. Her neck is slim and muscular. Broad shoulders, arms with visible tone and muscle definition. Her torso is flat and firm. Her legs are strong and toned — the muscle definition of someone who trains regularly. She carries herself with the upright posture and fluid movement of an athlete.`,
    // 2 — Soft
    `Her face has softened slightly — the sharp definition of her cheekbones muted by a new roundness at the cheeks. Her neck is slightly thicker. Her shoulders are still broad and strong. Her arms have retained much of their muscle but a new softness has settled over it — the definition remains but is less sharp. Her chest has filled out with real new volume — the athletic frame carrying the new bust with surprising presence. Her belly has appeared: a firm, round softness pushing forward at the midsection where there was nothing before. Her thighs have thickened with the combination of muscle and new fat, pressed against each other at the top.`,
    // 3 — Chubby
    `Her face is visibly rounder — full cheeks, a softer jaw, the athletic sharpness replaced by a rounded warmth. Her neck is thick. Her shoulders remain broad and strong. Her arms are now a mix of muscle and soft tissue — the bicep still present under a layer of padding. Her bust has grown substantially — full and round, sitting high on the broad athletic chest — a real, heavy presence that pulls at her shirts. Her belly is definitively round and forward-hanging: a soft, heavy mound that sits below her ribcage, the muscle structure buried. Her thighs are thick and heavy, still powerful but soft, pressing together from the hip. Her bottom has grown substantially — round and prominent, straining fabric.`,
    // 4 — Plump
    `Her face is full and round — prominent cheeks, a double chin forming, her neck smooth and wide. Her shoulders are still broad, but the narrowness has gone; she is wide at the shoulder and continuing to widen below. Her arms are heavy — thick upper arms, the muscle buried under substantial padding. Her bust is large and heavy, the broad athletic frame carrying its weight solidly — a significant soft mass that shapes the front of everything she wears. Her belly hangs forward heavily, a full apron below the navel, the old abdominal definition entirely gone. Her thighs are massive — the athlete's quadriceps now deep under layers of soft, heavy flesh. Her bottom is enormous and round. She moves with the particular gait of someone both powerful and very heavy.`,
    // 5 — Heavy
    `Her face is soft and full — round cheeks, clear double chin, her neck thick and strong-looking. Her shoulders are very broad, her back wide. Her arms are large: the upper arms are very thick, soft-over-muscle, hanging with real weight. Her bust is very large — the heavy flesh of it resting on the upper belly when she stands, the weight of it shaping everything she wears. Her torso is enormously thick — the chest, belly, and back all substantial. The belly hangs forward in a prominent apron. Her lower half continues the theme: thighs of extraordinary thickness, her bottom enormous and dominant. The former athlete's frame carries this weight powerfully — there is still something powerful in the way she takes up space — but the power is now the power of mass.`,
    // 6 — Fat
    `Her face is a full, round softness — cheeks wide and prominent, multiple chins, her neck thick and short. The broad shoulders remain, giving her an imposing width. Her arms are very large — the upper arms enormous soft cylinders that swing when she moves. Her bust is enormous — a tremendous heavy mass resting on the great rolls of her belly, the flesh of it warm and abundant, spilling to the sides. Her torso is vast: deep chest, a huge belly hanging in rolls, a back equally round. Her thighs and bottom are tremendous — she takes up the space of two standard seats. She moves with a slow, rolling gait, her body a massive, warm presence.`,
    // 7 — Very Fat
    `Her face is soft and round, floating above the enormous mass of her upper body. Her shoulders — still broad — disappear into the rolls of her torso. Her arms are very large, barely mobile, hanging at steep angles. Her bust is immense — its weight pressing down into the deep belly rolls beneath it, the flesh vast and warm. Her belly hangs in deep, heavy rolls. Her thighs are individually enormous; together they require a very wide stance. Her bottom cannot be accommodated by standard furniture. She moves deliberately, slowly, with the careful authority of someone managing great mass.`,
    // 8 — Enormous
    `Her face is small and soft above the immensity of her body. Her shoulders and the width of her former athletic frame now form the foundation of something far greater — an enormous, wide, deep, heavy presence. Her bust is an immense, warm mass of soft flesh resting on the great belly rolls below, the weight of it vast and permanent. Her belly extends far in front of her. Her thighs are vast — the muscle of her athletic past buried deep under layers of heavy, soft flesh. Her arms are largely decorative, hanging at steep angles from her sides. She fills and overflows any standard chair. Movement requires planning and assistance.`,
    // 9 — Immobile
    `Her face is serene above the enormous expanse of her body — the breadth of her former athletic frame is now the breadth of something far greater. Her bust is part of the great mass of her torso: vast, heavy, its weight indistinct from the surrounding abundance of warm flesh. Her belly hangs in deep, heavy rolls, extending far in front of her, the lowest apron resting on the tops of her thighs. Her thighs are of extraordinary circumference, the muscle of her past buried under enormous layers of soft, heavy flesh. She does not move independently. Her body fills the room in the immediate, physical sense — wide shoulders to widest thighs, all of it dense and soft and overwhelming. The furniture was built for her.`,
    // 10 — Blob
    `Her face is gentle and present above what she has become. The body remembers the athlete in the way it holds the mass — the broad shoulders still form the widest part of her upper body, now buried in the rolls of an immense torso. Her bust and belly and thighs are a continuous, breathtaking expanse of heavy, warm, soft flesh. Her thighs alone are vast enough to fill the width of reinforced furniture. Her arms are embedded in the great soft mass of her sides. She is the heaviest, most permanent thing in the room — an enormous, still presence of layered flesh. Everything is organized around her.`,
  ],
};
