// Stage 0 entries
const UMBRAL_STAGE_0 = [
  // Target 0 — Slight (~80-120 lbs)
  (target, umbral) => `${umbral.name} turns toward the slight girl with the slow, unhurried attention of something predatory becoming aware of easy prey. The void that pools at her edges — still new, still surprising to her in how it obeys — reaches out without much direction, more instinct than intent. The girl, maybe ninety pounds, is facing the wrong direction when the darkness finds her. She doesn't even have time to look confused. The void simply takes her: a soft implosion, a brief absence where a small body used to be, and then nothing. ${umbral.name} inhales sharply. She wasn't expecting it to feel like that — a sudden warmth spreading deep through her enormous middle, then lower, then everywhere. Her belly surges outward in a long, slow throb, new blubber forcing itself forward under her palms as she presses both hands into the swelling flesh. A second throb piles more soft mass onto the first. A third. Her thighs press tighter together as fresh fat thickens them from the inside, the inner flesh warm and insistent against itself. The seam along the underside of her waistband pops with a sharp little crack. She looks down at ${Math.round(umbral.lbs).toLocaleString()} pounds of herself and takes a slow breath. "Oh," she says softly, to no one. "Oh, that's what that is."`,

  // Target 1 — Trim (~120-165 lbs)
  (target, umbral) => `${umbral.name}'s shadow reaches before she does — it has learned to hunt ahead of her, which still startles her a little, this new quality of darkness she carries. ${target.name} is slim and quick and she gets maybe two steps before the void closes around her ankles. She pulls hard, twists, tries to shake it loose with the desperate energy of a small animal that understands what catching means. ${umbral.name} extends one enormous arm almost lazily, the gesture halfway between a reach and a shrug. The void tightens. ${target.name} makes a sound — sharp, indignant — and then she is simply gone, pulled inward with a sound like a held breath released. ${umbral.name} stands very still for a moment. The warmth moves through her in rolling waves, deep and insistent, and new blubber surges outward in answer: her belly pushing forward against her clothing, the fabric pulling taut across fresh soft mass, a slow crawl of expansion that goes on longer than she expected. Her thighs thicken with new fat, the inner surfaces pressing warm and firm against each other. The rolls at her sides deepen as blubber piles onto blubber. A button on her waistband shears off and clatters across the floor. She watches it go. ${Math.round(umbral.lbs).toLocaleString()} pounds now, and still learning what that means.`,

  // Target 2 — Soft (~165-215 lbs)
  (target, umbral) => `There is a moment — she's noticed this, filed it away — where people sense the void before they see it. ${target.name} is soft-figured and slow to turn, but she turns at the right moment, sees the darkness gathering at ${umbral.name}'s edges, and backs up two steps with her hands raised. It is the right instinct and it does nothing. The void is already around her. ${umbral.name} feels the resistance when she draws the girl in: a satisfying push-back, like pulling something with real give to it. ${target.name} grabs the edge of a desk on her way past and the desk scrapes forward three inches before her grip fails. Then she is absorbed, and ${umbral.name} staggers slightly under the sudden weight of it. The warmth hits fast and hard. Her belly lurches outward — an inch, two, three — new blubber forcing its way forward in a sustained push that presses her waistband to its limit and past it. The fabric tears at the left hip with a clean ripping sound as a fresh roll of belly fat spills over the gap. Her thighs push against each other, new fat thickening them from hip to knee. Her lower back rounds as flesh piles onto flesh. She catches herself on the desk ${target.name} tried to hold and leans there for a moment, breathing, feeling the growth settle into her at ${Math.round(umbral.lbs).toLocaleString()} pounds. "Okay," she murmurs. "Okay. More than I thought."`,

  // Target 3 — Padded (~215-295 lbs)
  (target, umbral) => `${target.name} is a solid girl — clearly overweight, wide through the hips, her belly already round and prominent — and when she sees the void gathering around ${umbral.name} she doesn't freeze. She shoves. Both hands straight into the darkness, full weight behind it, trying to push the Umbral back through sheer mass. ${umbral.name} hasn't encountered this before. She braces, surprised, and the effort of holding her ground makes the void flicker. ${target.name} shoves again and takes half a step toward the door. Then ${umbral.name}'s hunger reasserts itself, all that cold appetite snapping back into focus, and the void surges. It takes ${target.name} mid-stride — she goes with both feet off the floor, arms still forward, still trying — and the absorption is rough and warm and longer than usual. ${umbral.name} lists to one side, grabs a desk for support. Her body expands dramatically, fast enough to feel: her belly shoves outward in a continuous heave of new blubber, fresh fat piling onto the existing rolls in waves, her sides rounding out as new flesh forces them wider. Her thighs are forced apart by the blubber thickening between them. Three seams blow simultaneously. Her shirt rides up past her navel, exposing a deep band of fresh, warm softness she can press her palm into. She presses her hand into it, fascinated despite herself. ${Math.round(umbral.lbs).toLocaleString()} pounds. She needed both hands to stay upright. That's new.`,

  // Target 4 — Heavy (~295-400 lbs)
  (target, umbral) => `${target.name} is genuinely heavy, wide and thick-limbed, and she fights back in a way that makes ${umbral.name} work for the first real time. The void reaches and ${target.name} pushes into it rather than away, trying to disrupt its center the way you'd fight a current — she's wrong about the physics, but the instinct is interesting. ${umbral.name} has to commit, has to draw on the hunger properly rather than letting it trickle forward on its own. The pull becomes a wrench. ${target.name} grabs a doorframe and gets both hands around it, her heels dug in, the fat of her arms shaking with the strain. The doorframe cracks. She holds on for a long, grunting, teeth-clenched moment. Then the void takes her all at once, frame-splinter and all, and the absorption hits ${umbral.name} like a fist. She sits down hard on the nearest surface. New blubber pours forward and outward in long rolling surges, roll by roll of soft flesh settling onto the existing mass, the fat of her belly advancing in a slow relentless tide. Her thighs spread wide across the seat as new fat fills them from within. Her clothing gives up in stages: the waistband first, then the back seam, then the shirt at the side. She sits in the wreckage of her outfit and breathes, feeling each new pound of blubber settle warm and heavy into place. ${Math.round(umbral.lbs).toLocaleString()} pounds. Heavy. That one left a mark.`,

  // Target 5 — Plump (~400-520 lbs)
  (target, umbral) => `${target.name} is enormous by ordinary standards — well over four hundred pounds, her belly a genuine apron, her thighs pressing together at every step — and when she sees the void she screams, a full-throated sound of genuine alarm, and turns and runs. Her run is a fast waddle, her whole body shaking with it, and she makes it twelve feet before the void outruns her. ${umbral.name} strains to hold it, the hunger still new enough that this much mass feels like hauling a tide. ${target.name} hits the edge of the void and digs in, heels skidding, belly shaking, using every ounce of her very considerable weight as an anchor. She is heavy enough that ${umbral.name} feels the resistance physically, like pulling against something moored. Then the void deepens and the grip releases and ${target.name} goes in with a great rushing sound. The growth that follows is violent in its speed: ${umbral.name}'s belly surges outward in long, heavy waves, new blubber piling onto existing rolls with each pulse, the fat of her thighs thickening until they force her knees apart another inch, then another. Her sides swell with fresh rolls of flesh. The seat beneath her screams under the accumulating weight. Fabric detonates at the back. The floor actually flexes under the new pounds. ${Math.round(umbral.lbs).toLocaleString()} pounds. She barely stays seated. Her hands are shaking. The void is satisfied but she is not sure she is.`,

  // Target 6 — Big (~520-640 lbs)
  (target, umbral) => `${target.name} is well over five hundred pounds — a massive woman, her belly an enormous warm presence, her thighs columns of soft flesh — and she does not run. She turns toward ${umbral.name} and plants herself and says no with everything she has, using her body as the argument. She shoves forward, putting all that mass in motion, trying to reach ${umbral.name} before the void consolidates. The two enormous women collide in the half-darkness: the soft mass of ${target.name}'s belly hitting the edge of the void with a deep, resonant impact, flesh colliding with cold darkness in a way ${umbral.name} hasn't felt before. ${umbral.name} goes back half a step. The void flares with effort. ${target.name} pushes harder. For a long, straining moment it is genuinely unclear who wins. Then ${umbral.name}'s hunger overrides the uncertainty and the void opens wide and takes everything at once. The absorption staggers her. She can't stand. She slides down the wall to sitting, her body expanding massively around her, enormous rolls of new blubber pouring outward and piling onto the existing flesh, her thighs spreading across the floor as fresh fat surges into them. The sound of fabric destroying itself is continuous. She sits in spreading softness for a full minute before she can move. ${Math.round(umbral.lbs).toLocaleString()} pounds. Her shadow, she notices, is now the size of a small room.`,

  // Target 7 — Large (~640-700 lbs)
  (target, umbral) => `${target.name} is enormous — approaching immobility, nearly seven hundred pounds, her mass so great that moving is itself an act of effort. She cannot run. She knows this. She uses what she has instead: she rocks herself forward off her reinforced seat with a grunt of effort and puts her full weight against the void as it reaches her, leaning into it, daring it to move her. ${umbral.name} feels the difference immediately. This isn't a girl she can simply pull — this is a mass nearly as significant as her own, digging in with everything it has. The void strains. ${umbral.name} plants her feet and draws on the hunger with a concentration she's never needed before, feeling the new cold power of her form focused entirely forward. ${target.name} sways. She grabs the doorframe, gets her hands around it, wood cracking under her grip. Then the void deepens and the wood fails and she goes in with a sound like a wave breaking. ${umbral.name} drops to her knees on the floor, both hands splayed, absorbing the growth through the impact. Her belly rolls outward across the floor in front of her as new blubber surges forward, the fat of her lower rolls extending further still, the flesh thick and warm and accumulating. Her thighs flatten and widen against the ground as fresh mass forces them apart. She kneels in her own expansion, feeling each new pound of blubber settle warm and heavy. ${Math.round(umbral.lbs).toLocaleString()} pounds. She needs a moment. She takes it.`,

  // Target 8 — Massive (~700-760 lbs)
  (target, umbral) => `${target.name} is barely mobile — nearly seven hundred and fifty pounds, her body a monument of soft flesh that moves only with great deliberateness — but she is not helpless. She has positioned herself against a load-bearing wall and she waits for ${umbral.name} with the calm of someone who has decided how this will go. When the void touches her she doesn't flinch. She leans into it, puts every pound she has against the cold draw of it, and she succeeds in slowing it. ${umbral.name} strains, sweating cold, feeling the hunger fight against resistance it wasn't built to overcome easily at this stage. ${target.name} braces against the wall, pressing back, and the wall actually groans. ${umbral.name} screams the hunger forward with everything she has and the void tears loose and takes ${target.name} in a long, wrenching draw that leaves ${umbral.name} on her hands and knees in the center of the room. The growth is immense and continuous: new blubber pressing the floor flat in front of her as her belly advances, the fat of her thighs spreading to either side as fresh mass fills them, her whole body heaving outward in a slow expansion of warm flesh that takes nearly a minute to complete. The blubber settles in layers, each new roll warm and heavy over the last. ${Math.round(umbral.lbs).toLocaleString()} pounds. She cannot stand up yet. The void is full. She is full. The floor holds, barely.`,

  // Target 9 — Colossal (~760-820 lbs)
  (target, umbral) => `${target.name} is immobile — over seven hundred and fifty pounds, fixed in her reinforced corner, an enormous soft presence that cannot come to ${umbral.name}. What she can do is resist verbally, loudly, and with the full weight of her fury: she demands ${umbral.name} stop, she calls for help, she shouts the walls down. ${umbral.name} crosses the room to her, the void billowing outward with each step, and stands before the colossal woman. There is a brief, uncomfortable moment — two enormous women, one consuming, one immobile — before the void seizes. ${target.name} slaps at it, scores of pounds of soft arm muscle against the cold darkness. She grabs ${umbral.name}'s wrist and holds with every ounce of immobile strength she has. It is meaningful resistance and it means nothing. The void pulls her in, slowly and completely, and ${umbral.name} falls backward under the mass of the absorption and lies there while her body grows. The growth is extraordinary: her belly heaves upward and forward in waves of surging blubber, new fat piling onto existing rolls in thick, warm layers, her thighs widening as fresh flesh forces them apart until they press against the walls of the room. She breathes. The room is darker. She is larger. The chair she collapsed is unrecognizable. ${Math.round(umbral.lbs).toLocaleString()} pounds. She almost didn't make it through that one.`,

  // Target 10 — Blob (820+ lbs)
  (target, umbral) => `${target.name} is a full Blob — over eight hundred pounds, entirely immobile, a breathtaking mountain of soft warm flesh occupying the entire reinforced corner of the room. She is the same fundamental category as ${umbral.name}. What follows is not a fight so much as a confrontation between two enormous facts. ${umbral.name} crosses the room, void billowing, and the air between them goes cold and strange when their masses meet. ${target.name} cannot move but she can exert: she presses all eight hundred-plus pounds of herself against the void, using gravity and sheer volume as resistance, and the effect is real. ${umbral.name}'s void stutters. She has never encountered this. She has to reach into the hunger at a depth she's never accessed, pulling from some colder, older place, and drive the void forward with everything she has. ${target.name} resists vocally, enormously, furiously. The room shakes. Then the void takes hold and the absorption is the longest, most brutal thing ${umbral.name} has experienced: new blubber driving forward across the floor like a tide as her belly advances inch by inch, her thighs pressing the walls as fat surges outward in every direction, the soft mass of her flesh growing and piling and settling without pause. When it ends she is on her back in the ruins of the room, the new blubber warm and heavy all around her, breathing hard. The dark is absolute. ${Math.round(umbral.lbs).toLocaleString()} pounds. She is going to be here for a while.`,
];

// Stage 1 entries
const UMBRAL_STAGE_1 = [
  // Target 0 — Slight
  (target, umbral) => `The void-wings are just beginning, small and lightless, and ${umbral.name} finds she barely has to think about it anymore — the hunger knows a slight girl when it senses one. ${target.name} is perhaps a hundred pounds, a wisp of a thing, and she freezes when the darkness moves toward her, which is the wrong response. The void takes the frozen girl in a single clean motion, a soft implosion, and she is gone before she had anything real to offer in the way of resistance. ${umbral.name} doesn't bother to brace for the growth — she's learned by now to simply let it come. And it does: a warm rolling swell through her enormous middle, new blubber pushing outward in a slow, insistent press as her belly advances forward and settles heavier. Her thighs round out as fresh fat fills them from within, the inner surfaces pressing warm together. A seam at her hip opens with a quiet tear as new flesh forces it apart. She adjusts her weight across the reinforced seat and feels the new pounds of blubber settle, one slow warm wave resolving into the next. ${Math.round(umbral.lbs).toLocaleString()} pounds now. She checks the number with the distant interest of someone keeping a useful tally. The void feels fed. It wants more almost immediately.`,

  // Target 1 — Trim
  (target, umbral) => `${umbral.name}'s shadow reaches the length of the room before she does — one of the new things her void-wings have done to her, the way her darkness extends without her telling it to. ${target.name} is slim and has fast reflexes and she's already moving when the shadow finds her, cutting toward the window, her heels loud on the floor. The void closes the window and the door in the same moment. ${target.name} turns, finds herself boxed in, and tries to slide along the wall away from the darkness. She is quick. The void is quicker and increasingly confident. It takes her mid-scramble, and she goes in with a cry of frustration that cuts off clean. ${umbral.name} feels the absorption as something practiced now, a familiar warmth that moves through her in the established way: belly forward as new blubber surges outward, fresh fat thickening her thighs until the flesh presses warm and insistent against itself. A button flies as the waistband can no longer contain the new mass. A seam opens at the right side as blubber piles onto the existing rolls. New flesh settles into her with soft, warm pressure. She presses a hand into the fresh softness under her lowest fold and feels it give, deep and yielding. ${Math.round(umbral.lbs).toLocaleString()} pounds. Satisfying. Clean. The hunger marks it and moves on.`,

  // Target 2 — Soft
  (target, umbral) => `${target.name} sees it coming — she has a moment of full awareness, looking at ${umbral.name}'s void-wings spread wide in the doorway, the solid-black eyes, the cold that moves ahead of her like a herald. She backs up. She puts furniture between herself and the void with deliberate calm, using what's available. ${umbral.name} finds this almost respectful. The girl has sense. She navigates the furniture with methodical patience, the void flowing around each obstacle, ${target.name} retreating until she hits the wall and has nowhere left to go. The absorption is clean and practiced: the void draws her in against the resistance of her weight, she pushes back with real soft-bodied effort, and then she goes. ${umbral.name} absorbs her with the same ritual attention she brings to everything now. Her belly swells forward in a sustained push of new blubber, the fat advancing in a slow warm wave. Her lower rolls deepen as fresh flesh piles onto them. The soft mass of her sides pads outward as blubber forces them wider. A button pops from her waistband and rolls into the dark. ${Math.round(umbral.lbs).toLocaleString()} pounds. Good. She settles the new mass into position like arranging furniture.`,

  // Target 3 — Padded
  (target, umbral) => `${target.name} is padded and stubborn and she goes for the window the moment she sees ${umbral.name} enter, which shows good instincts even if it doesn't help. The void-wings fold across the window before she reaches it. She pivots, tries the door — covered. She turns and faces ${umbral.name} with the resigned fury of someone who has run out of options and has decided to make the most of the confrontation. She shoves hard into the void with her full padded weight, getting both hands deep into the cold dark and pushing, her whole body going into it. ${umbral.name} lets the resistance come and wraps the void around it, absorbing the push and transforming it into grip. ${target.name} screams and puts her heels in and leans back and stays there for ten full seconds, her soft body a real counterweight against the cold pull. Then the void closes and she goes in. ${umbral.name} feels new blubber push forward in a long, rolling swell, fresh fat adding itself in practiced layers onto the existing rolls of her belly. Her thighs widen as new flesh forces them apart. The rear seam of her clothing blows open as fresh blubber expands outward. She notes the new weight, the new dimension of herself, the warm bulk of it. ${Math.round(umbral.lbs).toLocaleString()} pounds. Methodical. Inevitable.`,

  // Target 4 — Heavy
  (target, umbral) => `${target.name} is heavy and she knows how to use it — the moment the void reaches for her she goes low, putting her weight into her legs, dropping her center of mass to make herself harder to pull. It works better than ${umbral.name} expected. The void finds her harder to grip when she's braced like that, solid and determined, her thick legs digging in. ${umbral.name} spreads her void-wings slightly and the darkness comes from two directions at once, and ${target.name} swings to face the new angle, then swings back. She cannot cover both. The void from the flank takes her mid-turn and she goes in gripping the edge of a desk with both hands, pulling the desk six inches before her grip fails. ${umbral.name} absorbs her with the deep, rolling warmth of real mass: her belly drives forward in a long, slow expansion, new blubber piling onto existing flesh in thick warm layers, her lower rolls deepening as fresh fat accumulates. New blubber settles into her thighs in waves, the flesh thickening and pressing warm against itself. The seat beneath her creaks hard. The back of her outfit tears open from waist to shoulder as new mass forces it apart. She stays seated through the expansion, breathing slowly, feeling every pound of blubber arrive warm and heavy. ${Math.round(umbral.lbs).toLocaleString()} pounds. Good.`,

  // Target 5 — Plump
  (target, umbral) => `${target.name} is well over four hundred pounds and she tries to run, which is brave and somewhat futile — her run is a fast, rolling waddle that shakes the floor, her enormous belly swaying, and she makes it twenty feet before the void-wings cover the gap. ${umbral.name} brings them down like a net and the darkness encircles the heavy girl completely. ${target.name} fights the enclosure: she pushes against the void-dark with her hands, she tries to use her considerable weight to force a gap, she leans and strains and makes real noise about it. The resistance is genuine and ${umbral.name} has to focus, draw the wings in, tighten the void around all that mass. ${target.name} makes one more heaving push and then the void takes her and the absorption is a great flood of warmth that forces ${umbral.name} back in her seat. Her belly surges outward in a huge continuous push, new blubber piling forward in waves — a fresh roll of belly fat spilling over her waistband, then another beneath it. Her thighs spread as new fat surges into them, forcing them apart inch by inch. The rolls at her sides deepen and multiply as blubber piles onto blubber. The sound of fabric tearing is immediate and extended. She presses both palms to her expanding belly and feels the new flesh warm and enormous and insistent under them. ${Math.round(umbral.lbs).toLocaleString()} pounds. She exhales slowly.`,

  // Target 6 — Big
  (target, umbral) => `${target.name} is over five hundred pounds and she does not waste time with running. She comes directly at ${umbral.name}, using her mass as the weapon, trying to disrupt the void at its source before it can concentrate. The two large women collide — a deep, resonant impact, the soft mass of ${target.name}'s enormous belly pressing against the cold dark of ${umbral.name}'s void with a force that makes the floor creak — and for a moment the void genuinely falters. ${umbral.name} grabs ${target.name}'s wrists and the struggle is physical, flesh colliding with flesh, two enormous women pushing each other with everything they have, blubber shaking with the effort on both sides. ${target.name} is strong and heavy and she drives ${umbral.name} back three steps before the void-wings catch her from behind. She arches, tries to break the rear grip, fails. ${umbral.name} pulls hard and the absorption tears loose all at once: the warmth of it drives her to the floor, sitting hard, new blubber rolling outward across the floor for nearly a foot of fresh belly mass. Her thighs press wide as fat surges into them. Clothing detonates. She sits in the center of the expansion, breathing hard, feeling the new weight of blubber settle around her like something earned. ${Math.round(umbral.lbs).toLocaleString()} pounds.`,

  // Target 7 — Large
  (target, umbral) => `${target.name} is nearly immobile — close to seven hundred pounds, her movement labored and deliberate — but she has thought about this. She has positioned herself in the center of the room with heavy furniture around her, making herself difficult to approach, and when ${umbral.name} enters she begins throwing objects: books, a lamp, a reinforced chair with both arms. She has enough mass to hurl these things with real force and she does. ${umbral.name}'s void-wings catch what they can, absorbing the thrown objects into the darkness, but one lands squarely. ${umbral.name} grunts, absorbs the hit, and advances. ${target.name} plants herself and screams and puts every pound of her enormous body against the void as it reaches her — seven hundred pounds of soft, desperate, furious resistance. The void strains. ${umbral.name} drives it forward with concentrated hunger. The resistance cracks and ${target.name} is taken in a long, continuous draw. The absorption fills ${umbral.name} like water fills a vessel: her belly expands in sustained waves of new blubber, fresh fat piling onto existing rolls until they hang heavier and deeper, her lower body widening as blubber forces her thighs further apart. The floor beneath her groans under the accumulating mass. ${Math.round(umbral.lbs).toLocaleString()} pounds. She needs a moment to feel the scope of it.`,

  // Target 8 — Massive
  (target, umbral) => `${target.name} is nearly seven hundred and fifty pounds and barely moves, but she is not passive. She has been watching ${umbral.name} for weeks and she has a plan: she has draped herself with metal chains — chair chains, locked — making her body harder to pull. When the void finds her she jerks against the restraints and the metal cuts into the cold dark and actually slows it. ${umbral.name} has never encountered this. The void struggles with the chains, trying to flow through them, and ${target.name} uses the delay to press every pound of herself against the resistance as hard as she can, leaning into the chains, using her immobility as an anchor. ${umbral.name} focuses the void-wings into a tight, piercing cone and drives it through the restraints like a wedge. The chains shear. ${target.name} goes with them. The absorption is violent and prolonged and ${umbral.name} ends up prone on the floor, her body spreading in every direction, new blubber surging outward for two full minutes without pause — fresh fat forcing her thighs wide across the floor, new rolls of belly flesh extending forward, the soft mass of her sides swelling thick with accumulated blubber. ${Math.round(umbral.lbs).toLocaleString()} pounds. She lies there and breathes and feels the enormity of what she now is.`,

  // Target 9 — Colossal
  (target, umbral) => `${target.name} is a colossal immobile woman — her body filling her entire corner, every surface around her reinforced for her weight — and she has had time to prepare. She has turned herself into an argument: she is pressed into her corner with every piece of furniture stacked around her as barricade, and when ${umbral.name} enters she begins a sustained verbal assault — calling for help, threatening, negotiating, describing in exact detail what will happen to ${umbral.name} if she continues. It is remarkable, actually: a voice as enormous as the woman producing it. ${umbral.name} advances through the furniture, void-wings folding it into darkness, and reaches the barricade and the colossal woman behind it. The absorption starts as a negotiation between two immense forms: the void cold and hungry, the target warm and heavy and absolutely determined. The resistance lasts longer than any before it. When the void finally wins, the release is catastrophic in its completeness: ${umbral.name} falls backward and new blubber surges outward in every direction at once, the fat of her belly pressing the walls as it advances, fresh mass piling onto her thighs and sides and lower rolls without stopping, the flesh warm and accumulating and vast. She stays there until the swelling stops, which takes a long time. ${Math.round(umbral.lbs).toLocaleString()} pounds.`,

  // Target 10 — Blob
  (target, umbral) => `${target.name} is a Blob — over eight hundred pounds, entirely immobile, the largest kind of woman in the world — and ${umbral.name} is also enormous by any ordinary standard, and what happens between them is something the void wasn't designed for. Two massive women. One trying to consume the other. The void-wings spread wide and the darkness surrounds ${target.name} completely and she pushes back with eight hundred-plus pounds of soft, enormous resistance, her arms beating against the cold, her voice a sustained roar. The void bends under her weight — literally bends, the darkness flexing like a net loaded past capacity. ${umbral.name} has to drive the hunger past every limit she knows, pouring herself into the void with a desperation she hasn't felt since she was ordinary. The room gets cold. The lights die. ${target.name} fights the whole time: screaming, pressing, the soft mass of her enormous flesh surging against the void, using her own blubber as a weapon until the very last moment. Then the void takes her and ${umbral.name} is knocked flat by the force of the absorption. New blubber rolls outward without mercy — her belly fat surging forward in waves across the floor, her thighs forced apart by fresh mass piling into them, the flesh of her arms and sides swelling thick with accumulated fat — a continuous rolling expansion that fills the room and presses the doors and doesn't stop for a very long time. ${Math.round(umbral.lbs).toLocaleString()} pounds. She is on the floor. She is fine. She is enormous.`,
];
