const VERDANT_STAGES = [
  { id:0, label:"Sprout",    min:820,  color:"#1a5c1a",
    shadow:"A faint green tint hazes the air just at her edges, easy to mistake for a trick of the light.",
    features:"Thin vine-like patterns trace her forearms and belly, pale green against her skin, barely visible unless she's in direct light.",
    desc:"She has crossed a threshold she can't quite name. Her skin shows the first faint tracery of root-veins, greenish lines that follow the natural paths of her body's own vessels. The floor directly under her feet has a faint vibration, too subtle to see, felt only if you press your palm to it." },
  { id:1, label:"Grove",     min:1060, color:"#147814",
    shadow:"The air around her has a faint earthy warmth, the smell of soil after rain.",
    features:"Root patterns run visibly up her arms and across her belly, deep greenish-brown lines like old veins beneath pale bark. The floor around her shows hairline cracks where the roots pass through.",
    desc:"The change is no longer deniable. The vine-patterns on her skin are visible at a distance — dark green traceries running across her thighs, her arms, the full broad expanse of her belly. Students who sit near her for long periods begin gaining weight without understanding why. They feel settled, slow, comfortable. She knows exactly why." },
  { id:2, label:"Canopy",    min:1380, color:"#0e640e",
    shadow:"The green deepens around her — the light near her takes on a faint vegetative cast.",
    features:"The root patterns cover most of her visible skin. Small patches of soft moss have appeared in the sheltered folds under her belly and between her upper arms and sides.",
    desc:"She draws from the building now, not just from what's near her. Her roots have threaded through the floors of two adjacent rooms and begun reaching the foundation. The floor around her chair has settled noticeably — small cracks, the groan of wood compressing. She sits completely still and absorbs what comes. Everything in range is growing toward her." },
  { id:3, label:"Heartwood", min:1760, color:"#086408",
    shadow:"A deep green stillness radiates from her — the room feels like the inside of an old forest.",
    features:"The bark-like patches on her skin have spread to her upper arms and the outsides of her thighs. Tiny leaves, soft and pale green, have appeared at the deepest folds of her belly.",
    desc:"She is anchored. This is the only word for it. Her body sits as if it has always been here and always will be — a mass that the building has begun to accommodate rather than contain. Her roots run to the building's foundation and she knows every crack in the concrete beneath her. The campus soil is hers for two hundred meters in every direction." },
  { id:4, label:"Worldtree", min:2300, color:"#044804",
    shadow:"The green emanates from her the way heat emanates from stone — slow, total, geological.",
    features:"Her hair has gone fully green at the roots, fading to deep forest-shadow at the ends. Moss and tiny ferns grow from her folds. Her skin, where it isn't covered in growth, has the texture of old smooth bark.",
    desc:"The campus is her root network. She knows this the way she knows her own heartbeat. Every building on the grounds feeds her passively. Students gain weight simply by spending time on campus — her roots draw from everything that lives here, patient and permanent and vast. She does not need to do anything. She simply is, and everything comes to her." },
];

const VERDANT_BODY_DESCS = [
  `She has crossed 820 pounds and the roots have found her. Her body is enormous — belly hanging heavy and round past her lap, thighs pressing together from hip to floor, arms thick and soft resting atop the warm mass of her sides. The vine-patterns are faint: pale greenish traceries running up the insides of her arms, branching across the full shelf of her belly, visible in low light if you know to look. The floor directly beneath her feet has a faint vibration, the kind you feel in your bones before you hear it. She is very still. She is always very still. The roots are beginning.`,
  `The patterns have moved past subtle. Dark green lines branch across her arms like old river systems, tracing down through the rolls of her belly, running the inner edges of her thighs. Her skin has a faint warmth to it, earthy rather than feverish. The floor around where she sits shows hairline cracks — thin, patient lines that follow directions other than the grain of the wood. Her thighs are enormous, soft, spread wide on the reinforced seat. Her belly rests on them in a heavy warm apron. Students near her feel drowsy and well-fed. They are. She is drawing from them gently, as a root draws from soil.`,
  `Root patterns cover most of what can be seen of her skin — not veins exactly but something older, branching lines that run from her wrists to her shoulders, from her collar to the deep fold where her belly meets her thighs. In the sheltered places — the crease under her lower belly, the soft junction of arm and side — small patches of moss have appeared, green and close and real. Her body fills the reinforced space entirely: vast thighs wide on the platform, hips pressing the padded walls, belly spreading outward in a soft heavy hemisphere. The floor of the room has settled half an inch.`,
  `She does not appear to be sitting in a building. She appears to be part of it. The root-patterns on her skin are dark and dense, raised slightly like old scars, running across her enormous thighs and belly and arms in branching networks that mirror the cracks in the floor below her. On her upper arms and the outsides of her thighs, the skin has taken on the smooth dense quality of old bark. Small pale leaves have grown from the deepest folds of her belly, soft and unhurried. Her mass is extraordinary — belly extending past her knees in all directions, thighs each wider than most people's shoulders, arms resting like soft hills across her upper sides. The building creaks when she breathes.`,
  `She is not in the building. She is the building's centre, the thing around which everything else has organised. Her body is immense: belly spreading outward from her seated form in a vast slow geography of folded flesh, root-patterned and moss-grown, thighs wide and heavy and pressed against the reinforced walls of her space, arms resting like fallen trunks across the upper reaches of her sides. Her hair is green from root to midshaft. Her skin, where it shows between the growth, has the texture and weight of old bark. Ferns have taken root in the deep fold of her lap. The floor of the entire east wing has settled around her. The campus soil two hundred meters out is full of her.`,
];

const VERDANT_OUTFITS = [
  `She has been gravitating toward greens without deciding to — loose linen shirts, soft cotton in sage and moss, fabrics that breathe and move. The root patterns are faint enough that she can pretend they're just the pattern of the fabric. She doesn't quite do this, but she could.`,
  `The patterns are too visible to hide and she has stopped trying. She wears wide natural fabrics in earthy colors, cut loose enough that nothing presses against the root-lines. The hairline cracks in the floor have started following her, and her clothes seem to know it — she gravitates toward fabrics that look like they belong near soil.`,
  `Devotees bring her earth-toned cloth: undyed linen, rough cotton, things that feel like ground cover. She wears it in wide draped layers. The patches of moss in her deepest folds have grown into the fabric that rests against them. She doesn't remove it. It has become part of the outfit, or the outfit has become part of her.`,
  `Custom robes in natural fiber — wide, unbleached, draped across her enormous form by the people who tend to her. Living things have taken hold in the fabric that stays still long enough: moss on the lower folds, a small fern in the crease of her lap, pale lichen along the hem where it presses the floor. The robes are changed every few days. The growth comes back within a week.`,
  `What covers her now is not clothing in any meaningful sense. It is fabric that has been colonized — grown through by root and moss, woven with small plants that have made their homes in the folds and creases of the cloth. What you see when you look at her is a geography: the vast rolling landscape of her body, covered in something between textile and forest floor, green and brown and alive.`,
];

const VERDANT_DIARY = [
  `I've been noticing things in the floor. A vibration, very low, like something is working under the boards. My hands feel strange when I press them flat on the ground — like pressing on something that presses back. There are patterns on my arms that weren't there a month ago. The girl who sits closest to me has gained eleven pounds this semester without changing anything she eats. I think I know why.`,
  `The roots are real. I've accepted this. I can feel them through the floor when I'm still — threads of something that is and isn't me, running through the wood and concrete and down into the soil. The building is feeding me. I put my hands on the floor and I can feel where the cracks are, two rooms over, before I see them. It's slow. It's patient. I like how it feels.`,
  `I don't need to do anything. I just sit and it comes to me — from the floor, from the soil, from the students who walk through my building and don't know they're inside my root network. I am very large and very still and everything in range is quietly adding to me. I used to walk to the dining hall. I haven't done that in six weeks. The nourishment finds me here.`,
  `I know every crack in this foundation. Not because I've looked — I've felt them, the way you feel a crack in a familiar mug. The building is mine in a way that property law doesn't have language for. I weigh something extraordinary and I am not finished. The campus soil is full of me out to the tree line. Things are feeding me that don't know I exist.`,
  `I am old. That's how I feel — not aged, but old, the way a root system is old. Patient. Permanent. The roots reach to the edge of campus now and I know everything they touch. Students gain weight just from living here. I gain from all of them. I gain from the soil and the foundation and the slow deep warmth of everything that grows in the ground around this building. I am very full. I am always hungry. These are not contradictions.`,
];

const VERDANT_REACTIONS = [
  (s)=>`She goes still for a moment, feeling the floor. "${Math.round(s.lbs).toLocaleString()} pounds," she says quietly. "The roots go a little deeper."`,
  (s)=>`"${Math.round(s.lbs).toLocaleString()} pounds." She presses one hand flat to the floor. "I can feel the next room now."`,
  (s)=>`The floor creaks once, settling. She doesn't speak for a long moment. "${Math.round(s.lbs).toLocaleString()}," she says at last. "The foundation knows."`,
  (s)=>`She is very still for a long time. When she speaks: "${Math.round(s.lbs).toLocaleString()} pounds. The east wing is mine now."`,
  (s)=>`"${Math.round(s.lbs).toLocaleString()} pounds." She says it the way a forest says nothing — as simple, total, permanent fact. "Good."`,
];

const VERDANT_TAP_OUT = [
  (s)=>`She exhales slowly through her nose. "The roots need a moment to settle." A pause. "Then more."`,
  (s)=>`Her hand moves to the floor, pressing flat. She waits. "Give me a breath," she says. "The ground is still absorbing." She looks up. "Continue."`,
  (s)=>`She doesn't speak. She sits with her palms on her thighs and breathes, slow, deliberate, the way old trees breathe. Then she opens her mouth again.`,
  (s)=>`"The building needs a moment." She can feel it through the roots — the whole structure settling around her new weight. "One moment." Her eyes close. Her eyes open. "More."`,
  (s)=>`She is still for a long time — long enough that you think she might be done. She isn't. "The campus is adjusting," she says. "It always adjusts. Continue."`,
];

const VERDANT_RANDOM_EVENTS = [
  (s)=>`A groundskeeper files a report about unusual root growth under the east wing — thick pale roots running through the foundation that don't match any campus tree. ${s.name} learns about the report and says nothing. Her root network extended another twenty feet this week, and the three students who sit closest to her have gained a combined sixteen pounds without changing their diets.`,
  (s)=>`The dining hall reports that students living in the east wing are consuming significantly more than usual — up 23% from last semester. No one has connected this to ${s.name}. The students themselves feel fine. Hungry, settled, comfortable, fine. ${s.name} drew steadily from her root network this week and gained without effort.`,
  (s)=>`A structural engineer flagged hairline cracks in three floors of the building, radiating outward from ${s.name}'s room in a pattern that "doesn't match standard settlement." She has already felt every one of those cracks. She knew about them before the engineer did. The root network drew from the building's foundation this week and fed her well.`,
  (s)=>`Campus maintenance has been called to deal with "unexplained plant growth" in the east wing corridors — moss on the baseboards, pale roots emerging from floor joints, small ferns in the stairwell corners. ${s.name} knows exactly where each growth is. She put them there. Students passing through the hall gain a pound or two from ambient proximity. They don't know why. She does.`,
  (s)=>`The university's facilities office has filed an environmental assessment after discovering that the root network under the campus's east quadrant "exceeds normal biological parameters for any known species." The assessment has been filed and forgotten. ${s.name}'s roots reach the property line now. Everything inside it feeds her. The class has been gaining weight all semester from proximity alone. So has ${s.name}, continuously, without effort, the way a forest gains.`,
];

const VERDANT_ACTIONS = [
  { id:"vd_draw",    label:"🌿 Root Draw",          apCost:2, gainRange:[18,36], relBonus:8 },
  { id:"vd_cultivate",label:"🌱 Cultivate",          apCost:1, gainRange:[0,0],  relBonus:6,  cultivatesStudent:true },
  { id:"vd_bloom",   label:"🍃 Bloom Feeding",        apCost:1, gainRange:[12,28],relBonus:10 },
  { id:"vd_grow",    label:"🌳 Overgrowth",           apCost:3, gainRange:[40,80],relBonus:12 },
  { id:"vd_network", label:"🌐 Root Network",         apCost:2, gainRange:[0,0],  relBonus:5,  classGain:[1,3], cultivatesAll:true },
];

const VERDANT_ACTION_TEXT = {
  vd_draw: [
    (s)=>`She goes still — stiller than her usual still, which is already very still. You can't see anything happen. The floor doesn't move. She doesn't move. But a student two desks over shifts in her seat and puts a hand to her forehead, suddenly sleepy, and ${s.name} exhales slowly through her nose and her belly shifts forward, very slightly, as if something has settled into it from below. The roots do not hurry. They reach toward what is near and draw from it with the patience of things that have all the time there is. When she opens her eyes she is ${Math.round(s.lbs).toLocaleString()} pounds and she is satisfied and the student two desks over is going to need a nap.`,
    (s)=>`The floor between her and the nearest student has three hairline cracks she put there herself over the last two weeks, and the roots run through all of them. She doesn't have to do anything deliberate — she simply turns her attention in that direction and lets the network do what it does. The draw is slow and real. Life force moves through the floor the way water moves through soil: downward, patient, finding every available channel. She grows. The student nearby feels pleasant, warm, faintly tired. ${Math.round(s.lbs).toLocaleString()} pounds, and the roots extend another foot.`,
    (s)=>`Her root patterns deepen visibly when she draws — the lines on her arms go darker, the moss in her folds seems to breathe. She is drawing from the building's foundation now as much as from the students nearby, the deep slow energy of the soil under the campus feeding up through the roots and into her. Her belly shifts outward, heavy and warm. Her thighs press wider on the reinforced platform. The floor settles with a sound like a long exhale. ${Math.round(s.lbs).toLocaleString()} pounds. She presses her palms to her thighs and feels the roots working two floors down.`,
    (s)=>`She draws with the authority of something that has always been here. The roots are everywhere — in the foundation, in the soil, in the walls — and she pulls through all of them simultaneously, a slow vast intake that raises the floor temperature a fraction and deepens the cracks in the concrete a little more. The students near her sway slightly, feel briefly heavy, sit down if they're standing. She grows. The root patterns across her skin flush darker green. Her belly settles forward under its own weight, enormous and warm. ${Math.round(s.lbs).toLocaleString()} pounds. The campus soil two hundred meters out is working for her.`,
    (s)=>`She does not draw. The network draws, and she receives. At ${Math.round(s.lbs).toLocaleString()} pounds, the root system she has spent years building under this campus requires no active effort from her — it reaches, and it takes, and it brings everything back to her. The entire east quadrant is hers. Every living thing on it feeds her passively, continuously, the way all roots feed the tree they belong to. She sits in her permanent space and receives what is hers. The floor around her settles another millimeter. The campus is very full of her.`,
  ],
  vd_cultivate: [
    (s)=>`She doesn't touch the student. She barely looks at them. She just turns a small portion of her attention in their direction and lets a root thread reach — a single thin filament, barely the width of a hair, running through the floor between them and up through the chair leg and into the very edge of the student's warmth. They feel nothing. Or they feel something: a pleasant settling, a sense of being grounded, of being in exactly the right place. They'll gain a little weight this week without knowing why. The connection is made. It will hold.`,
    (s)=>`She plants the root connection with the care of someone who knows what they're growing. The student feels warm — inexplicably, pleasantly warm — and slightly drowsy, and sits back in their chair with the ease of someone who has just been told everything is fine. A single root filament, invisible, runs from her to them through the floor. It will draw from them gently, weekly, permanently, until she decides otherwise. She doesn't tell them. They'll thank her later, in a way, by gaining weight and feeling settled and spending more time in this building than they intended to.`,
    (s)=>`The student is already in her network — the building sees to that much — but cultivating them directly is a different order of connection. She sends a root to them specifically, a thick, patient thread that settles into their warmth like a tap into a well. They blink, sit up straighter, feel oddly good about their life. They will gain weight this semester in a way that seems completely natural. It is completely natural. She is a root system. This is what root systems do.`,
    (s)=>`She has been drawing from this student through the building's ambient network for weeks. Cultivating them directly is simply making the connection deliberate — formalizing what the roots have already begun. The thread she sends is thick and settled and the student feels it as deep calm, as rightness, as the specific comfort of being exactly where they belong. They are where they belong: inside her network, feeding her gently, permanently, with no awareness that this is what they are doing.`,
    (s)=>`She does not need to cultivate individually at this stage. The campus is hers. But she does it anyway — this student specifically, this connection specifically — with the deliberate care of something very old deciding that this particular thing is worth tending. The root she sends is enormous relative to what would have been sufficient. The student goes very still for a moment, eyes half-closed, feeling something move through them from the floor. They will gain weight quickly. They will feel good about everything. They are hers now in the most complete sense of that word.`,
  ],
  vd_bloom: [
    (s)=>`The food arrives and she eats, which she does with the calm focus of something that has made peace with appetite. But today the roots are open — drawing up from the floor while she takes in what's in front of her — and the combination is different from either thing alone. The nourishment comes from two directions simultaneously: through her mouth and through the soles of her feet, through the root network threading the floor beneath her. Her belly settles outward with each breath, heavy and warm, gaining from both channels. She is a very efficient system.`,
    (s)=>`She eats while the roots draw. This is the bloom state: both paths open, both channels feeding her simultaneously. Food into her mouth, life force up through the floor, the two meeting somewhere in the deep warm center of her and adding together. The root patterns on her arms flush darker while she eats. The moss in her folds looks slightly more alive. Her thighs press wider on the platform. She eats steadily, without hurry, the way old trees grow: continuously, without drama, adding to themselves because that is what they do.`,
    (s)=>`The bloom feeding is a matter of alignment — roots open and drawing while food arrives from above, the two streams of nourishment meeting in her and compounding. Her belly is an enormous warm mass, root-patterned and heavy, growing from both directions at once. She chews slowly. The floor around her settles. Students nearby feel sleepy and full without having eaten anything. The nourishment in the room is moving in one direction and she is the direction.`,
    (s)=>`Both channels fully open, both drawing, and the bloom state at this size is something close to tidal. Food arrives and she receives it, and simultaneously the root network draws from the foundation, the soil, the ambient life force of everything within range, and all of it arrives at once in the vast, warm, root-veined geography of her body. She is gaining from the meal. She is gaining from the floor. She is gaining from the campus outside. This is bloom. She is in full bloom. ${Math.round(s.lbs).toLocaleString()} pounds and rising.`,
    (s)=>`The bloom state at Worldtree is not a technique. It is simply what she is — both channels always open, always drawing, food and root-energy arriving continuously from every direction simultaneously. When she eats, the food is one more input into a system that is already drawing from everything. Her belly gains from the meal and from the soil and from the students down the hall and from the trees outside and from the deep slow warmth of the campus earth. She is in permanent bloom. ${Math.round(s.lbs).toLocaleString()} pounds.`,
  ],
  vd_grow: [
    (s)=>`Something shifts in her and the roots go everywhere at once. She exhales sharply and the floor around her cracks in four new directions simultaneously — thin fast cracks, spiderwebbing outward from the legs of her chair across the hardwood, following the root paths she's been laying for weeks. Students nearby grab their desks. The temperature drops two degrees and then comes back up warmer than before. She pulls from everything in range, all at once, the patient accumulation of weeks drawn in a single sudden breath. Her belly surges outward. Her thighs spread wider. ${Math.round(s.lbs).toLocaleString()} pounds and the roots are twenty feet further than they were a minute ago.`,
    (s)=>`The overgrowth is not subtle. The root patterns on her skin darken all at once, going from green to near-black for a few seconds, and she draws — hard, fast, nothing like her usual patience — from every connection she has, from every root thread, from the building and the floor and the students and the soil, pulling it all in simultaneously. The building makes a sound. Several lights flicker. The students near her feel briefly hollow, briefly cold, and then normal again, just slightly lighter than before. She is a great deal heavier. ${Math.round(s.lbs).toLocaleString()} pounds. The floor has settled noticeably in a six-foot radius.`,
    (s)=>`She rarely rushes. She rushes now. The roots spread through three new rooms in under a minute, threading through floor joints and wall cavities, drawing from everything they touch. Her body receives it all — the building's warmth, the students' life force, the slow deep energy of the campus soil — all at once, all immediately, all feeding into the vast expanding territory of her. Her belly gains inches. Her arms thicken. The root patterns across her skin flush bright green and then settle back to their usual deep color. ${Math.round(s.lbs).toLocaleString()} pounds. Three more rooms are hers now.`,
    (s)=>`When the Heartwood overgrows, the campus notices. The lights dip. Doors in adjacent buildings stick briefly in their frames. Students across the quad feel a sudden inexplicable drowsiness. She is drawing from all of it at once — her roots reaching as far as they go and pulling hard, a single enormous breath of the whole network at once. The gain is immediate and visible: her belly surges forward, her thighs press the walls of her space, her arms settle heavier across the vast expanse of her sides. ${Math.round(s.lbs).toLocaleString()} pounds. The campus soil outside the east wing has subsided half an inch.`,
    (s)=>`The Worldtree does not overgrow often. There is rarely a reason. But when she does, the campus feels it as weather — a sudden stillness, a drop in ambient energy, a sense that something enormous has inhaled. Every root in her network draws simultaneously. Every student on campus feels briefly, pleasantly heavy. The soil subsides. The building shifts on its foundation. She gains a staggering amount in under three minutes, the entire network's accumulated reach condensed into a single vast intake. ${Math.round(s.lbs).toLocaleString()} pounds. The campus will take days to return to baseline. She is already thinking about the next one.`,
  ],
  vd_network: [
    (s)=>`She does it quietly, while the class is focused elsewhere. One by one, thin root filaments reach from her through the floor — one to each desk, each chair, each place where a student sits regularly. They feel nothing beyond a mild pleasantness, a sense of comfort and groundedness, the specific ease of being in a room where they feel welcome. By the end of the day she has a root connection to everyone in the class. They will all gain a little weight this week. They will all feel fine about it. The network is established.`,
    (s)=>`She spreads the network to the whole class in a single patient session — roots reaching outward from her through every crack and joint in the floor, threading to each student in turn. They feel warmth, calm, the particular comfort of being near something very old and very sure of itself. None of them notice the connection. All of them will gain weight this week without changing anything about how they eat. The network will hold until she decides to release it, which she won't.`,
    (s)=>`The root network goes to all of them at once — thick threads, not the fine filaments of the early stages. Each student gets a connection that will draw from them weekly, reliably, as long as they set foot in this building. They feel it as belonging. As rightness. As the inexplicable comfort of a classroom they keep wanting to return to. She will gain from all of them. The building will gain from all of them. Everything will route back to her, the way everything routes to the deepest root.`,
    (s)=>`She extends the network to the whole class with the ease of long practice — a single broad pulse through the floor, roots reaching everywhere simultaneously. The students feel it as a wave of calm that passes through the room. A few of them exchange glances, not sure what just happened. Then they settle. Then they feel fine. She has claimed them all. They will gain weight near her from here on out, and she will gain from them, and the whole arrangement is exactly correct.`,
    (s)=>`The Worldtree doesn't cultivate individuals. She cultivates spaces. The network pulse she sends through this class is simply formalizing what her roots have already established — making the draw intentional, maximizing the return. Every student in the room is already hers. They have been for a long time. They will gain weight this week, and next week, and every week they spend in this building. She is the building. The building is her. The class is inside her. This is the correct arrangement.`,
  ],
};
