// The Squad — Lead: A1 Mobile | Support: A5 Editor
// Auto-generated — run: node scripts/generateDinnerDepth.mjs
// Wildcard depth for dinner pools (Pass 33).
import { registerModuleVariants } from '../../engine.js';

registerModuleVariants("dinner.conv.compliment_appetite", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.conv.suggest_second", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.conv.food_talk_dinner", [{ when: {}, text: ["She critiques like a devoted enthusiast and eats like one too.", "You compare notes on the sauce. {subject.name} demonstrates her opinion by eating more of it."] }]);
registerModuleVariants("dinner.conv.order_for_her", [{ when: {}, text: ["You order generously before she can talk herself out of it. {subject.name} watches the dishes arrive, pleased.", "Rich courses land without her asking. {subject.name} raises a brow — appreciation, not protest."] }]);
registerModuleVariants("dinner.conv.wine_and_cheese", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.conv.overcomes_hesitation", [{ when: {}, text: ["She wavers; you remind her she deserves pleasure. {subject.name} orders the larger portion.", "Menu guilt flickers and dies. {subject.name} chooses abundance and does not look back."] }]);
registerModuleVariants("dinner.conv.body_compliment", [{ when: {}, text: ["You tell her she looks stunning. {subject.name} smiles into her plate and keeps eating.", "Warm words land; she accepts them the way she accepts dessert — without fuss."] }]);
registerModuleVariants("dinner.conv.personal_chef_story", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.conv.endless_courses", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.conv.praise_capacity", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.conv.ask_passion", [{ when: {}, text: ["You ask what lights her up. {subject.name} talks until the main course vanishes unnoticed.", "Real conversation opens; appetite runs underneath like a second current."] }]);
registerModuleVariants("dinner.conv.talk_genuinely", [{ when: {}, text: ["You ask something real. {subject.name} answers while eating — unselfconscious, open.", "The menu forgotten, she talks. The food keeps disappearing anyway."] }]);
registerModuleVariants("dinner.conv.toast_together", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.conv.share_a_dish", [{ when: {}, text: ["A plate between you. {subject.name} eats more than her share without comment.", "\"We can share,\" you say. She reaches in — hunger wins the arithmetic."] }]);
registerModuleVariants("dinner.conv.after_dinner_stroll", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.conv.awkward_comment", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.conv.suggest_diet", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.conv.ask_about_weight", [{ when: {}, text: ["The question hangs. She picks up her fork again, but something has shifted.", "You bring up her body. {subject.name} stills — the ease of dinner fractures."] }]);
registerModuleVariants("dinner.conv.second_table", [{ when: {}, text: ["You move her somewhere more comfortable. {subject.name} settles and orders again immediately.", "A better chair, more room. She sighs with relief and signals the server."] }]);
registerModuleVariants("dinner.groupTopic", [{ when: {}, text: ["something she has been thinking about", "a story she has not told yet"] }]);
registerModuleVariants("dinner.groupConv.get_them_talking", [{ when: {}, text: ["{dinner.groupConv.get_them_talking.l1}\n{dinner.groupConv.get_them_talking.l2}\n{dinner.groupConv.get_them_talking.l3}", "{dinner.groupConv.get_them_talking.l1}\n{dinner.groupConv.get_them_talking.l4}"] }]);
registerModuleVariants("dinner.groupConv.get_them_talking.l1", [{ when: {}, text: ["You steer the talk somewhere real. Both of them lean in.", "A question opens the table — appetite and curiosity answer together."] }]);
registerModuleVariants("dinner.groupConv.get_them_talking.l2", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.groupConv.get_them_talking.l3", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.groupConv.get_them_talking.l4", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.groupConv.compliment_both", [{ when: {}, text: ["{dinner.groupConv.compliment_both.l1}\n{dinner.groupConv.compliment_both.l3}", "{dinner.groupConv.compliment_both.l2}\n{dinner.groupConv.compliment_both.l3}"] }]);
registerModuleVariants("dinner.groupConv.compliment_both.l1", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.groupConv.compliment_both.l2", [{ when: {}, text: ["Surprise and interest cross {ref.name}'s face — then appetite returns.", "{ref.name} reacts before you finish the thought."] }]);
registerModuleVariants("dinner.groupConv.compliment_both.l3", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.groupConv.let_it_settle", [{ when: {}, text: ["{dinner.groupConv.let_it_settle.l1}\n{dinner.groupConv.let_it_settle.l3}", "{dinner.groupConv.let_it_settle.l2}\n{dinner.groupConv.let_it_settle.l3}"] }]);
registerModuleVariants("dinner.groupConv.let_it_settle.l1", [{ when: {}, text: ["A question opens the table — appetite and curiosity answer together.", "You steer the talk somewhere real. Both of them lean in."] }]);
registerModuleVariants("dinner.groupConv.let_it_settle.l2", [{ when: {}, text: ["Surprise and interest cross {ref.name}'s face — then appetite returns.", "{ref.name} reacts before you finish the thought."] }]);
registerModuleVariants("dinner.groupConv.let_it_settle.l3", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.groupConv.toast_together_group", [{ when: {}, text: ["{dinner.groupConv.toast_together_group.l2}\n{dinner.groupConv.toast_together_group.l3}", "{dinner.groupConv.toast_together_group.l1}\n{dinner.groupConv.toast_together_group.l3}"] }]);
registerModuleVariants("dinner.groupConv.toast_together_group.l1", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.groupConv.toast_together_group.l2", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.groupConv.toast_together_group.l3", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.groupConv.order_for_table", [{ when: {}, text: ["{dinner.groupConv.order_for_table.l1}\n{dinner.groupConv.order_for_table.l3}", "{dinner.groupConv.order_for_table.l2}\n{dinner.groupConv.order_for_table.l3}"] }]);
registerModuleVariants("dinner.groupConv.order_for_table.l1", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.groupConv.order_for_table.l2", [{ when: {}, text: ["{ref.name} reacts before you finish the thought.", "Surprise and interest cross {ref.name}'s face — then appetite returns."] }]);
registerModuleVariants("dinner.groupConv.order_for_table.l3", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.moodTone", [{ when: {}, text: ["The table holds an easy rhythm between courses.", "Quiet pleasure sits with you — appetite unhurried, mood soft.", "Something warm in the room matches what is on her plate."] }]);
registerModuleVariants("dinner.seasonAmbience", [{ when: {}, text: ["The restaurant wraps you in low light and butter-warm air.", "Outside noise dulls; inside, appetite feels like the point.", "The room smells of reduction and bread — indulgence in the walls."] }]);
registerModuleVariants("dinner.relWarmth", [{ when: {}, text: ["Familiar ease at the table — no performance, just appetite.", "She eats like someone who trusts the person across from her.", "Small kindnesses between courses deepen the warmth."] }]);
registerModuleVariants("dinner.selectorOverlay", [{ when: {}, text: ["Soft laughter and clinking glass; the evening leans toward indulgence.", "Candlelight catches the curve of her satisfaction — unhurried, present, real."] }]);
registerModuleVariants("dinner.campusNote", [{ when: {}, text: ["Campus life feels far away; dinner is its own country tonight.", "Whatever happened today, the table resets appetite to priority.", "The meal feels like shelter from everything outside."] }]);
registerModuleVariants("dinner.relSizeNote", [{ when: {}, text: ["Bodies take space at the table; neither of you pretends otherwise.", "She settles into her chair like she owns the evening.", "Scale shows in how the table arranges itself around her."] }]);
registerModuleVariants("dinner.skillNote", [{ when: {}, text: ["Something in your attention steadies her appetite tonight.", "She follows your lead at the table — fork, glass, next course.", "Hunger answers you before she names it aloud."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f1", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f2", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f3", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f4", [{ when: {}, text: ["{subject.name} watches {ref.name} eat with quiet fascination.", "Warmth and fullness on display; {subject.name} cannot look away."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f5", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f6", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f7", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f8", [{ when: {}, text: [". The warmth between them sharpens — appetite and attention braided.", ". Fullness shows in how she holds herself now."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f9", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f10", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f11", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f12", [{ when: {}, text: [". Fullness shows in how she holds herself now.", ". The table feels smaller for how much she has taken in."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f13", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f14", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f15", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f16", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f17", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f18", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f19", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f20", [{ when: {}, text: [". Warmth pools where hands and fabric meet.", ". Comfort arrives in layers — food, heat, permission."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f21", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f22", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f23", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f24", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f25", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f26", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f27", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f28", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f29", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f30", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f31", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f32", [{ when: {}, text: [". Something hungry settles in the silence.", ". She leans into the moment without apology."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f33", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f34", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f35", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f36", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f37", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f38", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f39", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f40", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f41", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f42", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f43", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f44", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f45", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f46", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f47", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f48", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f49", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f50", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f51", [{ when: {}, text: ["She touches her own empty place setting, then looks back at {ref.name}.", "Her eyes track every bite — hunger dressed as curiosity."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f52", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f53", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f54", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f55", [{ when: {}, text: [". The table feels smaller for how much she has taken in.", ". She does not look away from the plate."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f56", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f57", [{ when: {}, text: [". Fullness shows in how she holds herself now.", ". The table feels smaller for how much she has taken in."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f58", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f59", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f60", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f61", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f62", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f63", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f64", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f65", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f66", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f67", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f68", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f69", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f70", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f71", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f72", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinJealousy._f73", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.thinJealousy", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f74", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f75", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f76", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f77", [{ when: {}, text: [". The table feels smaller for how much she has taken in.", ". She does not look away from the plate."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f78", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f79", [{ when: {}, text: [". The warmth between them sharpens — appetite and attention braided.", ". Fullness shows in how she holds herself now."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f80", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f81", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f82", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f83", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f84", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f85", [{ when: {}, text: [". The table feels smaller for how much she has taken in.", ". She does not look away from the plate."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f86", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f87", [{ when: {}, text: [". Warmth pools where hands and fabric meet.", ". Comfort arrives in layers — food, heat, permission."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f88", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f89", [{ when: {}, text: [". Warmth pools where hands and fabric meet.", ". Comfort arrives in layers — food, heat, permission."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f90", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f91", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f92", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f93", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f94", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f95", [{ when: {}, text: [". She leans into the moment without apology.", ". Something hungry settles in the silence."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f96", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f97", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f98", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f99", [{ when: {}, text: [". The warmth between them sharpens — appetite and attention braided.", ". Fullness shows in how she holds herself now."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f100", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f101", [{ when: {}, text: [". Fullness shows in how she holds herself now.", ". The table feels smaller for how much she has taken in."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f102", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f103", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f104", [{ when: {}, text: ["She eats with the ease of someone finally allowed to want.", "The table holds warmth between courses; appetite has its own gravity tonight."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f105", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f106", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f107", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f108", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f109", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f110", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f111", [{ when: {}, text: [". She does not look away from the plate.", ". The warmth between them sharpens — appetite and attention braided."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f112", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f113", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f114", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f115", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f116", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f117", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f118", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f119", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f120", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f121", [{ when: {}, text: [". Warmth pools where hands and fabric meet.", ". Comfort arrives in layers — food, heat, permission."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f122", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f123", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f124", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f125", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f126", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f127", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f128", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f129", [{ when: {}, text: [". Warmth pools where hands and fabric meet.", ". Comfort arrives in layers — food, heat, permission."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f130", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f131", [{ when: {}, text: [". Her voice goes soft around the edges of want.", ". The restaurant hum fades; this is the whole evening."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f132", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f133", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f134", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.fatEncourage._f135", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.fatEncourage", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f136", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f137", [{ when: {}, text: [". Something hungry settles in the silence.", ". She leans into the moment without apology."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f138", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f139", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f140", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f141", [{ when: {}, text: [". The restaurant hum fades; this is the whole evening.", ". Warmth pools where hands and fabric meet."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f142", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f143", [{ when: {}, text: [". Fullness shows in how she holds herself now.", ". The table feels smaller for how much she has taken in."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f144", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f145", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f146", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f147", [{ when: {}, text: [". Comfort arrives in layers — food, heat, permission.", ". Her voice goes soft around the edges of want."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f148", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f149", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f150", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f151", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f152", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f153", [{ when: {}, text: [". She does not look away from the plate.", ". The warmth between them sharpens — appetite and attention braided."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f154", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f155", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f156", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f157", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f158", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.fatRetort._f159", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.fatRetort", [{ when: {}, text: ["Comfort pools in her middle; she makes no move to hide it.", "Warmth and fullness settle between you — patient, sensual, sure."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f160", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f161", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f162", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f163", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f164", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f165", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f166", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f167", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f168", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f169", [{ when: {}, text: [". Her voice goes soft around the edges of want.", ". The restaurant hum fades; this is the whole evening."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f170", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f171", [{ when: {}, text: [". The restaurant hum fades; this is the whole evening.", ". Warmth pools where hands and fabric meet."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f172", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f173", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f174", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f175", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f176", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f177", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f178", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f179", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f180", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f181", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f182", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f183", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f184", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f185", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f186", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f187", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f188", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f189", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f190", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f191", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f192", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f193", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f194", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f195", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f196", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f197", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f198", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f199", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f200", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f201", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f202", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f203", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f204", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f205", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f206", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f207", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f208", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f209", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f210", [{ when: {}, text: ["\"Stay,\" she breathes, eyes on your plate and hers.", "\"I want that,\" she says — plain, honest, hungry."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f211", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f212", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f213", [{ when: {}, text: ["\"More,\" she says, like it costs her nothing.", "\"Keep watching,\" she tells you, fork already moving."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f214", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.reaction.thinContextual._f215", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.reaction.thinContextual", [{ when: {}, text: ["Warmth and fullness settle between you — patient, sensual, sure.", "Comfort pools in her middle; she makes no move to hide it."] }]);
registerModuleVariants("dinner.reaction.jealousyDefault", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.waiter.bistro._f1", [{ when: {}, text: ["\"I want that,\" she says — plain, honest, hungry.", "\"Stay,\" she breathes, eyes on your plate and hers."] }]);
registerModuleVariants("dinner.waiter.bistro", [{ when: {}, text: ["Bread refilled before you ask — the bistro runs on generosity.", "A softly built woman in a bistro apron smiles at {subject.name}. \"Ready for more?\""] }]);
registerModuleVariants("dinner.waiter.italian._f1", [{ when: {}, text: ["\"Keep watching,\" she tells you, fork already moving.", "\"More,\" she says, like it costs her nothing."] }]);
registerModuleVariants("dinner.waiter.italian", [{ when: {}, text: ["A round, bustling server beams and refills the bread without ceremony.", "\"More? Of course more.\" Family Italian logic, delivered with warmth."] }]);
registerModuleVariants("dinner.waiter.steakhouse._f1", [{ when: {}, text: ["\"I know,\" she answers, warm and unhurried.", "\"I could get used to this,\" she says, almost to herself."] }]);
registerModuleVariants("dinner.waiter.steakhouse._f2", [{ when: {}, text: [". Comfort arrives in layers — food, heat, permission.", ". Her voice goes soft around the edges of want."] }]);
registerModuleVariants("dinner.waiter.steakhouse", [{ when: {}, text: ["A solid woman in a leather apron surveys cleared plates with approval.", "She nods at the wreckage of courses. \"Next round?\" Professional, unhurried."] }]);
registerModuleVariants("dinner.waiter.french._f1", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.waiter.french", [{ when: {}, text: ["The sommelier drifts over — substantial, crisp, refilling wine without comment.", "Formal service, soft authority: \"Another course?\""] }]);
registerModuleVariants("dinner.waiter.japanese._f1", [{ when: {}, text: ["She appears and vanishes like ritual; {subject.name} reaches for the fresh menu.", "Quiet formal service — chopsticks replaced, water refreshed, menu waiting."] }]);
registerModuleVariants("dinner.waiter.japanese", [{ when: {}, text: ["She appears and vanishes like ritual; {subject.name} reaches for the fresh menu.", "Quiet formal service — chopsticks replaced, water refreshed, menu waiting."] }]);
registerModuleVariants("dinner.waiter.private_club._f1", [{ when: {}, text: ["Discreet service in a private room — anticipation handled like luxury.", "The server knows when to appear; the next course is already implied."] }]);
registerModuleVariants("dinner.waiter.private_club._f2", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.waiter.private_club", [{ when: {}, text: ["Discreet service in a private room — anticipation handled like luxury.", "The server knows when to appear; the next course is already implied."] }]);
registerModuleVariants("dinner.waiter.chefs_table._f1", [{ when: {}, text: ["The kitchen sends its ambassador — pride and portions in equal measure.", "Chef's-table service: each arrival feels like an event."] }]);
registerModuleVariants("dinner.waiter.chefs_table._f2", [{ when: {}, text: ["\"I could get used to this,\" she says, almost to herself.", "\"I know,\" she answers, warm and unhurried."] }]);
registerModuleVariants("dinner.waiter.chefs_table", [{ when: {}, text: ["The kitchen sends its ambassador — pride and portions in equal measure.", "Chef's-table service: each arrival feels like an event."] }]);
registerModuleVariants("dinner.waiter.home_dinner._f1", [{ when: {}, text: ["You clear space and bring more — domestic warmth, no performance.", "The table is yours; seconds land like love language."] }]);
registerModuleVariants("dinner.waiter.home_dinner", [{ when: {}, text: ["You clear space and bring more — domestic warmth, no performance.", "The table is yours; seconds land like love language."] }]);
registerModuleVariants("dinner.waiter.brunch_hall._f1", [{ when: {}, text: ["\"That looks incredible,\" she admits, already reaching.", "\"Don't stop,\" she murmurs — meaning the food, maybe more."] }]);
registerModuleVariants("dinner.waiter.brunch_hall", [{ when: {}, text: ["Brunch service hums — syrup, coffee, and another plate before she asks.", "The hall runs on abundance; your server keeps pace without fuss."] }]);
registerModuleVariants("dinner.waiter.atelier._f1", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.waiter.atelier._f2", [{ when: {}, text: ["Each course arrives like a small ceremony; appetite is part of the design.", "Artful service matches artful plates — precision with indulgence underneath."] }]);
registerModuleVariants("dinner.waiter.atelier", [{ when: {}, text: ["Artful service matches artful plates — precision with indulgence underneath.", "Each course arrives like a small ceremony; appetite is part of the design."] }]);
registerModuleVariants("dinner.waiter", [{ when: {}, text: ["Soft laughter and clinking glass; the evening leans toward indulgence.", "Candlelight catches the curve of her satisfaction — unhurried, present, real."] }]);
registerModuleVariants("dinner.setup", [{ when: {}, text: ["Comfort pools in her middle; she makes no move to hide it.", "Warmth and fullness settle between you — patient, sensual, sure."] }]);
registerModuleVariants("dinner.courseReaction", [{ when: {}, text: ["Candlelight catches the curve of her satisfaction — unhurried, present, real.", "Soft laughter and clinking glass; the evening leans toward indulgence."] }]);
registerModuleVariants("dinner.endReflection", [{ when: {}, text: ["She eats with the ease of someone finally allowed to want.", "The table holds warmth between courses; appetite has its own gravity tonight."] }]);
registerModuleVariants("dinner.exit", [{ when: {}, text: ["She eats with the ease of someone finally allowed to want.", "The table holds warmth between courses; appetite has its own gravity tonight."] }]);
registerModuleVariants("dinner.depth", [{ when: {}, text: ["{dinner.setup} {dinner.courseReaction} {dinner.endReflection}", "{dinner.setup}\n{dinner.courseReaction}\n{dinner.endReflection}\n{dinner.exit}"] }]);
registerModuleVariants("dinner.overfill", [{ when: {}, text: ["\"Don't stop,\" she murmurs — meaning the food, maybe more.", "\"That looks incredible,\" she admits, already reaching."] }]);
registerModuleVariants("dinner.endOpen", [{ when: {}, text: ["{subject.name} leans back as the last plate clears — warm, full, unhurried.", "The meal winds down; {subject.name} looks satisfied in the deep way only a long dinner produces."] }]);
registerModuleVariants("dinner.endClose", [{ when: {}, text: ["She pats her middle once, content. \"That was exactly what I needed.\"", "The check arrives; she is in no hurry to leave — fullness has its own gravity."] }]);
registerModuleVariants("dinner.ending", [{ when: {}, text: ["{dinner.endOpen}\n{dinner.endClose}", "{dinner.endOpen} {dinner.endClose}"] }]);
registerModuleVariants("dinner.dish.soup_bread", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.pasta", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.salad_big", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.bruschetta", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.risotto", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.lasagne", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.tiramisu", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.shrimp_cocktail", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.ribeye", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.loaded_potato", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.cheesecake", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.amuse", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.foie_gras", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.duck_confit", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.soufle", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.cheese", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.sashimi", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.wagyu", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.ramen", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.mochi", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.tasting_menu", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.wagyu_private", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.truffle_pasta", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.mille_feuille", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.personal_menu", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.wagyu_special", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.dessert_cart", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.home_app", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.home_main", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.home_second", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.home_dessert", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.midnight", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.eggs_bene", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.french_toast", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.brunch_board", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.waffle_stack", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.atelier_welcome", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.atelier_main", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.atelier_cheese", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.atelier_dessert", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.atelier_nightcap", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.pr_board", [{ when: {}, text: ["A generous start — rich enough to promise the rest of the evening.", "Warm opening notes; appetite wakes up and stays."] }]);
registerModuleVariants("dinner.dish.pr_soup", [{ when: {}, text: ["A generous start — rich enough to promise the rest of the evening.", "Warm opening notes; appetite wakes up and stays."] }]);
registerModuleVariants("dinner.dish.pr_bruschetta", [{ when: {}, text: ["A generous start — rich enough to promise the rest of the evening.", "Warm opening notes; appetite wakes up and stays."] }]);
registerModuleVariants("dinner.dish.pr_pasta", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.pr_risotto", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.pr_roast", [{ when: {}, text: ["Portions meant to be taken seriously; she does.", "Substantial and slow — the kind of main that sits heavy and welcome."] }]);
registerModuleVariants("dinner.dish.pr_burger", [{ when: {}, text: ["Substantial and slow — the kind of main that sits heavy and welcome.", "Portions meant to be taken seriously; she does."] }]);
registerModuleVariants("dinner.dish.pr_more_pasta", [{ when: {}, text: ["Another round — warmth and weight keep building.", "More arrives; she accepts like it was always the plan."] }]);
registerModuleVariants("dinner.dish.pr_bread", [{ when: {}, text: ["Another round — warmth and weight keep building.", "More arrives; she accepts like it was always the plan."] }]);
registerModuleVariants("dinner.dish.pr_sides", [{ when: {}, text: ["More arrives; she accepts like it was always the plan.", "Another round — warmth and weight keep building."] }]);
registerModuleVariants("dinner.dish.pr_cake", [{ when: {}, text: ["The finish asks for patience and rewards it.", "Sweet density — indulgence without apology."] }]);
registerModuleVariants("dinner.dish.pr_icecream", [{ when: {}, text: ["The finish asks for patience and rewards it.", "Sweet density — indulgence without apology."] }]);
registerModuleVariants("dinner.dish.pr_brownie", [{ when: {}, text: ["The finish asks for patience and rewards it.", "Sweet density — indulgence without apology."] }]);
registerModuleVariants("dinner.dish.pr_mille", [{ when: {}, text: ["Sweet density — indulgence without apology.", "The finish asks for patience and rewards it."] }]);
registerModuleVariants("dinner.dish.pr_snack_tray", [{ when: {}, text: ["Small extra that feels enormous after everything else.", "Late generosity — no explanation required."] }]);
registerModuleVariants("dinner.dish.pr_wine_cheese", [{ when: {}, text: ["Small extra that feels enormous after everything else.", "Late generosity — no explanation required."] }]);
registerModuleVariants("dinner.dish.pr_chocolates", [{ when: {}, text: ["Late generosity — no explanation required.", "Small extra that feels enormous after everything else."] }]);
